/* ########
 * 2024 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import {SrcCodeCompilerConstants, compileTypeToJs, runTypeCompilerConstants} from './jitFnCacheCompiler';
import {
    JitCompiledFn,
    CompiledPureFunction,
    SrcCodeJITCompiledFnsCache,
    SrcCodePureFunctionsCache,
    getFnCaches,
} from '@mionkit/core';
import {JitFunctions} from '../constants.functions';
import {jitUtils} from '@mionkit/core';

it('should compile JIT functions cache to code', () => {
    const {jitFnsCache} = getFnCaches();
    // a real scenario would use compileAndWriteJitFunctions instead compileTypeToJs to persis to fileSystem

    // Create a mock JitFunctionsCache
    const mockCache = {};
    const compOpts = {
        ...runTypeCompilerConstants,
        typeName: 'JIT functions',
        files: {
            jit: {path: '/test/path/jitFunctionsCache.esm.js', module: 'esm'},
            pure: {path: '', module: 'esm'},
        },
        opts: {isJitFnCode: true},
    } satisfies SrcCodeCompilerConstants;

    // Add a mock JIT function to the cache
    const mockJitFn: JitCompiledFn = {
        typeName: 'compiledTypeName',
        fnID: JitFunctions.isType.id,
        jitFnHash: 'sayHello',
        args: {vλl: 'v'},
        defaultParamValues: {vλl: ''},
        // this should be generated by jit and include the context code
        code: 'function sayHello(name) {return "Hello " + name;} return sayHello;',
        dependenciesSet: new Set<string>(),
        pureFnDependencies: new Set<string>(),
        // these two must be equivalent to code
        fn: (name: string) => 'Hello ' + name,
        closureFn: (utl) => (name: string) => 'Hello ' + name,
    };
    mockCache['sayHello'] = mockJitFn;

    // Call the function under test
    const compiledMock = compileTypeToJs<SrcCodeJITCompiledFnsCache>(mockCache, compOpts, 'esm');
    // Check that the file code contains the export statement with the correct export name
    expect(compiledMock).toContain(`export const ${compOpts.exportName} =`);
    const evalCode = compiledMock.replace(`export const ${compOpts.exportName} =`, '');
    const evalResult = eval(`(${evalCode})`);
    evalResult['sayHello'].fn = evalResult['sayHello'].closureFn(jitUtils);
    expect(evalResult['sayHello'].fn('Karol')).toBe('Hello Karol');

    // guarantees cache in core package can be compiled
    // this contains any jit functions that are used by core package or mion packages
    const compiledCorePackage = compileTypeToJs<SrcCodeJITCompiledFnsCache>(jitFnsCache as any, compOpts, 'esm');
    expect(compiledCorePackage).toContain(`export const ${compOpts.exportName} =`);
    const realEvalCode = compiledCorePackage.replace(`export const ${compOpts.exportName} =`, '');
    expect(() => eval(`(${realEvalCode})`)).not.toThrow();

    // console.log('compiledMock:', compiledMock);
    // console.log('compiledCorePackage:', compiledCorePackage);
});

it('should compile pure functions cache to code', () => {
    const {pureFnsCache} = getFnCaches();
    // a real scenario would use compileAndSaveTypeToJs instead compileTypeToJs to persis to fileSystem

    // Create a mock PureFunctionsCache
    const mockCache = {};
    const compOpts = {
        ...runTypeCompilerConstants,
        typeName: 'Pure functions',
        files: {
            jit: {path: '', module: 'esm'},
            pure: {path: '/test/path/pureFunctionsCache.esm.js', module: 'esm'},
        },
        opts: {isPureFnCode: true},
    } satisfies SrcCodeCompilerConstants;

    // Add a mock pure function to the cache
    const mockPureFn: CompiledPureFunction = {
        closureFn: (jitUtils) => (a: number, b: number) => a + b,
        fn: (a: number, b: number) => a + b,
        paramNames: ['a', 'b'],
        code: 'function addNumbers(a, b) {return a + b;} return addNumbers;',
        pureFnHash: 'addNumbers',
        dependencies: new Set<string>(),
    };
    mockCache['addNumbers'] = mockPureFn;

    // Call the function under test
    const compiledMock = compileTypeToJs<SrcCodePureFunctionsCache>(mockCache, compOpts, 'esm');
    // Check that the file code contains the export statement with the correct export name
    expect(compiledMock).toContain(`export const ${compOpts.exportName} =`);

    // Verify the code can be evaluated and contains our mock cache
    const evalCode = compiledMock.replace(`export const ${compOpts.exportName} =`, '');
    const evalResult = eval(`(${evalCode})`);
    evalResult['addNumbers'].fn = evalResult['addNumbers'].closureFn(jitUtils);
    expect(evalResult.addNumbers.fn(1, 2)).toBe(3);

    // guarantees (real cache) in core package can be compiled
    // this contains any pure functions that are used by core package or mion packages
    const compiledCorePackage = compileTypeToJs<SrcCodePureFunctionsCache>(pureFnsCache as any, compOpts, 'esm');
    expect(compiledCorePackage).toContain(`export const ${compOpts.exportName} =`);
    const realEvalCode = compiledCorePackage.replace(`export const ${compOpts.exportName} =`, '');
    expect(() => eval(`(${realEvalCode})`)).not.toThrow();

    // console.log('compiledMock:', compiledMock);
    // console.log('compiledCorePackage:', compiledCorePackage);
});

it('should use absolute file paths in SrcCodeCompilerConstants', () => {
    // Test that the new structure uses absolute file paths
    const testFiles = {
        jit: {path: '/absolute/path/to/jitFunctionsCache.esm.js', module: 'esm' as const},
        pure: {path: '/absolute/path/to/pureFunctionsCache.cjs.js', module: 'cjs' as const},
    };

    const compOpts = {
        ...runTypeCompilerConstants,
        typeName: 'Test functions',
        files: testFiles,
        opts: {isJitFnCode: true},
    } satisfies SrcCodeCompilerConstants;

    expect(compOpts.files.jit.path).toBe(testFiles.jit.path);
    expect(compOpts.files.jit.module).toBe(testFiles.jit.module);
    expect(compOpts.files.pure.path).toBe(testFiles.pure.path);
    expect(compOpts.files.pure.module).toBe(testFiles.pure.module);
});

it('should generate CommonJS format for cjs module type', () => {
    // Use a proper mock cache structure similar to the JIT functions test
    const mockCache: SrcCodeJITCompiledFnsCache = {};
    const mockJitFn: SrcCodeJitCompiledFn = {
        typeName: 'string',
        fnID: 'isType',
        jitFnHash: 'testFn',
        args: {vλl: 'v'},
        defaultParamValues: {vλl: ''},
        code: 'return typeof v === "string";',
        dependenciesSet: new Set<string>(),
        pureFnDependencies: new Set<string>(),
        closureFn: (utl) => (name: string) => typeof name === 'string',
    };
    mockCache['testFn'] = mockJitFn;

    const compOpts = {
        ...runTypeCompilerConstants,
        typeName: 'Test functions',
        files: {
            jit: {path: '/test/path/jitFunctionsCache.cjs.js', module: 'cjs' as const},
            pure: {path: '', module: 'cjs' as const},
        },
        opts: {isJitFnCode: true},
    } satisfies SrcCodeCompilerConstants;

    // Test CommonJS format
    const cjsCode = compileTypeToJs(mockCache, compOpts, 'cjs');
    expect(cjsCode).toContain(`module.exports = { ${compOpts.exportName}:`);
    expect(cjsCode).not.toContain('export const');

    // Test ESM format
    const esmCode = compileTypeToJs(mockCache, compOpts, 'esm');
    expect(esmCode).toContain(`export const ${compOpts.exportName} =`);
    expect(esmCode).not.toContain('module.exports');
});
