/* ########
 * 2024 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import {SrcCodeCompilerConstants, compileTypeToJs, runTypeCompilerConstants, findJSFile} from './jitFnCacheCompiler';
import {JitCompiledFn, CompiledPureFunction, SrcCodeJITCompiledFnsCache, SrcCodePureFunctionsCache} from '@mionkit/core';
import {JitFunctions} from '../constants.functions';
import {cΦmpilεdCachε as jitFnsCache} from '@mionkit/core';
import {cΦmpilεdCachε as pureFnsCache} from '@mionkit/core';
import {jitUtils} from '@mionkit/core';
import {existsSync, mkdirSync, unlinkSync, writeFileSync} from 'fs';
import {join} from 'path';

it('should compile JIT functions cache to code', () => {
    // a real scenario would use compileAndWriteJitFunctions instead compileTypeToJs to persis to fileSystem

    // Create a mock JitFunctionsCache
    const mockCache = {};
    const compOpts = {
        ...runTypeCompilerConstants,
        typeName: 'Pure functions',
        files: runTypeCompilerConstants.jitFunctionsFiles,
        opts: {isJitFnCode: true},
    } satisfies SrcCodeCompilerConstants;

    // Add a mock JIT function to the cache
    const mockJitFn: JitCompiledFn = {
        typeName: 'compiledTypeName',
        fnID: JitFunctions.isType.id,
        jitFnHash: 'sayHello',
        args: {vλl: 'v'},
        defaultParamValues: {vλl: ''},
        // this should be generated by jit and include the context code
        code: 'function sayHello(name) {return "Hello " + name;} return sayHello;',
        dependenciesSet: new Set<string>(),
        pureFnDependencies: new Set<string>(),
        // these two must be equivalent to code
        fn: (name: string) => 'Hello ' + name,
        closureFn: (utl) => (name: string) => 'Hello ' + name,
    };
    mockCache['sayHello'] = mockJitFn;

    // Call the function under test
    const compiledMock = compileTypeToJs<SrcCodeJITCompiledFnsCache>(mockCache, compOpts);
    // Check that the file code contains the export statement with the correct export name
    expect(compiledMock).toContain(`export const ${compOpts.exportName} =`);
    const evalCode = compiledMock.replace(`export const ${compOpts.exportName} =`, '');
    const evalResult = eval(`(${evalCode})`);
    evalResult['sayHello'].fn = evalResult['sayHello'].closureFn(jitUtils);
    expect(evalResult['sayHello'].fn('Karol')).toBe('Hello Karol');

    // guarantees cache in core package can be compiled
    // this contains any jit functions that are used by core package or mion packages
    const compiledCorePackage = compileTypeToJs<SrcCodeJITCompiledFnsCache>(jitFnsCache, compOpts);
    expect(compiledCorePackage).toContain(`export const ${compOpts.exportName} =`);
    const realEvalCode = compiledCorePackage.replace(`export const ${compOpts.exportName} =`, '');
    expect(() => eval(`(${realEvalCode})`)).not.toThrow();

    // console.log('compiledMock:', compiledMock);
    // console.log('compiledCorePackage:', compiledCorePackage);
});

it('should compile pure functions cache to code', () => {
    // a real scenario would use compileAndSaveTypeToJs instead compileTypeToJs to persis to fileSystem

    // Create a mock PureFunctionsCache
    const mockCache = {};
    const compOpts = {
        ...runTypeCompilerConstants,
        typeName: 'Pure functions',
        files: runTypeCompilerConstants.pureFunctionsFiles,
        opts: {isPureFnCode: true},
    } satisfies SrcCodeCompilerConstants;

    // Add a mock pure function to the cache
    const mockPureFn: CompiledPureFunction = {
        closureFn: (jitUtils) => (a: number, b: number) => a + b,
        fn: (a: number, b: number) => a + b,
        paramNames: ['a', 'b'],
        code: 'function addNumbers(a, b) {return a + b;} return addNumbers;',
        pureFnHash: 'addNumbers',
        dependencies: new Set<string>(),
    };
    mockCache['addNumbers'] = mockPureFn;

    // Call the function under test
    const compiledMock = compileTypeToJs<SrcCodePureFunctionsCache>(mockCache, compOpts);
    // Check that the file code contains the export statement with the correct export name
    expect(compiledMock).toContain(`export const ${compOpts.exportName} =`);

    // Verify the code can be evaluated and contains our mock cache
    const evalCode = compiledMock.replace(`export const ${compOpts.exportName} =`, '');
    const evalResult = eval(`(${evalCode})`);
    evalResult['addNumbers'].fn = evalResult['addNumbers'].closureFn(jitUtils);
    expect(evalResult.addNumbers.fn(1, 2)).toBe(3);

    // guarantees (real cache) in core package can be compiled
    // this contains any pure functions that are used by core package or mion packages
    const compiledCorePackage = compileTypeToJs<SrcCodePureFunctionsCache>(pureFnsCache, compOpts);
    expect(compiledCorePackage).toContain(`export const ${compOpts.exportName} =`);
    const realEvalCode = compiledCorePackage.replace(`export const ${compOpts.exportName} =`, '');
    expect(() => eval(`(${realEvalCode})`)).not.toThrow();

    // console.log('compiledMock:', compiledMock);
    // console.log('compiledCorePackage:', compiledCorePackage);
});

function createDirAndWriteFile(dir: string, file: string) {
    if (!existsSync(dir)) mkdirSync(dir, {recursive: true});
    const filePath = join(dir, file);
    writeFileSync(filePath, 'export const cΦmpilεdCachε = {};\n', 'utf8');
}

function deleteFile(dir: string, file: string) {
    const filePath = join(dir, file);
    if (existsSync(filePath)) {
        unlinkSync(filePath);
    }
}

it('should find .dist files in @mionkit/core package', () => {
    // compileAndWriteJitFunctions and compileAndWritePureFunctions work only after code gets compiled
    // for testing lets find fe files in the core package as test
    const dirCjs = join(__dirname, '../../../core/dist/cjs/_autogen');
    const dirEsm = join(__dirname, '../../../core/dist/esm/_autogen');
    const filesCjs = ['jitFunctionsCache.js', 'pureFunctionsCache.js'];
    const filesEsm = ['jitFunctionsCache.mjs', 'pureFunctionsCache.mjs'];

    filesCjs.forEach((file) => createDirAndWriteFile(dirCjs, file));
    filesEsm.forEach((file) => createDirAndWriteFile(dirEsm, file));

    const packageName = '@mionkit/core';
    const files = [
        './dist/cjs/_autogen/jitFunctionsCache',
        './dist/cjs/_autogen/pureFunctionsCache',
        './dist/esm/_autogen/jitFunctionsCache',
        './dist/esm/_autogen/pureFunctionsCache',
    ];
    const fullFileNames = files.map((file) => findJSFile(packageName, file)) as string[];
    expect(fullFileNames.every(Boolean)).toBe(true);

    filesCjs.forEach((file) => deleteFile(dirCjs, file));
    filesEsm.forEach((file) => deleteFile(dirEsm, file));
});
