// Writes the measured numbers to committed artifacts: a JSON file for tooling
// and a Markdown table for humans.
//
// Both are COMMITTED on purpose. The budgets are hand-maintained, so a report
// that moves without a budget moving is the signal that something changed the
// cost, and it shows up in the pull request diff where a reviewer will see it.
// Nothing time-varying goes in (no timestamps, no durations): the counts are
// deterministic under the exact-pinned `typescript` and `drizzle-orm`, so any
// diff at all means a real change.

import {writeFileSync, mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const REPORT_DIR = fileURLToPath(new URL('../reports/', import.meta.url));

export interface StepReport {
  step: number;
  label: string;
  /** Net instantiations this step added over the previous one. **/
  delta: number;
  budget: number;
  /** Net instantiations of the whole snippet up to and including this step. **/
  cumulative: number;
}

export interface ConsumerReport {
  budget: number;
  netInstantiations: number;
  keepsGenericAlias: boolean;
  dtsBytes: number;
}

export interface PipelineReport {
  typescript: string;
  drizzleOrm: string;
  steps: StepReport[];
  consumer: ConsumerReport;
}

function markdown(report: PipelineReport): string {
  const rows = report.steps.map((s) => `| ${s.step} | ${s.label} | ${s.delta} | ${s.budget} | ${s.cumulative} |`).join('\n');
  const total = report.steps.reduce((sum, s) => sum + s.delta, 0);
  return `# Model pipeline type-instantiation report

Generated by \`packages/type-budget/test/modelPipeline.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript} and drizzle-orm ${report.drizzleOrm}.

## Per-step cost, compiled from source

Each step adds one layer to the previous snippet. The delta is what that layer
costs the type checker; the cumulative total is mostly drizzle's own types and
carries no signal on its own. Budgets may only ever be lowered.

| Step | Layer | Net instantiations added | Budget | Cumulative |
| ---: | ----- | -----------------------: | -----: | ---------: |
${rows}

Total for the whole chain: **${total}**.

Every one of these is paid again on every keystroke. TypeScript memoises type
instantiations within a single check, but each edit builds a new checker, so the
work is redone. Parsing is reused across edits; type instantiation is not.

## Downstream consumer cost, read from the emitted \`.d.ts\`

| What | Value |
| ---- | ----: |
| Consumer net instantiations | ${report.consumer.netInstantiations} |
| Budget | ${report.consumer.budget} |
| Emitted declaration size (bytes) | ${report.consumer.dtsBytes} |
| Declaration keeps the generic alias unresolved | ${report.consumer.keepsGenericAlias ? 'yes' : 'no'} |

Declaration emit prints the type alias as it was written, never the type it
evaluates to, so \`export type User = InferSelect<typeof api>\` crosses the package
boundary unresolved. None of the producer's work is banked: every consumer runs
the refine surgery again in their own checker.
`;
}

/** Write reports/model-pipeline.{json,md}. **/
export function writeReport(report: PipelineReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}model-pipeline.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}model-pipeline.md`, markdown(report));
}

// ── Lane comparison ──────────────────────────────────────────────────────────

export interface LaneStepReport {
  step: number;
  label: string;
  delta: number;
  budget: number;
}

export interface LaneReport {
  name: string;
  steps: LaneStepReport[];
  total: number;
}

export interface ComparisonReport {
  typescript: string;
  drizzleOrm: string;
  lanes: LaneReport[];
}

// Each lane names its own first two steps ("plain drizzle table" vs "plain row
// type" vs "plain builder object"), so the shared table needs labels that fit
// every column. Per-lane spellings stay in the JSON.
const NEUTRAL_STEP_LABELS = [
  'declare the row',
  'add the column formats',
  'refine two columns',
  'select / insert / update models',
  'mion route api',
  'initClient',
];

function comparisonMarkdown(report: ComparisonReport): string {
  const [first] = report.lanes;
  const names = report.lanes.map((l) => l.name);
  const head = `| Step | Layer | ${names.join(' | ')} |`;
  const rule = `| ---: | ----- | ${names.map(() => '---:').join(' | ')} |`;
  const rows = first.steps
    .map(
      (step, i) =>
        `| ${step.step} | ${NEUTRAL_STEP_LABELS[i] ?? step.label} | ${report.lanes.map((l) => l.steps[i].delta).join(' | ')} |`
    )
    .join('\n');
  const totals = `| | **Total** | ${report.lanes.map((l) => `**${l.total}**`).join(' | ')} |`;
  return `# Model declaration approaches, compared

Generated by \`packages/type-budget/test/laneComparison.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript} and drizzle-orm ${report.drizzleOrm}.

Three ways to declare the same model:

- **drizzle** a table built from the proxy column builders, model derived from it
- **type-only** the row written as a plain TypeScript type
- **builder** the row built with the RT.\* / TF.\* value-first builders

Steps 3 to 6 are the same code in every lane: the same refinement, the same
Select/Insert/Update models, the same mion route api, the same client. Only steps
1 and 2 differ, so the gap between the totals is the price of how the model was
declared and nothing else.

## Net instantiations per step

${head}
${rule}
${rows}
${totals}

## Reading this

These numbers price the three approaches, they do not rank them. The drizzle lane
derives the model from the table, so the database schema and the API types cannot
drift apart. The other two hand you that consistency to keep by hand: the
type-only row has to be edited whenever a column changes, and the builder row is
one authored definition the runtime also uses. What the table shows is the cost of
that guarantee, paid by every consumer's editor on every keystroke.

Steps 5 and 6 are the control. Their code is identical in all three lanes, so
their costs should stay close, and step 5 does: within a few percent. Step 6
spreads wider, around 21%, because the three lanes hand the client structurally
equivalent but differently spelled types (the builder lane's readonly params, the
drizzle lane's aliases). The suite asserts the control holds within 30%, which
catches drift without pinning today's gap.

Step 1 in the type-only lane costs nothing at all: a plain object type with no
generics instantiates nothing. That zero is the floor the other two are measured
against.
`;
}

/** Write reports/lane-comparison.{json,md}. **/
export function writeComparisonReport(report: ComparisonReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}lane-comparison.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}lane-comparison.md`, comparisonMarkdown(report));
}
