// Writes the measured numbers to committed artifacts: a JSON file for tooling
// and a Markdown table for humans.
//
// Both are COMMITTED on purpose. The budgets are hand-maintained, so a report
// that moves without a budget moving is the signal that something changed the
// cost, and it shows up in the pull request diff where a reviewer will see it.
// Nothing time-varying goes in (no timestamps, no durations): the counts are
// deterministic under the exact-pinned `typescript` and `drizzle-orm`, so any
// diff at all means a real change.

import {writeFileSync, mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const REPORT_DIR = fileURLToPath(new URL('../reports/', import.meta.url));

export interface StepReport {
  step: number;
  label: string;
  /** Net instantiations this step added over the previous one. **/
  delta: number;
  budget: number;
  /** Net instantiations of the whole snippet up to and including this step. **/
  cumulative: number;
}

export interface ConsumerReport {
  budget: number;
  netInstantiations: number;
  keepsGenericAlias: boolean;
  dtsBytes: number;
}

export interface PipelineReport {
  typescript: string;
  drizzleOrm: string;
  steps: StepReport[];
  consumer: ConsumerReport;
}

function markdown(report: PipelineReport): string {
  const rows = report.steps.map((s) => `| ${s.step} | ${s.label} | ${s.delta} | ${s.budget} | ${s.cumulative} |`).join('\n');
  const total = report.steps.reduce((sum, s) => sum + s.delta, 0);
  return `# Model pipeline type-instantiation report

Generated by \`packages/type-budget/test/modelPipeline.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript} and drizzle-orm ${report.drizzleOrm}.

## Per-step cost, compiled from source

Each step adds one layer to the previous snippet. The delta is what that layer
costs the type checker; the cumulative total is mostly drizzle's own types and
carries no signal on its own. Budgets may only ever be lowered.

| Step | Layer | Net instantiations added | Budget | Cumulative |
| ---: | ----- | -----------------------: | -----: | ---------: |
${rows}

Total for the whole chain: **${total}**.

Every one of these is paid again on every keystroke. TypeScript memoises type
instantiations within a single check, but each edit builds a new checker, so the
work is redone. Parsing is reused across edits; type instantiation is not.

## Downstream consumer cost, read from the emitted \`.d.ts\`

| What | Value |
| ---- | ----: |
| Consumer net instantiations | ${report.consumer.netInstantiations} |
| Budget | ${report.consumer.budget} |
| Emitted declaration size (bytes) | ${report.consumer.dtsBytes} |
| Declaration keeps the generic alias unresolved | ${report.consumer.keepsGenericAlias ? 'yes' : 'no'} |

Declaration emit prints the type alias as it was written, never the type it
evaluates to, so \`export type User = InferSelect<typeof api>\` crosses the package
boundary unresolved. None of the producer's work is banked: every consumer runs
the refine surgery again in their own checker.
`;
}

/** Write reports/model-pipeline.{json,md}. **/
export function writeReport(report: PipelineReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}model-pipeline.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}model-pipeline.md`, markdown(report));
}
