// Code generated by cmd/gen-fn-hashes. DO NOT EDIT.
// Source: internal/cachegen/operations (the registry + fnhash.go salt).
// Regenerate via `pnpm miondevx core codegen fnhashes` after changing an operation, a
// validate option, a JSON strategy, or the fnHash salt.
//
// Every fnHash here is VERSION-INDEPENDENT (operations.fnHashSalt no longer
// folds constants.Version), so the same table ships for every mion
// release: a consumer resolves `fnKey (+ options) → fnHash` once and never
// re-pins on a version bump. The runtime cache key is `<fnHash>_<typeId>`;
// its typeId half (injected by the plugin) still carries the version.

export type FnHashAxis = 'none' | 'validateOptions' | 'jsonStrategy';

export interface FnHashEntry {
  readonly axis: FnHashAxis;
  /** jsonStrategy only: the strategy token applied when options omit `strategy`. */
  readonly defaultVariant?: string;
  /** CircularGuarded families (validate / validationErrors / toBinary /
   *  jsonEncoder) fork on the rejectCircularRefs compile option: each base
   *  variant token also has a 'C'-suffixed armed twin. getFnHash appends 'C'
   *  when options.rejectCircularRefs is set on such a family. */
  readonly circularGuarded?: true;
  /** Variant token → fnHash. Token is '' for option-less families, the validate
   *  variant suffix ('', 'NT', 'NM'), or the JSON strategy name — each
   *  optionally with a trailing 'C' for the rejectCircularRefs fork on a
   *  CircularGuarded family. */
  readonly variants: Readonly<Record<string, string>>;
}

export const FN_HASHES = {
  classSerializerReg: {axis: 'none', variants: {'': 'fGyS'}},
  compactForJson: {axis: 'none', variants: {'': 'rpEK'}},
  compactFromJson: {axis: 'none', variants: {'': 'FFsn'}},
  formatTransform: {axis: 'none', variants: {'': 'mzca'}},
  fromBinary: {axis: 'none', variants: {'': 'rR8x'}},
  jsonDecoder: {axis: 'jsonStrategy', defaultVariant: 'clone', variants: {clone: 'xXCs', compact: 'hoBv', mutate: 'TqQA'}},
  jsonEncoder: {
    axis: 'jsonStrategy',
    defaultVariant: 'clone',
    circularGuarded: true,
    variants: {clone: 'tx9T', cloneC: 'ZLjB', compact: 'FL2w', compactC: 'D9wa', mutate: 'l3Wy', mutateC: 'E23P'},
  },
  jsonSchema: {axis: 'none', variants: {'': 'VwiH'}},
  prepareForJsonClone: {axis: 'none', variants: {'': 'A0Qb'}},
  prepareForJsonMutate: {axis: 'none', variants: {'': 'AwYs'}},
  removeUnknownKeys: {axis: 'none', variants: {'': 'C85b'}},
  restoreFromJsonClone: {axis: 'none', variants: {'': 'Ky89'}},
  restoreFromJsonMutate: {axis: 'none', variants: {'': 'w8ie'}},
  toBinary: {axis: 'none', circularGuarded: true, variants: {'': 'jDpZ', C: 'rutq'}},
  validate: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {'': 'Eq2V', C: 'VpZY', NM: 'PHIy', NMC: 'STwe', NT: 'WOvb', NTC: 'Tq25'},
  },
  validateStrict: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {'': 'fZHy', C: 'ljLE', NM: 'EwD7', NMC: 'dobr', NT: 'gAsC', NTC: 'Oz5j'},
  },
  validateUnionKeys: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {'': 'Xhuv', C: 'H97o', NM: 'NX1L', NMC: 'qzkT', NT: 'BhE9', NTC: 'q7RI'},
  },
  validationErrors: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {'': 'swxg', C: 'UYW2', NM: 'zncs', NMC: 'VTY9', NT: 'aZak', NTC: 'hjJf'},
  },
  validationErrorsStrict: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {'': 'OB5g', C: 'c6EY', NM: 'TGyU', NMC: 'k7iN', NT: 'ikAJ', NTC: 'ypxr'},
  },
  validationErrorsUnionKeys: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {'': 'OBOg', C: 'O8IR', NM: 'zAg4', NMC: 'Yu6R', NT: 'X6fx', NTC: 'bEtz'},
  },
} as const satisfies Record<string, FnHashEntry>;

/** Emitted family tag → the fn key that names it in a marker. The two are
 *  SEPARATE vocabularies: a compiled entry carries the short tag ('pjs') at
 *  slot 0 of its tuple, while a marker names the readable key
 *  ('prepareForJsonClone'). A framework that projects an injected payload by
 *  the tag it finds needs this to speak one vocabulary again. Composite JSON
 *  families emit per-strategy tags and are not listed. */
export const FAMILY_TAG_TO_FN_KEY = {
  cj: 'compactForJson',
  cjr: 'compactFromJson',
  csr: 'classSerializerReg',
  fb: 'fromBinary',
  fmt: 'formatTransform',
  jsc: 'jsonSchema',
  pj: 'prepareForJsonMutate',
  pjs: 'prepareForJsonClone',
  rj: 'restoreFromJsonMutate',
  rjs: 'restoreFromJsonClone',
  ruk: 'removeUnknownKeys',
  tb: 'toBinary',
  val: 'validate',
  verr: 'validationErrors',
  vest: 'validationErrorsStrict',
  veuk: 'validationErrorsUnionKeys',
  vst: 'validateStrict',
  vuk: 'validateUnionKeys',
} as const satisfies Readonly<Record<string, string>>;

/** ValidateOptions name → single-letter token, in Go declaration order
 *  (constants.ValidateOptions). The validate variant suffix is 'N' followed by
 *  the letters of the present options concatenated in THIS order. */
export const VALIDATE_OPTION_LETTERS = [
  ['numberTypeof', 'T'],
  ['numberNotNaN', 'M'],
] as const satisfies ReadonlyArray<readonly [string, string]>;
