// Code generated by cmd/gen-fn-hashes. DO NOT EDIT.
// Source: internal/cachegen/operations (the registry + fnhash.go salt).
// Regenerate via `pnpm miondevx core codegen fnhashes` after changing an operation, a
// validate option, a JSON strategy, or the fnHash salt.
//
// Every fnHash here is VERSION-INDEPENDENT (operations.fnHashSalt no longer
// folds constants.Version), so the same table ships for every mion
// release: a consumer resolves `fnKey (+ options) → fnHash` once and never
// re-pins on a version bump. The runtime cache key is `<fnHash>_<typeId>`;
// its typeId half (injected by the plugin) still carries the version.

export type FnHashAxis = 'none' | 'validateOptions' | 'jsonStrategy' | 'hasUnknownKeysOptions';

export interface FnHashEntry {
  readonly axis: FnHashAxis;
  /** jsonStrategy only: the strategy token applied when options omit `strategy`. */
  readonly defaultVariant?: string;
  /** CircularGuarded families (validate / validationErrors / toBinary /
   *  jsonEncoder) fork on the rejectCircularRefs compile option: each base
   *  variant token also has a 'C'-suffixed armed twin. getFnHash appends 'C'
   *  when options.rejectCircularRefs is set on such a family. */
  readonly circularGuarded?: true;
  /** Variant token → fnHash. Token is '' for option-less families, the validate
   *  variant suffix ('', 'NL', 'NA', 'NLA'), the hasUnknownKeys variant suffix
   *  ('', 'OV'), or the JSON strategy name — each optionally with a trailing
   *  'C' for the rejectCircularRefs fork on a CircularGuarded family. */
  readonly variants: Readonly<Record<string, string>>;
}

export const FN_HASHES = {
  classSerializerReg: {axis: 'none', variants: {'': 'fGyS'}},
  compactForJson: {axis: 'none', variants: {'': 'rpEK'}},
  compactFromJson: {axis: 'none', variants: {'': 'FFsn'}},
  formatTransform: {axis: 'none', variants: {'': 'mzca'}},
  fromBinary: {axis: 'none', variants: {'': 'rR8x'}},
  hasUnknownKeys: {axis: 'hasUnknownKeysOptions', variants: {'': 'GsPX', OV: 'be7V'}},
  jsonDecoder: {axis: 'jsonStrategy', defaultVariant: 'strip', variants: {compact: 'hoBv', preserve: 'kpI8', strip: 'Ajic'}},
  jsonEncoder: {
    axis: 'jsonStrategy',
    defaultVariant: 'clone',
    circularGuarded: true,
    variants: {
      clone: 'tx9T',
      cloneC: 'ZLjB',
      compact: 'FL2w',
      compactC: 'D9wa',
      direct: 'Bm08',
      directC: 'T2Cf',
      mutate: 'l3Wy',
      mutateC: 'E23P',
    },
  },
  jsonSchema: {axis: 'none', variants: {'': 'VwiH'}},
  prepareForJsonClone: {axis: 'none', variants: {'': 'A0Qb'}},
  prepareForJsonMutate: {axis: 'none', variants: {'': 'AwYs'}},
  removeUnknownKeys: {axis: 'none', variants: {'': 'C85b'}},
  restoreFromJsonClone: {axis: 'none', variants: {'': 'Ky89'}},
  restoreFromJsonMutate: {axis: 'none', variants: {'': 'w8ie'}},
  stringifyJson: {axis: 'none', variants: {'': 'i4VX'}},
  stripUnknownKeysWire: {axis: 'none', variants: {'': 'q9zA'}},
  toBinary: {axis: 'none', circularGuarded: true, variants: {'': 'jDpZ', C: 'rutq'}},
  unknownKeyErrors: {axis: 'none', variants: {'': 'r8yS'}},
  validate: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'Eq2V',
      C: 'VpZY',
      NA: 'KAWX',
      NAC: 'Xc5w',
      NAM: 'nfMT',
      NAMC: 'MO5D',
      NAT: 'e5Fe',
      NATC: 'HY11',
      NATM: 'ID0X',
      NATMC: 'Pkva',
      NL: 'swyy',
      NLA: 'o2vR',
      NLAC: 'FVSj',
      NLAM: 'gMqy',
      NLAMC: 'L6Rd',
      NLAT: 'k8r5',
      NLATC: 'dl7o',
      NLATM: 'kFqE',
      NLATMC: 'hjLv',
      NLC: 'x9HZ',
      NLM: 'iAIK',
      NLMC: 'IyKa',
      NLT: 't5vX',
      NLTC: 'Ofx4',
      NLTM: 'BlpN',
      NLTMC: 'GBmc',
      NM: 'PHIy',
      NMC: 'STwe',
      NT: 'WOvb',
      NTC: 'Tq25',
      NTM: 'RGJe',
      NTMC: 'hkri',
    },
  },
  validateStrict: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'fZHy',
      C: 'ljLE',
      NA: 'SglO',
      NAC: 'xtpt',
      NAM: 'p5Z3',
      NAMC: 'grXU',
      NAT: 'E6UO',
      NATC: 'vsuq',
      NATM: 'haF2',
      NATMC: 'CQrr',
      NL: 'o6rR',
      NLA: 'irCy',
      NLAC: 'Ax3E',
      NLAM: 'hVqF',
      NLAMC: 'thab',
      NLAT: 'Dl6Z',
      NLATC: 'g8QS',
      NLATM: 'X1Gj',
      NLATMC: 'u42M',
      NLC: 'mkgu',
      NLM: 'eNDk',
      NLMC: 'p8ii',
      NLT: 'i4AB',
      NLTC: 'Xmc6',
      NLTM: 'LjeC',
      NLTMC: 'PG4q',
      NM: 'EwD7',
      NMC: 'dobr',
      NT: 'gAsC',
      NTC: 'Oz5j',
      NTM: 'mZAg',
      NTMC: 'XmFX',
    },
  },
  validateUnionKeys: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'Xhuv',
      C: 'H97o',
      NA: 'aBtc',
      NAC: 'Hndm',
      NAM: 'JXJX',
      NAMC: 'DOLR',
      NAT: 'qJyR',
      NATC: 'kVBL',
      NATM: 'PrUG',
      NATMC: 'iQs1',
      NL: 'ILWJ',
      NLA: 'ZjcP',
      NLAC: 'Dk7K',
      NLAM: 'oftf',
      NLAMC: 'V9fd',
      NLAT: 'Ppbw',
      NLATC: 'Rint',
      NLATM: 'LL2Y',
      NLATMC: 'DrFt',
      NLC: 'LSsS',
      NLM: 'yyeU',
      NLMC: 'y3QG',
      NLT: 'wjdN',
      NLTC: 'JwaF',
      NLTM: 'Mday',
      NLTMC: 'FRK1',
      NM: 'NX1L',
      NMC: 'qzkT',
      NT: 'BhE9',
      NTC: 'q7RI',
      NTM: 'sYB4',
      NTMC: 'HRMq',
    },
  },
  validationErrors: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'swxg',
      C: 'UYW2',
      NA: 'G6qO',
      NAC: 'Fyll',
      NAM: 'Qknw',
      NAMC: 'ftgY',
      NAT: 'utBM',
      NATC: 'jSXW',
      NATM: 'JAgE',
      NATMC: 'Gn4P',
      NL: 'lVZr',
      NLA: 'xJVW',
      NLAC: 'LaRP',
      NLAM: 'PKpr',
      NLAMC: 'gexJ',
      NLAT: 'Z0Zn',
      NLATC: 'K7Kd',
      NLATM: 'Tnom',
      NLATMC: 'fBHs',
      NLC: 'gpvz',
      NLM: 'Xz6d',
      NLMC: 'k2ab',
      NLT: 'IjkG',
      NLTC: 'SQYh',
      NLTM: 'swtb',
      NLTMC: 'dHms',
      NM: 'zncs',
      NMC: 'VTY9',
      NT: 'aZak',
      NTC: 'hjJf',
      NTM: 'CjhC',
      NTMC: 'OQYw',
    },
  },
  validationErrorsStrict: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'OB5g',
      C: 'c6EY',
      NA: 'oz9A',
      NAC: 'OGmx',
      NAM: 'o8FB',
      NAMC: 'kv0b',
      NAT: 'qmFM',
      NATC: 'Wk3z',
      NATM: 't6CR',
      NATMC: 'aVEH',
      NL: 'qSSd',
      NLA: 'TlGQ',
      NLAC: 'JuVI',
      NLAM: 'GYm3',
      NLAMC: 'JW3k',
      NLAT: 'dRpw',
      NLATC: 'ahI0',
      NLATM: 'J5cN',
      NLATMC: 'hLFT',
      NLC: 'tfdn',
      NLM: 'w5zu',
      NLMC: 'xzIK',
      NLT: 'wR6n',
      NLTC: 'rNwk',
      NLTM: 'PN76',
      NLTMC: 'vmTA',
      NM: 'TGyU',
      NMC: 'k7iN',
      NT: 'ikAJ',
      NTC: 'ypxr',
      NTM: 'HPXM',
      NTMC: 'HiHT',
    },
  },
  validationErrorsUnionKeys: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'OBOg',
      C: 'O8IR',
      NA: 'Ivkt',
      NAC: 'htE6',
      NAM: 'VCON',
      NAMC: 'mk8P',
      NAT: 'KmFt',
      NATC: 'mvl0',
      NATM: 'uUII',
      NATMC: 'v45v',
      NL: 'Ev0c',
      NLA: 'C8mV',
      NLAC: 'T4TL',
      NLAM: 'FkG8',
      NLAMC: 'Q58R',
      NLAT: 'n9GW',
      NLATC: 'oh7Z',
      NLATM: 'ruXR',
      NLATMC: 'mgTL',
      NLC: 'rAFz',
      NLM: 'LQY8',
      NLMC: 'QyHd',
      NLT: 'vtS4',
      NLTC: 'HhTU',
      NLTM: 'IV1f',
      NLTMC: 'hpyS',
      NM: 'zAg4',
      NMC: 'Yu6R',
      NT: 'X6fx',
      NTC: 'bEtz',
      NTM: 'Eepd',
      NTMC: 'YPIX',
    },
  },
} as const satisfies Record<string, FnHashEntry>;

/** Emitted family tag → the fn key that names it in a marker. The two are
 *  SEPARATE vocabularies: a compiled entry carries the short tag ('pjs') at
 *  slot 0 of its tuple, while a marker names the readable key
 *  ('prepareForJsonClone'). A framework that projects an injected payload by
 *  the tag it finds needs this to speak one vocabulary again. Composite JSON
 *  families emit per-strategy tags and are not listed. */
export const FAMILY_TAG_TO_FN_KEY = {
  cj: 'compactForJson',
  cjr: 'compactFromJson',
  csr: 'classSerializerReg',
  fb: 'fromBinary',
  fmt: 'formatTransform',
  huk: 'hasUnknownKeys',
  jsc: 'jsonSchema',
  pj: 'prepareForJsonMutate',
  pjs: 'prepareForJsonClone',
  rj: 'restoreFromJsonMutate',
  rjs: 'restoreFromJsonClone',
  ruk: 'removeUnknownKeys',
  sj: 'stringifyJson',
  tb: 'toBinary',
  uke: 'unknownKeyErrors',
  ukuw: 'stripUnknownKeysWire',
  val: 'validate',
  verr: 'validationErrors',
  vest: 'validationErrorsStrict',
  veuk: 'validationErrorsUnionKeys',
  vst: 'validateStrict',
  vuk: 'validateUnionKeys',
} as const satisfies Readonly<Record<string, string>>;

/** ValidateOptions name → single-letter token, in Go declaration order
 *  (constants.ValidateOptions). The validate variant suffix is 'N' followed by
 *  the letters of the present options concatenated in THIS order. */
export const VALIDATE_OPTION_LETTERS = [
  ['noLiterals', 'L'],
  ['noIsArrayCheck', 'A'],
  ['numberTypeof', 'T'],
  ['numberNotNaN', 'M'],
] as const satisfies ReadonlyArray<readonly [string, string]>;

/** HasUnknownKeysOptions name → single-letter token, in Go declaration order
 *  (constants.HasUnknownKeysOptions). The hasUnknownKeys variant suffix is 'O'
 *  followed by the letters of the present options concatenated in THIS order. */
export const HAS_UNKNOWN_KEYS_OPTION_LETTERS = [['runsAfterValidation', 'V']] as const satisfies ReadonlyArray<
  readonly [string, string]
>;
