// Code generated by cmd/gen-fn-hashes. DO NOT EDIT.
// Source: internal/cachegen/operations (the registry + fnhash.go salt).
// Regenerate via `pnpm rtx core codegen fnhashes` after changing an operation, a
// validate option, a JSON strategy, or the fnHash salt.
//
// Every fnHash here is VERSION-INDEPENDENT (operations.fnHashSalt no longer
// folds constants.Version), so the same table ships for every mion
// release: a consumer resolves `fnKey (+ options) → fnHash` once and never
// re-pins on a version bump. The runtime cache key is `<fnHash>_<typeId>`;
// its typeId half (injected by the plugin) still carries the version.

export type FnHashAxis = 'none' | 'validateOptions' | 'jsonStrategy' | 'hasUnknownKeysOptions';

export interface FnHashEntry {
  readonly axis: FnHashAxis;
  /** jsonStrategy only: the strategy token applied when options omit `strategy`. */
  readonly defaultVariant?: string;
  /** CircularGuarded families (validate / validationErrors / toBinary /
   *  jsonEncoder) fork on the rejectCircularRefs compile option: each base
   *  variant token also has a 'C'-suffixed armed twin. getFnHash appends 'C'
   *  when options.rejectCircularRefs is set on such a family. */
  readonly circularGuarded?: true;
  /** Variant token → fnHash. Token is '' for option-less families, the validate
   *  variant suffix ('', 'NL', 'NA', 'NLA'), the hasUnknownKeys variant suffix
   *  ('', 'OV'), or the JSON strategy name — each optionally with a trailing
   *  'C' for the rejectCircularRefs fork on a CircularGuarded family. */
  readonly variants: Readonly<Record<string, string>>;
}

export const FN_HASHES = {
  ces: {axis: 'none', variants: {'': 'wsq8'}},
  cj: {axis: 'none', variants: {'': 'xnNV'}},
  cjr: {axis: 'none', variants: {'': 'Siwe'}},
  csr: {axis: 'none', variants: {'': 'ndTV'}},
  fb: {axis: 'none', variants: {'': 'mY6e'}},
  fmt: {axis: 'none', variants: {'': 'SS6W'}},
  huk: {axis: 'hasUnknownKeysOptions', variants: {'': 'lRNH', OV: 'Omgu'}},
  jsonDecoder: {axis: 'jsonStrategy', defaultVariant: 'strip', variants: {compact: 'MCym', preserve: 'J5lV', strip: 'fDVl'}},
  jsonEncoder: {
    axis: 'jsonStrategy',
    defaultVariant: 'clone',
    circularGuarded: true,
    variants: {
      clone: 'wUiG',
      cloneC: 't3D3',
      compact: 'yeSa',
      compactC: 'LxJ3',
      direct: 'y0um',
      directC: 'DJJx',
      mutate: 'z1Lh',
      mutateC: 'MEwk',
    },
  },
  jsonSchema: {axis: 'none', variants: {'': 'UMiU'}},
  pj: {axis: 'none', variants: {'': 'tt1B'}},
  pjs: {axis: 'none', variants: {'': 'oakY'}},
  prs: {axis: 'none', variants: {'': 'Q4UG'}},
  prsf: {axis: 'none', variants: {'': 'Ygou'}},
  prss: {axis: 'none', variants: {'': 'qgwk'}},
  rj: {axis: 'none', variants: {'': 'X13R'}},
  sj: {axis: 'none', variants: {'': 'qm4w'}},
  tb: {axis: 'none', circularGuarded: true, variants: {'': 'plZf', C: 'GC80'}},
  uke: {axis: 'none', variants: {'': 'XFJv'}},
  ukuw: {axis: 'none', variants: {'': 'N3xd'}},
  val: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'nPZf',
      C: 'cCee',
      NA: 'WeUm',
      NAC: 'fJb3',
      NAM: 'D77v',
      NAMC: 'ASI4',
      NAT: 'CG0k',
      NATC: 'jH9V',
      NATM: 'zd5t',
      NATMC: 'UQEg',
      NL: 'N7JN',
      NLA: 'GYKM',
      NLAC: 'z9td',
      NLAM: 'rXxN',
      NLAMC: 'oaWw',
      NLAT: 'qwqC',
      NLATC: 'XZnn',
      NLATM: 'TDnH',
      NLATMC: 'w46s',
      NLC: 'iaiM',
      NLM: 'iWyC',
      NLMC: 'HZvX',
      NLT: 'hvrr',
      NLTC: 'qOWO',
      NLTM: 'CEcg',
      NLTMC: 'TDxL',
      NM: 'ycIc',
      NMC: 'nzdJ',
      NT: 'xLB1',
      NTC: 'WoEA',
      NTM: 'OOMY',
      NTMC: 'fljj',
    },
  },
  verr: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'pBbL',
      C: 'a8Ay',
      NA: 'UKgG',
      NAC: 'F3LV',
      NAM: 'Vtr5',
      NAMC: 'OsEK',
      NAT: 'U2kU',
      NATC: 'xh1B',
      NATM: 'ZxFl',
      NATMC: 'eIgu',
      NL: 'LD57',
      NLA: 'Yk4m',
      NLAC: 'NJlT',
      NLAM: 'Rh7F',
      NLAMC: 'y2CK',
      NLAT: 'QQ0u',
      NLATC: 'hRZB',
      NLATM: 'hdfn',
      NLATMC: 'eGgG',
      NLC: 'IuSE',
      NLM: 'AiSc',
      NLMC: 'VznD',
      NLT: 'zRL1',
      NLTC: 'EoOq',
      NLTM: 'cYM8',
      NLTMC: 'dv9Z',
      NM: 'wI4w',
      NMC: 'NTNF',
      NT: 'vhXl',
      NTC: 'wIes',
      NTM: 'ga6y',
      NTMC: 'tVbZ',
    },
  },
  vest: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'qYmk',
      C: 'DHBd',
      NA: 'xjhl',
      NAC: 'qIeU',
      NAM: 'Cu6y',
      NAMC: 'HVDF',
      NAT: 'B3Zn',
      NATC: 'qK4w',
      NATM: 'Kc8o',
      NATMC: 'fLfp',
      NL: 'oc6M',
      NLA: 'FlJP',
      NLAC: 'GckO',
      NLAM: 'CWAE',
      NLAMC: 'z1xF',
      NLAT: 'Bvtt',
      NLATC: 'iQYw',
      NLATM: 'aGei',
      NLATMC: 'jFfV',
      NLC: 't9lD',
      NLM: 'hjxF',
      NLMC: 'O2my',
      NLT: 'gSqu',
      NLTC: 'xRNp',
      NLTM: 'NDf7',
      NLTMC: 'eu8U',
      NM: 'Zh5b',
      NMC: 'yygE',
      NT: 'YQY0',
      NTC: 'hnHv',
      NTM: 'NbL1',
      NTMC: 'moaU',
    },
  },
  vst: {
    axis: 'validateOptions',
    circularGuarded: true,
    variants: {
      '': 'g6G6',
      C: 'Vtr1',
      NA: 'P579',
      NAC: 'YwyG',
      NAM: 'skUS',
      NAMC: 'pfpV',
      NAT: 'rTNH',
      NATC: 'Y4MM',
      NATM: 's0s6',
      NATMC: 'Vtvl',
      NL: 'GYWA',
      NLA: 'vbx9',
      NLAC: 'ow64',
      NLAM: 'kKUq',
      NLAMC: 'pNNB',
      NLAT: 'jjNf',
      NLATC: 'YCes',
      NLATM: 'I00y',
      NLATMC: 'xVbd',
      NLC: 'bXFp',
      NLM: 'X9lZ',
      NLMC: 'wm8O',
      NLT: 'WIeO',
      NLTC: 'fbzF',
      NLTM: 'vrzT',
      NLTMC: 'UgoQ',
      NM: 'r3VZ',
      NMC: 'gmAq',
      NT: 'qCOO',
      NTC: 'PbXd',
      NTM: 'D1zh',
      NTMC: 'UEWa',
    },
  },
} as const satisfies Record<string, FnHashEntry>;

/** ValidateOptions name → single-letter token, in Go declaration order
 *  (constants.ValidateOptions). The validate variant suffix is 'N' followed by
 *  the letters of the present options concatenated in THIS order. */
export const VALIDATE_OPTION_LETTERS = [
  ['noLiterals', 'L'],
  ['noIsArrayCheck', 'A'],
  ['numberTypeof', 'T'],
  ['numberNotNaN', 'M'],
] as const satisfies ReadonlyArray<readonly [string, string]>;

/** HasUnknownKeysOptions name → single-letter token, in Go declaration order
 *  (constants.HasUnknownKeysOptions). The hasUnknownKeys variant suffix is 'O'
 *  followed by the letters of the present options concatenated in THIS order. */
export const HAS_UNKNOWN_KEYS_OPTION_LETTERS = [['runsAfterValidation', 'V']] as const satisfies ReadonlyArray<
  readonly [string, string]
>;
