// AUTO-GENERATED by cmd/gen-format-error-keys. DO NOT EDIT.
// Regenerate: pnpm miondevx core codegen errorkeys. CI fails on drift (`--check`).
// Keys come from each format's own validation-errors code, run over the samples in
// ts-go-runtypes/internal/cachegen/typefunctions/formats/errorkeys_samples.go.

// Every `rt$errors` key a format's validation errors can carry, per format name.
export type FormatErrorKeys = {
  bigintFormat: 'gt' | 'lt' | 'max' | 'min' | 'multipleOf';
  creditCard: 'creditCard' | 'networks';
  date: 'format' | 'gt' | 'lt' | 'max' | 'min';
  dateTime: 'date' | 'gt' | 'lt' | 'max' | 'min' | 'splitChar' | 'time';
  domain: 'allowedValues' | 'hyphen' | 'idna' | 'maxLength' | 'maxParts' | 'minLength' | 'minParts' | 'pattern';
  email: '@' | 'emailRfc' | 'hyphen' | 'maxLength' | 'maxParts' | 'minLength' | 'minParts' | 'pattern';
  formattedArray: 'maxItems' | 'minItems' | 'uniqueItems';
  formattedMap: 'maxItems' | 'minItems' | 'uniqueItems';
  formattedObject: 'closed' | 'maxProperties' | 'minProperties';
  formattedSet: 'maxItems' | 'minItems' | 'uniqueItems';
  ip: 'version';
  nativeDate: 'gt' | 'lt' | 'max' | 'min';
  numberFormat: 'gt' | 'integer' | 'lt' | 'max' | 'min' | 'multipleOf';
  stringFormat:
    | 'allowedChars'
    | 'allowedValues'
    | 'contentMediaType'
    | 'disallowedChars'
    | 'disallowedValues'
    | 'isRegex'
    | 'length'
    | 'maxLength'
    | 'minLength'
    | 'pattern';
  temporalInstant: 'gt' | 'lt' | 'max' | 'min';
  temporalPlainDate: 'gt' | 'lt' | 'max' | 'min';
  temporalPlainDateTime: 'gt' | 'lt' | 'max' | 'min';
  temporalPlainTime: 'gt' | 'lt' | 'max' | 'min';
  temporalPlainYearMonth: 'gt' | 'lt' | 'max' | 'min';
  temporalZonedDateTime: 'gt' | 'lt' | 'max' | 'min';
  time: 'format' | 'gt' | 'lt' | 'max' | 'min';
  url: 'maxLength' | 'minLength' | 'pattern';
  uuid: 'version';
};

// The same keys as data.
export const FORMAT_ERROR_KEYS = {
  bigintFormat: ['gt', 'lt', 'max', 'min', 'multipleOf'],
  creditCard: ['creditCard', 'networks'],
  date: ['format', 'gt', 'lt', 'max', 'min'],
  dateTime: ['date', 'gt', 'lt', 'max', 'min', 'splitChar', 'time'],
  domain: ['allowedValues', 'hyphen', 'idna', 'maxLength', 'maxParts', 'minLength', 'minParts', 'pattern'],
  email: ['@', 'emailRfc', 'hyphen', 'maxLength', 'maxParts', 'minLength', 'minParts', 'pattern'],
  formattedArray: ['maxItems', 'minItems', 'uniqueItems'],
  formattedMap: ['maxItems', 'minItems', 'uniqueItems'],
  formattedObject: ['closed', 'maxProperties', 'minProperties'],
  formattedSet: ['maxItems', 'minItems', 'uniqueItems'],
  ip: ['version'],
  nativeDate: ['gt', 'lt', 'max', 'min'],
  numberFormat: ['gt', 'integer', 'lt', 'max', 'min', 'multipleOf'],
  stringFormat: [
    'allowedChars',
    'allowedValues',
    'contentMediaType',
    'disallowedChars',
    'disallowedValues',
    'isRegex',
    'length',
    'maxLength',
    'minLength',
    'pattern',
  ],
  temporalInstant: ['gt', 'lt', 'max', 'min'],
  temporalPlainDate: ['gt', 'lt', 'max', 'min'],
  temporalPlainDateTime: ['gt', 'lt', 'max', 'min'],
  temporalPlainTime: ['gt', 'lt', 'max', 'min'],
  temporalPlainYearMonth: ['gt', 'lt', 'max', 'min'],
  temporalZonedDateTime: ['gt', 'lt', 'max', 'min'],
  time: ['format', 'gt', 'lt', 'max', 'min'],
  url: ['maxLength', 'minLength', 'pattern'],
  uuid: ['version'],
} as const;

// The params each format's samples set or exclude on purpose; a param outside it fails a type test.
export type FormatSampledParams = {
  bigintFormat: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum' | 'multipleOf';
  creditCard: 'networks' | 'separators' | 'transform';
  date: 'exclusiveMaximum' | 'exclusiveMinimum' | 'format' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  dateTime:
    | 'date'
    | 'exclusiveMaximum'
    | 'exclusiveMinimum'
    | 'gt'
    | 'lt'
    | 'max'
    | 'maximum'
    | 'min'
    | 'minimum'
    | 'splitChar'
    | 'time';
  domain:
    | 'allowedValues'
    | 'idna'
    | 'maxLength'
    | 'maxParts'
    | 'minLength'
    | 'minParts'
    | 'mockSamples'
    | 'names'
    | 'pattern'
    | 'tld'
    | 'transform';
  email: 'domain' | 'emailRfc' | 'localPart' | 'maxLength' | 'minLength' | 'mockSamples' | 'pattern' | 'transform';
  formattedArray: 'contains' | 'maxContains' | 'maxItems' | 'minContains' | 'minItems' | 'uniqueItems';
  formattedMap: 'contains' | 'maxContains' | 'maxItems' | 'minContains' | 'minItems' | 'uniqueItems';
  formattedObject:
    | 'additionalOwn'
    | 'closed'
    | 'closedPatterns'
    | 'maxProperties'
    | 'minProperties'
    | 'patternProperties'
    | 'propertyNames';
  formattedSet: 'contains' | 'maxContains' | 'maxItems' | 'minContains' | 'minItems' | 'uniqueItems';
  ip: 'allowLocalHost' | 'allowPort' | 'transform' | 'version';
  nativeDate: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  numberFormat:
    | 'exclusiveMaximum'
    | 'exclusiveMinimum'
    | 'float'
    | 'gt'
    | 'integer'
    | 'isCurrency'
    | 'lt'
    | 'max'
    | 'maximum'
    | 'min'
    | 'minimum'
    | 'multipleOf'
    | 'multipleOfTolerance';
  stringFormat:
    | 'allowedChars'
    | 'allowedValues'
    | 'contentEncoding'
    | 'contentMediaType'
    | 'disallowedChars'
    | 'disallowedValues'
    | 'isRegex'
    | 'length'
    | 'maxLength'
    | 'minLength'
    | 'mockSamples'
    | 'pattern'
    | 'transform';
  temporalInstant: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  temporalPlainDate: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  temporalPlainDateTime: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  temporalPlainTime: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  temporalPlainYearMonth: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  temporalZonedDateTime: 'exclusiveMaximum' | 'exclusiveMinimum' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  time: 'exclusiveMaximum' | 'exclusiveMinimum' | 'format' | 'gt' | 'lt' | 'max' | 'maximum' | 'min' | 'minimum';
  url: 'maxLength' | 'minLength' | 'mockSamples' | 'pattern' | 'transform';
  uuid: 'version';
};
