// Code generated by cmd/gen-plugin-keys. DO NOT EDIT.
// Source: cmd/mion/config.go (tsRuntypesPlugin json tags).
// Regenerate via `pnpm miondevx core codegen pluginkeys` after changing the struct.
//
// The recognised keys of the tsconfig `plugins` entry. The plugin-option
// parity test (test/plugin-option-parity.test.ts) checks these against the
// bundler PluginOptions so a project option added to only one side fails CI.

export const TSCONFIG_PLUGIN_KEYS = [
  'binarySizing',
  'clientTsconfig',
  'emitMode',
  'failOnError',
  'genDir',
  'hashLength',
  'i18n',
  'inlineMode',
  'markers',
  'moduleMode',
  'name',
  'parallelRender',
  'parallelScan',
  'parse',
  'patternSampleCount',
  'patternSampleRetries',
  'pureFnReport',
  'singleThreaded',
  'validate',
] as const;

export type TsconfigPluginKey = (typeof TSCONFIG_PLUGIN_KEYS)[number];
