// ============================================================================
//                            AUTO-GENERATED FILE
//                            DO NOT EDIT MANUALLY
// ============================================================================
//
// Generated by cmd/gen-run-type-kind from:
//   - internal/reflection/runtype.go
//   - internal/reflection/subkind.go
//
// To update: change the Go source, then run:
//
//     pnpm rtx core codegen kind
//
// which regenerates this file AND the devtools-package mirror
// (packages/ts-runtypes-devtools/src/go-generated/reflectionKind.generated.ts) from the same
// protocol consts. The TestRunTypeKindFileInSync Go test and
// `pnpm rtx core codegen kind --check` (CI) both fail on any drift.
//
// Numeric discriminators that JS-side consumers use to dispatch on the
// shape of a RunType node in the runTypesCache. Values must match the
// Go binary's wire output byte-for-byte.
//
// ============================================================================

export const RunTypeKind = {
  never: 0,
  any: 1,
  unknown: 2,
  void: 3,
  object: 4,
  string: 5,
  number: 6,
  boolean: 7,
  symbol: 8,
  bigint: 9,
  null: 10,
  undefined: 11,
  regexp: 12,
  literal: 13,
  templateLiteral: 14,
  property: 15,
  method: 16,
  function: 17,
  parameter: 18,
  promise: 19,
  class: 20,
  typeParameter: 21,
  enum: 22,
  union: 23,
  intersection: 24,
  array: 25,
  tuple: 26,
  tupleMember: 27,
  enumMember: 28,
  rest: 29,
  objectLiteral: 30,
  indexSignature: 31,
  propertySignature: 32,
  methodSignature: 33,
  infer: 34,
  callSignature: 35,
  ref: -1,
} as const;

export type RunTypeKindName = keyof typeof RunTypeKind;
export type RunTypeKindValue = (typeof RunTypeKind)[RunTypeKindName];

export const RunTypeSubKind = {
  none: 0,
  mapKey: 1801,
  mapValue: 1802,
  setItem: 1803,
  date: 2001,
  map: 2002,
  set: 2003,
  nonSerializable: 2004,
  temporalInstant: 2101,
  temporalZonedDateTime: 2102,
  temporalPlainDate: 2103,
  temporalPlainTime: 2104,
  temporalPlainDateTime: 2105,
  temporalPlainYearMonth: 2106,
  temporalPlainMonthDay: 2107,
  temporalDuration: 2108,
} as const;

export type RunTypeSubKindName = keyof typeof RunTypeSubKind;
export type RunTypeSubKindValue = (typeof RunTypeSubKind)[RunTypeSubKindName];
