// ============================================================================
//                            AUTO-GENERATED FILE
//                            DO NOT EDIT MANUALLY
// ============================================================================
//
// Generated by cmd/gen-type-formats from the Go format registry
// (internal/cachegen/typefunctions/formats — each emitter's Name() + Kind()).
//
// To update: add / rename a format emitter on the Go side, then run:
//
//     pnpm rtx core codegen typeformats
//
// The TestTypeFormatsFileInSync Go test and
// `pnpm rtx core codegen typeformats --check` (CI) both fail on any drift.
//
// The canonical format names ts-runtypes stamps on a reflected prop's
// `formatAnnotation.name`, each with the base RunTypeKind it refines. A
// consumer that maps a reflected format to something external (a DB column,
// a UI label) keys off this table instead of re-declaring the names.
//
// ============================================================================

import {RunTypeKind, type RunTypeKindValue} from './runTypeKind.generated.ts';

// Metadata for one built-in type format: the canonical `name` and the base
// `RunTypeKind` the format refines.
export interface TypeFormatMeta {
  readonly name: FormatName;
  readonly kind: RunTypeKindValue;
}

// Every built-in type format, keyed by its canonical name.
export const typeFormats = {
  bigintFormat: {name: 'bigintFormat', kind: RunTypeKind.bigint},
  date: {name: 'date', kind: RunTypeKind.string},
  dateTime: {name: 'dateTime', kind: RunTypeKind.string},
  domain: {name: 'domain', kind: RunTypeKind.string},
  email: {name: 'email', kind: RunTypeKind.string},
  formattedArray: {name: 'formattedArray', kind: RunTypeKind.array},
  formattedObject: {name: 'formattedObject', kind: RunTypeKind.object},
  ip: {name: 'ip', kind: RunTypeKind.string},
  jsonContent: {name: 'jsonContent', kind: RunTypeKind.string},
  nativeDate: {name: 'nativeDate', kind: RunTypeKind.class},
  numberFormat: {name: 'numberFormat', kind: RunTypeKind.number},
  stringFormat: {name: 'stringFormat', kind: RunTypeKind.string},
  temporalInstant: {name: 'temporalInstant', kind: RunTypeKind.class},
  temporalPlainDate: {name: 'temporalPlainDate', kind: RunTypeKind.class},
  temporalPlainDateTime: {name: 'temporalPlainDateTime', kind: RunTypeKind.class},
  temporalPlainTime: {name: 'temporalPlainTime', kind: RunTypeKind.class},
  temporalPlainYearMonth: {name: 'temporalPlainYearMonth', kind: RunTypeKind.class},
  temporalZonedDateTime: {name: 'temporalZonedDateTime', kind: RunTypeKind.class},
  time: {name: 'time', kind: RunTypeKind.string},
  url: {name: 'url', kind: RunTypeKind.string},
  uuid: {name: 'uuid', kind: RunTypeKind.string},
} as const;

// The canonical format-name string stamped on a reflected prop's
// `formatAnnotation.name`, covering every built-in format.
export type FormatName = keyof typeof typeFormats;
