/* ########
 * 2025 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import type {
    PgColumnBuilderBase,
    PgTableWithColumns,
    PgTextBuilder,
    PgVarcharBuilder,
    PgUUIDBuilder,
    PgIntegerBuilder,
    PgDoublePrecisionBuilder,
    PgBooleanBuilder,
    PgBigInt53Builder,
    PgBigInt64Builder,
    PgTimestampBuilder,
    PgDateBuilder,
    PgTimeBuilder,
    PgJsonbBuilder,
    PgInetBuilder,
} from 'drizzle-orm/pg-core';
import type {BuildColumns} from 'drizzle-orm/column-builder';

// ============================================================================
// Column Type Mapping
// ============================================================================

/**
 * Maps a TypeScript primitive type to its corresponding PostgreSQL column builder type.
 * This is used to constrain what column builders can be used for each property type.
 *
 * - string → PgTextBuilder | PgVarcharBuilder | PgUUIDBuilder | PgInetBuilder
 * - number → PgDoublePrecisionBuilder | PgIntegerBuilder
 * - boolean → PgBooleanBuilder
 * - bigint → PgBigInt53Builder | PgBigInt64Builder
 * - Date → PgTimestampBuilder | PgDateBuilder | PgTimeBuilder
 * - arrays/objects → PgJsonbBuilder
 */
export type PgColumnType<T> =
    // String types - can be text, varchar, uuid, inet, etc.
    T extends string
        ? PgTextBuilder<any> | PgVarcharBuilder<any> | PgUUIDBuilder<any> | PgInetBuilder<any>
        : // Number types - can be double precision or integer
          T extends number
          ? PgDoublePrecisionBuilder<any> | PgIntegerBuilder<any>
          : // Boolean type
            T extends boolean
            ? PgBooleanBuilder<any>
            : // BigInt type
              T extends bigint
              ? PgBigInt53Builder<any> | PgBigInt64Builder<any>
              : // Date type - can be timestamp, date, or time
                T extends Date
                ? PgTimestampBuilder<any> | PgDateBuilder<any> | PgTimeBuilder<any>
                : // Arrays and objects become JSONB
                  T extends any[] | object
                  ? PgJsonbBuilder<any>
                  : // Fallback to base column builder
                    PgColumnBuilderBase;

// ============================================================================
// Table Config Type (for tableConfig parameter)
// ============================================================================

/**
 * Maps a TypeScript type T to a partial record of drizzle column builders.
 * Each property key must exist in T, and the value must be the appropriate column builder
 * for that property's type.
 *
 * This type is used for the `tableConfig` parameter to allow overriding specific columns
 * (e.g., for primary keys, foreign keys, custom constraints).
 *
 * @example
 * ```typescript
 * interface User {
 *   id: string;
 *   name: string;
 *   age: number;
 *   active: boolean;
 * }
 *
 * // Valid config - types match
 * const config: PgTableConfig<User> = {
 *   id: uuid('id').primaryKey(),  // string → PgUUIDBuilder ✓
 *   name: text('name'),           // string → PgTextBuilder ✓
 *   age: integer('age'),          // number → PgIntegerBuilder ✓
 * };
 *
 * // Invalid config - type mismatch would be caught
 * const badConfig: PgTableConfig<User> = {
 *   id: integer('id'),  // Error: string property can't use integer builder
 * };
 * ```
 */
export type PgTableConfig<T> = {
    [K in keyof T]?: PgColumnType<T[K]>;
};

// ============================================================================
// Auto-Generated Columns Type (for return type)
// ============================================================================

/**
 * Maps each property of T to its corresponding PostgreSQL column builder.
 * This represents the columns that will be auto-generated from the TypeScript type.
 *
 * Unlike PgTableConfig (which is partial), this maps ALL properties to column builders.
 */
export type AutoGeneratedPgColumns<T> = {
    [K in keyof T]: PgColumnType<T[K]>;
};

// ============================================================================
// Result Type
// ============================================================================

/**
 * Result type for drizzlePGTable function.
 * Returns a PgTableWithColumns where the columns are built from the auto-generated
 * columns merged with any overrides from tableConfig.
 *
 * The goal is that `drizzlePGTable<User>('users')` returns the same type as
 * `pgTable('users', {id: text('id'), name: text('name'), ...})`.
 */
export type DrizzlePgTableResult<
    TTableName extends string,
    T,
    TConfig extends PgTableConfig<T> = PgTableConfig<T>,
> = PgTableWithColumns<{
    name: TTableName;
    schema: undefined;
    columns: BuildColumns<TTableName, AutoGeneratedPgColumns<T> & TConfig, 'pg'>;
    dialect: 'pg';
}>;
