/* ########
 * 2026 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import {ExtractedPureFn} from './types.ts';

/** Generates the virtual module source code from extracted server pure functions */
export function generateServerPureFnsVirtualModule(extractedFns: ExtractedPureFn[]): string {
    // Group functions by namespace
    const byNamespace = new Map<string, ExtractedPureFn[]>();
    for (const fn of extractedFns) {
        const list = byNamespace.get(fn.namespace) || [];
        list.push(fn);
        byNamespace.set(fn.namespace, list);
    }

    // Generate nested namespace entries
    const namespaceEntries: string[] = [];
    for (const [namespace, fns] of byNamespace) {
        const fnEntries = fns.map((fn) => generateEntryCode(fn));
        namespaceEntries.push(`    ${JSON.stringify(namespace)}: {\n${fnEntries.join(',\n')}\n    }`);
    }

    return `// Auto-generated by @mionjs/server-pure-functions
// Do not edit manually

export const serverPureFnsCache = {
${namespaceEntries.join(',\n')}
};
`;
}

/** Generates the code for a single server pure function entry */
function generateEntryCode(fn: ExtractedPureFn): string {
    const paramsArray = fn.paramNames.map((p) => JSON.stringify(p)).join(', ');

    // Convert dependencies from "namespace::fnName" to just "fnName" (same-namespace resolution)
    const depsArray = [...fn.dependencies].map((d) => {
        const parts = d.split('::');
        return JSON.stringify(parts.length === 2 ? parts[1] : d);
    });

    // Generate the function code
    const fnCode = fn.isFactory ? generateFactoryFn(fn) : generateDirectFn(fn);

    const depsLine = depsArray.length > 0 ? `\n            pureFnDependencies: [${depsArray.join(', ')}],` : '';

    return `        ${JSON.stringify(fn.fnName)}: {
            namespace: ${JSON.stringify(fn.namespace)},
            fnName: ${JSON.stringify(fn.fnName)},
            paramNames: [${paramsArray}],
            code: ${JSON.stringify(fn.fnBody)},
            bodyHash: ${JSON.stringify(fn.bodyHash)},${depsLine}
            isFactory: ${fn.isFactory},
${fnCode}
        }`;
}

/** Generates a direct fn property for a regular pure function */
function generateDirectFn(fn: ExtractedPureFn): string {
    const params = fn.paramNames.join(', ');
    const safeName = makeSafeFunctionName(fn.fnName);

    return `            fn: function ${safeName}(${params}) {
                ${fn.fnBody}
            },`;
}

/** Generates createFn + fn: undefined for a factory function */
function generateFactoryFn(fn: ExtractedPureFn): string {
    const params = fn.paramNames.join(', ');
    const safeName = makeSafeFunctionName(fn.fnName);

    return `            fn: undefined,
            createFn: function ${safeName}(jitUtils) {
                return (function factory(${params}) {
                    ${fn.fnBody}
                })(jitUtils);
            },`;
}

/** Makes a function name safe for use as a JavaScript identifier */
function makeSafeFunctionName(name: string): string {
    // Replace any non-alphanumeric characters with underscores
    const safe = name.replace(/[^a-zA-Z0-9_$]/g, '_');
    // Ensure it starts with a letter or underscore
    if (/^[0-9]/.test(safe)) {
        return '_' + safe;
    }
    return safe || 'anonymous';
}
