// importmap.go — the SECOND output of this generator: the import map
// `mion drizzle-migrate` rewrites drizzle imports with.
//
// The map is a pure JOIN of the two things this tool already owns: the
// hand-owned drizzle-dialects.json (which drizzle module each package wraps)
// and the per-dialect manifests (which of that module's exports are migrated).
// A `migrated` entry is guaranteed by validate() to be a LOCAL export of the
// proxy package under the SAME name, which is exactly what makes the rewrite a
// rename of the module specifier and nothing else.
//
// It lands INSIDE the Go module (internal/drizzlemigrate/importmap.json) because
// the shipped binary has no repo to read the manifests from: the drizzle-e2e
// lane runs the published `@mionjs/bin-compiler` launcher inside a container. Being
// generator-owned means `pnpm miondevx core drizzle-manifest --check` catches drift in
// it the same way it does for the manifests, so the translator and the coverage
// gate can never disagree about the boundary.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
)

// Where the emitted map lives, repo-root-relative. Inside the Go module so
// internal/drizzlemigrate can go:embed it.
const importMapPath = "ts-go-runtypes/internal/drizzlemigrate/importmap.json"

const importMapComment = "AUTO-GENERATED by `pnpm miondevx core drizzle-manifest` (ts-go-runtypes/cmd/gen-drizzle-manifest), " +
	"joining drizzle-dialects.json with the per-dialect manifests. The map `mion drizzle-migrate` rewrites " +
	"drizzle imports with: a `migrated` export moves to the wrapping package under the same name, everything else " +
	"stays on drizzle. Never hand-edit; flip an entry's `status` in its manifest instead. " +
	"CI gate: `pnpm miondevx core drizzle-manifest --check`."

// ImportMapModule is one drizzle module's rewrite rule.
type ImportMapModule struct {
	Dialect string `json:"dialect"`
	// From is the drizzle module specifier the suites import from.
	From string `json:"from"`
	// To is the wrapping mion package a migrated name moves to.
	To string `json:"to"`
	// ToDrizzle is the subpath exporting toDrizzle(), empty for the
	// dialect-agnostic root package (which has no materializer).
	ToDrizzle string `json:"toDrizzle,omitempty"`
	// Migrated is every export that moves, sorted.
	Migrated []string `json:"migrated"`
	// Columns are the migrated exports that build a COLUMN. A column call only
	// ever lives inside a table's columns record, never as a declaration of its
	// own, which is what lets drizzle-migrate's vocabulary gate ask about the
	// rest without listing sixty column builders by hand.
	Columns []string `json:"columns"`
	// Alias renames a moved export's local (see DialectConfig.MigrateAlias).
	Alias map[string]string `json:"alias,omitempty"`
}

// ImportMap is the emitted file.
type ImportMap struct {
	Comment    string            `json:"$comment"`
	DrizzleOrm string            `json:"drizzleOrm"`
	Modules    []ImportMapModule `json:"modules"`
}

// packageNameOf reads a dialect package's npm name; that name, not the
// directory, is what an import specifier has to say.
func packageNameOf(repoRoot string, dialect DialectConfig) (string, error) {
	manifestPath := filepath.Join(repoRoot, filepath.FromSlash(dialect.PackageDir), "package.json")
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return "", fmt.Errorf("import map: %s: %w", dialect.PackageDir+"/package.json", err)
	}
	var pkg struct {
		Name string `json:"name"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return "", fmt.Errorf("import map: parse %s: %w", dialect.PackageDir+"/package.json", err)
	}
	if pkg.Name == "" {
		return "", fmt.Errorf("import map: %s/package.json has no name", dialect.PackageDir)
	}
	return pkg.Name, nil
}

// buildImportMap projects the merged manifest onto the rewrite rules.
func buildImportMap(repoRoot string, config *Config, manifest *Manifest) (*ImportMap, error) {
	migratedByDialect := map[string][]string{}
	columnsByDialect := map[string][]string{}
	for _, entry := range manifest.Entries {
		if entry.Status == statusMigrated {
			migratedByDialect[entry.Dialect] = append(migratedByDialect[entry.Dialect], entry.Fn)
			if entry.Kind == "column" {
				columnsByDialect[entry.Dialect] = append(columnsByDialect[entry.Dialect], entry.Fn)
			}
		}
	}
	importMap := &ImportMap{Comment: importMapComment, DrizzleOrm: manifest.DrizzleOrm}
	for _, dialect := range config.Dialects {
		packageName, err := packageNameOf(repoRoot, dialect)
		if err != nil {
			return nil, err
		}
		migrated := append([]string(nil), migratedByDialect[dialect.Dialect]...)
		slices.Sort(migrated)
		columns := append([]string(nil), columnsByDialect[dialect.Dialect]...)
		slices.Sort(columns)
		module := ImportMapModule{
			Dialect:  dialect.Dialect,
			From:     dialect.Module,
			To:       packageName,
			Migrated: migrated,
			Columns:  columns,
			Alias:    dialect.MigrateAlias,
		}
		// Only a dialect package materializes tables; the root package carries
		// the shared vocabulary and has no toDrizzle.
		if !dialect.NoColumnBuilders {
			module.ToDrizzle = packageName + "/drizzle"
		}
		importMap.Modules = append(importMap.Modules, module)
	}
	slices.SortFunc(importMap.Modules, func(a, b ImportMapModule) int {
		if a.From == b.From {
			return 0
		}
		if a.From < b.From {
			return -1
		}
		return 1
	})
	return importMap, nil
}

func marshalImportMap(importMap *ImportMap) ([]byte, error) {
	encoded, err := json.MarshalIndent(importMap, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}
