package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const manifestRelPath = "packages/drizzle/drizzle-columns.manifest.json"

const manifestComment = "AUTO-GENERATED by `pnpm rtx core drizzle-manifest` (ts-go-runtypes/cmd/gen-drizzle-manifest). " +
	"Hand-edit ONLY `status` and `reason` on column and function entries; the drizzle-proxy-migration skill drives review. " +
	"CI gate: `pnpm rtx core drizzle-manifest --check`."

const passthroughReason = "class or constant; passes through via export *"

// Entry statuses. Passthrough entries (classes/constants) are always
// generator-skipped; column builders AND callable functions start pending and
// are hand-flipped to migrated (wrapper/mapping authored as a local proxy
// export) or skipped (no runtype mapping needed, reason required - the
// explicit "no mapping needed" marker).
const (
	statusPending  = "pending"
	statusMigrated = "migrated"
	statusSkipped  = "skipped"
)

type Entry struct {
	Dialect string   `json:"dialect"`
	Fn      string   `json:"fn"`
	Kind    string   `json:"kind"`
	Params  []string `json:"params,omitempty"`
	Status  string   `json:"status"`
	Reason  string   `json:"reason,omitempty"`
}

type Manifest struct {
	Comment    string  `json:"$comment"`
	DrizzleOrm string  `json:"drizzleOrm"`
	Entries    []Entry `json:"entries"`
}

func entryKey(entry Entry) string { return entry.Dialect + ":" + entry.Fn }

// merge folds the committed manifest's hand-owned fields (status, reason on
// column and function entries) into a fresh extraction. New reviewable
// entries arrive pending; a migrated entry whose recorded params drifted
// (drizzle upgrade) is downgraded to pending so the mapping gets re-reviewed;
// entries drizzle no longer exports are dropped by construction (fresh is the
// base). Passthrough entries are fully regenerated every run.
func merge(fresh *Manifest, committed *Manifest) *Manifest {
	committedByKey := map[string]Entry{}
	if committed != nil {
		for _, entry := range committed.Entries {
			committedByKey[entryKey(entry)] = entry
		}
	}
	merged := &Manifest{Comment: manifestComment, DrizzleOrm: fresh.DrizzleOrm}
	for _, entry := range fresh.Entries {
		previous, known := committedByKey[entryKey(entry)]
		if reviewableKind(entry.Kind) && known && previous.Kind == entry.Kind {
			entry.Status, entry.Reason = previous.Status, previous.Reason
			if previous.Status == statusMigrated && !slices.Equal(previous.Params, entry.Params) {
				entry.Status = statusPending
				entry.Reason = "params drifted; was: " + strings.Join(previous.Params, " | ")
			}
		}
		merged.Entries = append(merged.Entries, entry)
	}
	slices.SortFunc(merged.Entries, func(a, b Entry) int {
		if a.Dialect != b.Dialect {
			return strings.Compare(a.Dialect, b.Dialect)
		}
		return strings.Compare(a.Fn, b.Fn)
	})
	return merged
}

// validate enforces the always-on invariants: legal statuses, reasons on
// skips, at least one column AND one callable function per dialect, and every
// migrated fn present as a LOCAL export of its proxy module (star re-exports
// don't count).
func validate(manifest *Manifest, localExportsByDialect map[string]map[string]bool) error {
	var problems []string
	columnsPerDialect := map[string]int{}
	functionsPerDialect := map[string]int{}
	for _, entry := range manifest.Entries {
		if entry.Kind == "column" {
			columnsPerDialect[entry.Dialect]++
		}
		if entry.Kind == "function" {
			functionsPerDialect[entry.Dialect]++
		}
		switch entry.Status {
		case statusPending, statusMigrated:
		case statusSkipped:
			if entry.Reason == "" {
				problems = append(problems, fmt.Sprintf("%s.%s: skipped without a reason", entry.Dialect, entry.Fn))
			}
		default:
			problems = append(problems, fmt.Sprintf("%s.%s: unknown status %q", entry.Dialect, entry.Fn, entry.Status))
		}
		if entry.Status == statusMigrated && !localExportsByDialect[entry.Dialect][entry.Fn] {
			problems = append(problems, fmt.Sprintf("%s.%s: migrated but not a local export of src/proxies/%s.ts", entry.Dialect, entry.Fn, entry.Dialect))
		}
	}
	for _, dialect := range dialects {
		if columnsPerDialect[dialect.Name] == 0 {
			problems = append(problems, fmt.Sprintf("%s: extraction found ZERO column builders (classifier or resolution broke)", dialect.Name))
		}
		if functionsPerDialect[dialect.Name] == 0 {
			problems = append(problems, fmt.Sprintf("%s: extraction found ZERO callable functions (classifier or resolution broke)", dialect.Name))
		}
	}
	if len(problems) > 0 {
		return errors.New("manifest invalid:\n  " + strings.Join(problems, "\n  "))
	}
	return nil
}

func marshalManifest(manifest *Manifest) ([]byte, error) {
	encoded, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

func loadCommitted(path string) (*Manifest, error) {
	raw, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var manifest Manifest
	if err := json.Unmarshal(raw, &manifest); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &manifest, nil
}

// diffSummary names the entries that differ between the committed manifest
// and a fresh merge, for actionable --check failures.
func diffSummary(committed *Manifest, merged *Manifest) []string {
	committedByKey := map[string]Entry{}
	if committed != nil {
		for _, entry := range committed.Entries {
			committedByKey[entryKey(entry)] = entry
		}
	}
	var lines []string
	seen := map[string]bool{}
	for _, entry := range merged.Entries {
		key := entryKey(entry)
		seen[key] = true
		previous, known := committedByKey[key]
		if !known {
			lines = append(lines, "added "+key)
		} else if !slices.Equal(previous.Params, entry.Params) || previous.Kind != entry.Kind || previous.Status != entry.Status || previous.Reason != entry.Reason {
			lines = append(lines, "changed "+key)
		}
	}
	for key := range committedByKey {
		if !seen[key] {
			lines = append(lines, "removed "+key)
		}
	}
	slices.Sort(lines)
	if committed != nil && committed.DrizzleOrm != merged.DrizzleOrm {
		lines = append(lines, fmt.Sprintf("drizzle-orm version %s -> %s", committed.DrizzleOrm, merged.DrizzleOrm))
	}
	return lines
}

func run(repoRoot string, check bool) error {
	manifestPath := filepath.Join(repoRoot, filepath.FromSlash(manifestRelPath))
	fresh, localExportsByDialect, err := extract(repoRoot)
	if err != nil {
		return err
	}
	committed, err := loadCommitted(manifestPath)
	if err != nil {
		return err
	}
	merged := merge(fresh, committed)
	if err := validate(merged, localExportsByDialect); err != nil {
		return err
	}
	encoded, err := marshalManifest(merged)
	if err != nil {
		return err
	}
	if check {
		committedRaw, readErr := os.ReadFile(manifestPath)
		if readErr != nil {
			return fmt.Errorf("--check: %s missing - run `pnpm rtx core drizzle-manifest` and commit it", manifestRelPath)
		}
		if !bytes.Equal(committedRaw, encoded) {
			return errors.New("manifest drift - run `pnpm rtx core drizzle-manifest` and commit:\n  " + strings.Join(diffSummary(committed, merged), "\n  "))
		}
		var pending []string
		for _, entry := range merged.Entries {
			if entry.Status == statusPending {
				pending = append(pending, entryKey(entry))
			}
		}
		if len(pending) > 0 {
			return errors.New("pending manifest entries (run the drizzle-proxy-migration skill):\n  " + strings.Join(pending, "\n  "))
		}
	} else if err := os.WriteFile(manifestPath, encoded, 0o644); err != nil {
		return err
	}
	printSummary(merged)
	return nil
}

func printSummary(manifest *Manifest) {
	for _, dialect := range dialects {
		for _, kind := range []string{"column", "function"} {
			counts := map[string]int{}
			total := 0
			for _, entry := range manifest.Entries {
				if entry.Dialect == dialect.Name && entry.Kind == kind {
					counts[entry.Status]++
					total++
				}
			}
			fmt.Printf("%s: %d %s entries - %d migrated, %d pending, %d skipped\n",
				dialect.Name, total, kind, counts[statusMigrated], counts[statusPending], counts[statusSkipped])
		}
	}
}

// reviewableKind reports whether hand-set statuses on this kind survive
// regeneration (columns and callable functions; passthrough never does).
func reviewableKind(kind string) bool {
	return kind == "column" || kind == "function"
}
