package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const manifestComment = "AUTO-GENERATED by `pnpm rtx core drizzle-manifest` (ts-go-runtypes/cmd/gen-drizzle-manifest). " +
	"One manifest per dialect package, driven by the hand-owned drizzle-dialects.json at the repo root. " +
	"Hand-edit ONLY `status` and `reason` on column and function entries; the drizzle-slim-schemas skill drives review. " +
	"CI gate: `pnpm rtx core drizzle-manifest --check`."

const passthroughReason = "class or constant; passes through via export *"

// Entry statuses. Passthrough entries (classes/constants) are always
// generator-skipped; column builders AND callable functions start pending and
// are hand-flipped to migrated (wrapper/mapping authored as a local proxy
// export) or skipped (no runtype mapping needed, reason required - the
// explicit "no mapping needed" marker).
const (
	statusPending  = "pending"
	statusMigrated = "migrated"
	statusSkipped  = "skipped"
)

// DialectConfig is one row of the hand-owned dialects.json: everything the
// tool needs to know about a dialect. PackageDir is repo-root-relative (each
// dialect lives in its own package); Proxy and Manifest are packageDir-relative.
type DialectConfig struct {
	Dialect    string `json:"dialect"`
	Module     string `json:"module"`
	PackageDir string `json:"packageDir"`
	Proxy      string `json:"proxy"`
	Manifest   string `json:"manifest"`
	// NoColumnBuilders marks a module that legitimately exports no column
	// builders (the root drizzle-orm module); validation skips its
	// zero-columns coverage check.
	NoColumnBuilders bool `json:"noColumnBuilders,omitempty"`
	// MigrateAlias names the migrated exports drizzle-migrate must import
	// under a DIFFERENT local, because the drizzle spelling stays in use in
	// the same file (`sql`: ours records, drizzle's queries). Hand-owned, and
	// the only input to the import map that is not derived.
	MigrateAlias map[string]string `json:"migrateAlias,omitempty"`
}

func (dialect DialectConfig) manifestPath(repoRoot string) string {
	return filepath.Join(repoRoot, filepath.FromSlash(dialect.PackageDir), filepath.FromSlash(dialect.Manifest))
}

func (dialect DialectConfig) proxyPath(repoRoot string) string {
	return filepath.Join(repoRoot, filepath.FromSlash(dialect.PackageDir), filepath.FromSlash(dialect.Proxy))
}

// manifestRef names a dialect's manifest file repo-root-relatively for
// messages ("packages/drizzle-orm-pg-core/manifests/pg.manifest.json").
func (dialect DialectConfig) manifestRef() string {
	return dialect.PackageDir + "/" + dialect.Manifest
}

// Config is the required --config file (dialects.json). It is INPUT, never
// written by the tool: the supported dialects and their files live here, not
// in Go code.
type Config struct {
	Comment  string          `json:"$comment,omitempty"`
	Dialects []DialectConfig `json:"dialects"`
}

func loadConfig(path string) (*Config, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("--config %s: %w", path, err)
	}
	var config Config
	if err := json.Unmarshal(raw, &config); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	var problems []string
	if len(config.Dialects) == 0 {
		problems = append(problems, "at least one dialect is required")
	}
	seenDialect, seenManifest := map[string]bool{}, map[string]bool{}
	for _, dialect := range config.Dialects {
		if dialect.Dialect == "" || dialect.Module == "" || dialect.PackageDir == "" || dialect.Proxy == "" || dialect.Manifest == "" {
			problems = append(problems, fmt.Sprintf("dialect %q: dialect, module, packageDir, proxy and manifest are all required", dialect.Dialect))
			continue
		}
		if seenDialect[dialect.Dialect] {
			problems = append(problems, "duplicate dialect "+dialect.Dialect)
		}
		if seenManifest[dialect.manifestRef()] {
			problems = append(problems, "duplicate manifest file "+dialect.manifestRef())
		}
		for _, pathField := range []struct{ name, value string }{{"packageDir", dialect.PackageDir}, {"proxy", dialect.Proxy}, {"manifest", dialect.Manifest}} {
			if filepath.IsAbs(pathField.value) || strings.HasPrefix(pathField.value, "..") || strings.Contains(pathField.value, "/../") || strings.ContainsRune(pathField.value, '\\') {
				problems = append(problems, fmt.Sprintf("dialect %s: %s must be a forward-slash relative path inside the repo, got %q", dialect.Dialect, pathField.name, pathField.value))
			}
		}
		if !strings.HasSuffix(dialect.Manifest, ".manifest.json") {
			problems = append(problems, fmt.Sprintf("dialect %s: manifest must be a packageDir-relative *.manifest.json path, got %q", dialect.Dialect, dialect.Manifest))
		}
		seenDialect[dialect.Dialect], seenManifest[dialect.manifestRef()] = true, true
	}
	if len(problems) > 0 {
		return nil, fmt.Errorf("invalid config %s:\n  %s", path, strings.Join(problems, "\n  "))
	}
	return &config, nil
}

// Entry.Dialect is in-memory only (json:"-"): on disk the dialect is the
// file's root metadata and is stamped back onto entries at load time.
// Modifiers and TypeAlias are GENERATED (never hand-owned): the chainable
// modifier methods drizzle's builder exposes for a column entry, and the
// pure-type column alias the proxy package exports for it (upperFirst rule) -
// the machine-readable vocabulary the type road and the convert program share.
type Entry struct {
	Dialect   string   `json:"-"`
	Fn        string   `json:"fn"`
	Kind      string   `json:"kind"`
	Params    []string `json:"params,omitempty"`
	Modifiers []string `json:"modifiers,omitempty"`
	Handles   []string `json:"handles,omitempty"`
	TypeAlias string   `json:"typeAlias,omitempty"`
	Status    string   `json:"status"`
	Reason    string   `json:"reason,omitempty"`
}

// Manifest doubles as the combined in-memory model (Dialect empty, entries
// spanning all dialects) and the on-disk per-dialect file (Dialect set).
type Manifest struct {
	Comment    string  `json:"$comment"`
	Dialect    string  `json:"dialect,omitempty"`
	DrizzleOrm string  `json:"drizzleOrm"`
	Entries    []Entry `json:"entries"`
}

func entryKey(entry Entry) string { return entry.Dialect + ":" + entry.Fn }

// merge folds the committed manifest's hand-owned fields (status, reason on
// column and function entries) into a fresh extraction. New reviewable
// entries arrive pending; a migrated entry whose recorded params drifted
// (drizzle upgrade) is downgraded to pending so the mapping gets re-reviewed;
// entries drizzle no longer exports are dropped by construction (fresh is the
// base). Passthrough entries are fully regenerated every run.
func merge(fresh *Manifest, committed *Manifest) *Manifest {
	committedByKey := map[string]Entry{}
	if committed != nil {
		for _, entry := range committed.Entries {
			committedByKey[entryKey(entry)] = entry
		}
	}
	merged := &Manifest{Comment: manifestComment, DrizzleOrm: fresh.DrizzleOrm}
	for _, entry := range fresh.Entries {
		previous, known := committedByKey[entryKey(entry)]
		if reviewableKind(entry.Kind) && known && previous.Kind == entry.Kind {
			entry.Status, entry.Reason = previous.Status, previous.Reason
			if previous.Status == statusMigrated && !slices.Equal(previous.Params, entry.Params) {
				entry.Status = statusPending
				entry.Reason = "params drifted; was: " + strings.Join(previous.Params, " | ")
			}
		}
		merged.Entries = append(merged.Entries, entry)
	}
	slices.SortFunc(merged.Entries, func(a, b Entry) int {
		if a.Dialect != b.Dialect {
			return strings.Compare(a.Dialect, b.Dialect)
		}
		return strings.Compare(a.Fn, b.Fn)
	})
	return merged
}

// validate enforces the always-on invariants: legal statuses, reasons on
// skips, at least one column AND one callable function per configured
// dialect, and every migrated fn present as a LOCAL export of its proxy
// module (star re-exports don't count).
func validate(manifest *Manifest, localExportsByDialect map[string]map[string]bool, config *Config) error {
	var problems []string
	columnsPerDialect := map[string]int{}
	functionsPerDialect := map[string]int{}
	for _, entry := range manifest.Entries {
		if entry.Kind == "column" {
			columnsPerDialect[entry.Dialect]++
		}
		if entry.Kind == "function" {
			functionsPerDialect[entry.Dialect]++
		}
		switch entry.Status {
		case statusPending, statusMigrated:
		case statusSkipped:
			if entry.Reason == "" {
				problems = append(problems, fmt.Sprintf("%s.%s: skipped without a reason", entry.Dialect, entry.Fn))
			}
		default:
			problems = append(problems, fmt.Sprintf("%s.%s: unknown status %q", entry.Dialect, entry.Fn, entry.Status))
		}
		if entry.Status == statusMigrated && !localExportsByDialect[entry.Dialect][entry.Fn] {
			problems = append(problems, fmt.Sprintf("%s.%s: migrated but not a local export of the configured proxy", entry.Dialect, entry.Fn))
		}
	}
	for _, dialect := range config.Dialects {
		if columnsPerDialect[dialect.Dialect] == 0 && !dialect.NoColumnBuilders {
			problems = append(problems, fmt.Sprintf("%s: extraction found ZERO column builders (classifier or resolution broke)", dialect.Dialect))
		}
		if functionsPerDialect[dialect.Dialect] == 0 {
			problems = append(problems, fmt.Sprintf("%s: extraction found ZERO callable functions (classifier or resolution broke)", dialect.Dialect))
		}
	}
	if len(problems) > 0 {
		return errors.New("manifest invalid:\n  " + strings.Join(problems, "\n  "))
	}
	return nil
}

// manifestForDialect projects the combined manifest into one dialect's file
// model (dialect at the root, entries without it).
func manifestForDialect(manifest *Manifest, dialectName string) *Manifest {
	dialectManifest := &Manifest{Comment: manifestComment, Dialect: dialectName, DrizzleOrm: manifest.DrizzleOrm}
	for _, entry := range manifest.Entries {
		if entry.Dialect == dialectName {
			dialectManifest.Entries = append(dialectManifest.Entries, entry)
		}
	}
	return dialectManifest
}

func marshalManifest(manifest *Manifest) ([]byte, error) {
	encoded, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

// loadCommitted reads every configured dialect's manifest file from its own
// package dir and combines them into one in-memory manifest, stamping each
// file's dialect back onto its entries. Missing files are tolerated (first
// run, new dialect); no files at all means no committed manifest yet.
func loadCommitted(repoRoot string, config *Config) (*Manifest, error) {
	combined := &Manifest{}
	found := false
	for _, dialect := range config.Dialects {
		path := dialect.manifestPath(repoRoot)
		raw, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		var dialectManifest Manifest
		if err := json.Unmarshal(raw, &dialectManifest); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		found = true
		combined.DrizzleOrm = dialectManifest.DrizzleOrm
		for _, entry := range dialectManifest.Entries {
			entry.Dialect = dialect.Dialect
			combined.Entries = append(combined.Entries, entry)
		}
	}
	if !found {
		return nil, nil
	}
	return combined, nil
}

// strayManifestFiles lists *.manifest.json files in any configured manifest
// dir that no configured dialect claims (a removed dialect, a typo'd
// hand-made file). Returned paths are absolute.
func strayManifestFiles(repoRoot string, config *Config) ([]string, error) {
	known := map[string]bool{}
	manifestDirs := map[string]bool{}
	for _, dialect := range config.Dialects {
		known[dialect.manifestPath(repoRoot)] = true
		manifestDirs[filepath.Dir(dialect.manifestPath(repoRoot))] = true
	}
	var strays []string
	for manifestDir := range manifestDirs {
		dirEntries, err := os.ReadDir(manifestDir)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		for _, dirEntry := range dirEntries {
			name := dirEntry.Name()
			if !dirEntry.IsDir() && strings.HasSuffix(name, ".manifest.json") && !known[filepath.Join(manifestDir, name)] {
				strays = append(strays, filepath.Join(manifestDir, name))
			}
		}
	}
	slices.Sort(strays)
	return strays, nil
}

// diffSummary names the entries that differ between the committed manifests
// and a fresh merge, for actionable --check failures.
func diffSummary(committed *Manifest, merged *Manifest) []string {
	committedByKey := map[string]Entry{}
	if committed != nil {
		for _, entry := range committed.Entries {
			committedByKey[entryKey(entry)] = entry
		}
	}
	var lines []string
	seen := map[string]bool{}
	for _, entry := range merged.Entries {
		key := entryKey(entry)
		seen[key] = true
		previous, known := committedByKey[key]
		if !known {
			lines = append(lines, "added "+key)
		} else if !slices.Equal(previous.Params, entry.Params) || !slices.Equal(previous.Modifiers, entry.Modifiers) || !slices.Equal(previous.Handles, entry.Handles) ||
			previous.TypeAlias != entry.TypeAlias || previous.Kind != entry.Kind || previous.Status != entry.Status ||
			previous.Reason != entry.Reason {
			lines = append(lines, "changed "+key)
		}
	}
	for key := range committedByKey {
		if !seen[key] {
			lines = append(lines, "removed "+key)
		}
	}
	slices.Sort(lines)
	if committed != nil && committed.DrizzleOrm != merged.DrizzleOrm {
		lines = append(lines, fmt.Sprintf("drizzle-orm version %s -> %s", committed.DrizzleOrm, merged.DrizzleOrm))
	}
	return lines
}

func run(repoRoot string, configPath string, check bool, pending bool) error {
	config, err := loadConfig(configPath)
	if err != nil {
		return err
	}
	fresh, localExportsByDialect, err := extract(repoRoot, config)
	if err != nil {
		return err
	}
	committed, err := loadCommitted(repoRoot, config)
	if err != nil {
		return err
	}
	merged := merge(fresh, committed)
	// --pending is pure inspection: print the review queue and stop. It never
	// writes and never fails, so agents can run it any time; --check stays the
	// gate.
	if pending {
		fmt.Print(pendingReport(merged))
		return nil
	}
	if err := validate(merged, localExportsByDialect, config); err != nil {
		return err
	}
	strays, err := strayManifestFiles(repoRoot, config)
	if err != nil {
		return err
	}
	// The import map rides the same write / --check path as the manifests: it
	// is derived from them, so a manifest edit that never reached it would let
	// drizzle-migrate translate against a boundary nothing else believes in.
	importMap, err := buildImportMap(repoRoot, config, merged)
	if err != nil {
		return err
	}
	encodedImportMap, err := marshalImportMap(importMap)
	if err != nil {
		return err
	}
	importMapFile := filepath.Join(repoRoot, filepath.FromSlash(importMapPath))
	if check {
		committedImportMap, readErr := os.ReadFile(importMapFile)
		if readErr != nil {
			return fmt.Errorf("--check: %s missing - run `pnpm rtx core drizzle-manifest` and commit it", importMapPath)
		}
		if !bytes.Equal(committedImportMap, encodedImportMap) {
			return errors.New("--check: " + importMapPath + " drifted from the manifests - run `pnpm rtx core drizzle-manifest` and commit")
		}
	} else if err := os.WriteFile(importMapFile, encodedImportMap, 0o644); err != nil {
		return err
	}
	if check {
		if len(strays) > 0 {
			return fmt.Errorf("--check: manifest files no dialect in %s claims (removed dialect or hand-made file): %s - run `pnpm rtx core drizzle-manifest` and commit", configPath, strings.Join(repoRelative(repoRoot, strays), ", "))
		}
		var drifted []string
		for _, dialect := range config.Dialects {
			encoded, marshalErr := marshalManifest(manifestForDialect(merged, dialect.Dialect))
			if marshalErr != nil {
				return marshalErr
			}
			committedRaw, readErr := os.ReadFile(dialect.manifestPath(repoRoot))
			if readErr != nil {
				return fmt.Errorf("--check: %s missing - run `pnpm rtx core drizzle-manifest` and commit it", dialect.manifestRef())
			}
			if !bytes.Equal(committedRaw, encoded) {
				drifted = append(drifted, dialect.manifestRef())
			}
		}
		if len(drifted) > 0 {
			return errors.New("manifest drift in " + strings.Join(drifted, ", ") + " - run `pnpm rtx core drizzle-manifest` and commit:\n  " + strings.Join(diffSummary(committed, merged), "\n  "))
		}
		var pending []string
		for _, entry := range merged.Entries {
			if entry.Status == statusPending {
				pending = append(pending, entryKey(entry))
			}
		}
		if len(pending) > 0 {
			return errors.New("pending manifest entries - list them with `pnpm rtx core drizzle-manifest --pending`, then run the drizzle-slim-schemas skill:\n  " + strings.Join(pending, "\n  "))
		}
	} else {
		for _, dialect := range config.Dialects {
			encoded, marshalErr := marshalManifest(manifestForDialect(merged, dialect.Dialect))
			if marshalErr != nil {
				return marshalErr
			}
			if err := os.WriteFile(dialect.manifestPath(repoRoot), encoded, 0o644); err != nil {
				return err
			}
		}
		// the manifest files are generator-owned: unclaimed ones go away
		for _, stray := range strays {
			if err := os.Remove(stray); err != nil {
				return err
			}
			fmt.Printf("removed stray manifest %s\n", strings.Join(repoRelative(repoRoot, []string{stray}), ""))
		}
	}
	printSummary(merged, config)
	return nil
}

// repoRelative rewrites absolute paths repo-root-relatively for messages,
// falling back to the absolute path outside the root.
func repoRelative(repoRoot string, paths []string) []string {
	var relative []string
	for _, path := range paths {
		if rel, err := filepath.Rel(repoRoot, path); err == nil && !strings.HasPrefix(rel, "..") {
			relative = append(relative, filepath.ToSlash(rel))
		} else {
			relative = append(relative, path)
		}
	}
	return relative
}

func printSummary(manifest *Manifest, config *Config) {
	for _, dialect := range config.Dialects {
		for _, kind := range []string{"column", "function"} {
			counts := map[string]int{}
			total := 0
			for _, entry := range manifest.Entries {
				if entry.Dialect == dialect.Dialect && entry.Kind == kind {
					counts[entry.Status]++
					total++
				}
			}
			fmt.Printf("%s: %d %s entries - %d migrated, %d pending, %d skipped\n",
				dialect.Dialect, total, kind, counts[statusMigrated], counts[statusPending], counts[statusSkipped])
		}
	}
}

// pendingReport renders the review queue: every entry whose status is
// pending, with its kind, overload params and the reason the generator left
// (a drift note carries the previous shape). This is what the
// drizzle-slim-schemas skill works from, instead of hand-reading the
// manifest JSON.
func pendingReport(manifest *Manifest) string {
	var report strings.Builder
	count := 0
	for _, entry := range manifest.Entries {
		if entry.Status != statusPending {
			continue
		}
		count++
		fmt.Fprintf(&report, "\n%s.%s  [%s]\n", entry.Dialect, entry.Fn, entry.Kind)
		for _, params := range entry.Params {
			fmt.Fprintf(&report, "  params: %s\n", params)
		}
		if entry.Reason != "" {
			fmt.Fprintf(&report, "  reason: %s\n", entry.Reason)
		}
	}
	if count == 0 {
		return "nothing pending - every column and function entry is reviewed.\n"
	}
	header := fmt.Sprintf("%d entr%s awaiting review (status \"pending\") - the drizzle-slim-schemas skill drives the mapping:\n", count, map[bool]string{true: "y", false: "ies"}[count == 1])
	return header + report.String()
}

// reviewableKind reports whether hand-set statuses on this kind survive
// regeneration (columns and callable functions; passthrough never does).
func reviewableKind(kind string) bool {
	return kind == "column" || kind == "function"
}
