package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// One manifest file per dialect (pg.manifest.json, mysql.manifest.json,
// sqlite.manifest.json) so adding a dialect is adding a file; the dialect
// lives in each file's root metadata, never on the entries.
const manifestDirRelPath = "packages/drizzle/manifests"

func manifestFileName(dialectName string) string { return dialectName + ".manifest.json" }

const manifestComment = "AUTO-GENERATED by `pnpm rtx core drizzle-manifest` (ts-go-runtypes/cmd/gen-drizzle-manifest). " +
	"One manifest per dialect. Hand-edit ONLY `status` and `reason` on column and function entries; the drizzle-proxy-migration skill drives review. " +
	"CI gate: `pnpm rtx core drizzle-manifest --check`."

const passthroughReason = "class or constant; passes through via export *"

// index.json makes the layout self-describing: the supported dialects and the
// file each one lives in. Adding a dialect means adding it to the `dialects`
// slice in gen.go and regenerating, never hand-editing this file.
const indexFileName = "index.json"

const indexComment = "AUTO-GENERATED by `pnpm rtx core drizzle-manifest`. Lists the supported drizzle dialects and their manifest files. " +
	"To add a dialect, extend `dialects` in ts-go-runtypes/cmd/gen-drizzle-manifest/gen.go and regenerate; never hand-edit."

type IndexDialect struct {
	Dialect  string `json:"dialect"`
	Module   string `json:"module"`
	Proxy    string `json:"proxy"`
	Manifest string `json:"manifest"`
}

type ManifestIndex struct {
	Comment    string         `json:"$comment"`
	DrizzleOrm string         `json:"drizzleOrm"`
	Dialects   []IndexDialect `json:"dialects"`
}

func buildIndex(drizzleOrmVersion string) *ManifestIndex {
	index := &ManifestIndex{Comment: indexComment, DrizzleOrm: drizzleOrmVersion}
	for _, dialect := range dialects {
		index.Dialects = append(index.Dialects, IndexDialect{
			Dialect:  dialect.Name,
			Module:   dialect.Module,
			Proxy:    dialect.ProxyRelPath,
			Manifest: manifestFileName(dialect.Name),
		})
	}
	return index
}

func marshalIndex(index *ManifestIndex) ([]byte, error) {
	encoded, err := json.MarshalIndent(index, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

// Entry statuses. Passthrough entries (classes/constants) are always
// generator-skipped; column builders AND callable functions start pending and
// are hand-flipped to migrated (wrapper/mapping authored as a local proxy
// export) or skipped (no runtype mapping needed, reason required - the
// explicit "no mapping needed" marker).
const (
	statusPending  = "pending"
	statusMigrated = "migrated"
	statusSkipped  = "skipped"
)

// Entry.Dialect is in-memory only (json:"-"): on disk the dialect is the
// file's root metadata and is stamped back onto entries at load time.
type Entry struct {
	Dialect string   `json:"-"`
	Fn      string   `json:"fn"`
	Kind    string   `json:"kind"`
	Params  []string `json:"params,omitempty"`
	Status  string   `json:"status"`
	Reason  string   `json:"reason,omitempty"`
}

// Manifest doubles as the combined in-memory model (Dialect empty, entries
// spanning all dialects) and the on-disk per-dialect file (Dialect set).
type Manifest struct {
	Comment    string  `json:"$comment"`
	Dialect    string  `json:"dialect,omitempty"`
	DrizzleOrm string  `json:"drizzleOrm"`
	Entries    []Entry `json:"entries"`
}

func entryKey(entry Entry) string { return entry.Dialect + ":" + entry.Fn }

// merge folds the committed manifest's hand-owned fields (status, reason on
// column and function entries) into a fresh extraction. New reviewable
// entries arrive pending; a migrated entry whose recorded params drifted
// (drizzle upgrade) is downgraded to pending so the mapping gets re-reviewed;
// entries drizzle no longer exports are dropped by construction (fresh is the
// base). Passthrough entries are fully regenerated every run.
func merge(fresh *Manifest, committed *Manifest) *Manifest {
	committedByKey := map[string]Entry{}
	if committed != nil {
		for _, entry := range committed.Entries {
			committedByKey[entryKey(entry)] = entry
		}
	}
	merged := &Manifest{Comment: manifestComment, DrizzleOrm: fresh.DrizzleOrm}
	for _, entry := range fresh.Entries {
		previous, known := committedByKey[entryKey(entry)]
		if reviewableKind(entry.Kind) && known && previous.Kind == entry.Kind {
			entry.Status, entry.Reason = previous.Status, previous.Reason
			if previous.Status == statusMigrated && !slices.Equal(previous.Params, entry.Params) {
				entry.Status = statusPending
				entry.Reason = "params drifted; was: " + strings.Join(previous.Params, " | ")
			}
		}
		merged.Entries = append(merged.Entries, entry)
	}
	slices.SortFunc(merged.Entries, func(a, b Entry) int {
		if a.Dialect != b.Dialect {
			return strings.Compare(a.Dialect, b.Dialect)
		}
		return strings.Compare(a.Fn, b.Fn)
	})
	return merged
}

// validate enforces the always-on invariants: legal statuses, reasons on
// skips, at least one column AND one callable function per dialect, and every
// migrated fn present as a LOCAL export of its proxy module (star re-exports
// don't count).
func validate(manifest *Manifest, localExportsByDialect map[string]map[string]bool) error {
	var problems []string
	columnsPerDialect := map[string]int{}
	functionsPerDialect := map[string]int{}
	for _, entry := range manifest.Entries {
		if entry.Kind == "column" {
			columnsPerDialect[entry.Dialect]++
		}
		if entry.Kind == "function" {
			functionsPerDialect[entry.Dialect]++
		}
		switch entry.Status {
		case statusPending, statusMigrated:
		case statusSkipped:
			if entry.Reason == "" {
				problems = append(problems, fmt.Sprintf("%s.%s: skipped without a reason", entry.Dialect, entry.Fn))
			}
		default:
			problems = append(problems, fmt.Sprintf("%s.%s: unknown status %q", entry.Dialect, entry.Fn, entry.Status))
		}
		if entry.Status == statusMigrated && !localExportsByDialect[entry.Dialect][entry.Fn] {
			problems = append(problems, fmt.Sprintf("%s.%s: migrated but not a local export of src/proxies/%s.ts", entry.Dialect, entry.Fn, entry.Dialect))
		}
	}
	for _, dialect := range dialects {
		if columnsPerDialect[dialect.Name] == 0 {
			problems = append(problems, fmt.Sprintf("%s: extraction found ZERO column builders (classifier or resolution broke)", dialect.Name))
		}
		if functionsPerDialect[dialect.Name] == 0 {
			problems = append(problems, fmt.Sprintf("%s: extraction found ZERO callable functions (classifier or resolution broke)", dialect.Name))
		}
	}
	if len(problems) > 0 {
		return errors.New("manifest invalid:\n  " + strings.Join(problems, "\n  "))
	}
	return nil
}

// splitByDialect projects the combined manifest into the per-dialect file
// models, in the dialects order (which is the file order on disk too).
func splitByDialect(manifest *Manifest) []*Manifest {
	var perDialect []*Manifest
	for _, dialect := range dialects {
		dialectManifest := &Manifest{Comment: manifestComment, Dialect: dialect.Name, DrizzleOrm: manifest.DrizzleOrm}
		for _, entry := range manifest.Entries {
			if entry.Dialect == dialect.Name {
				dialectManifest.Entries = append(dialectManifest.Entries, entry)
			}
		}
		perDialect = append(perDialect, dialectManifest)
	}
	return perDialect
}

func marshalManifest(manifest *Manifest) ([]byte, error) {
	encoded, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

// loadCommitted reads every known dialect's manifest file from the manifests
// dir and combines them into one in-memory manifest, stamping each file's
// root dialect back onto its entries. Missing files are tolerated (first run,
// new dialect); no files at all means no committed manifest yet.
func loadCommitted(manifestDir string) (*Manifest, error) {
	combined := &Manifest{}
	found := false
	for _, dialect := range dialects {
		path := filepath.Join(manifestDir, manifestFileName(dialect.Name))
		raw, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		var dialectManifest Manifest
		if err := json.Unmarshal(raw, &dialectManifest); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		found = true
		combined.DrizzleOrm = dialectManifest.DrizzleOrm
		for _, entry := range dialectManifest.Entries {
			entry.Dialect = dialect.Name
			combined.Entries = append(combined.Entries, entry)
		}
	}
	if !found {
		return nil, nil
	}
	return combined, nil
}

// strayManifestFiles lists *.manifest.json files in the manifests dir that
// belong to no known dialect (a removed dialect, a typo'd hand-made file).
func strayManifestFiles(manifestDir string) ([]string, error) {
	dirEntries, err := os.ReadDir(manifestDir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	known := map[string]bool{}
	for _, dialect := range dialects {
		known[manifestFileName(dialect.Name)] = true
	}
	var strays []string
	for _, dirEntry := range dirEntries {
		name := dirEntry.Name()
		if !dirEntry.IsDir() && strings.HasSuffix(name, ".manifest.json") && !known[name] {
			strays = append(strays, name)
		}
	}
	slices.Sort(strays)
	return strays, nil
}

// diffSummary names the entries that differ between the committed manifests
// and a fresh merge, for actionable --check failures.
func diffSummary(committed *Manifest, merged *Manifest) []string {
	committedByKey := map[string]Entry{}
	if committed != nil {
		for _, entry := range committed.Entries {
			committedByKey[entryKey(entry)] = entry
		}
	}
	var lines []string
	seen := map[string]bool{}
	for _, entry := range merged.Entries {
		key := entryKey(entry)
		seen[key] = true
		previous, known := committedByKey[key]
		if !known {
			lines = append(lines, "added "+key)
		} else if !slices.Equal(previous.Params, entry.Params) || previous.Kind != entry.Kind || previous.Status != entry.Status || previous.Reason != entry.Reason {
			lines = append(lines, "changed "+key)
		}
	}
	for key := range committedByKey {
		if !seen[key] {
			lines = append(lines, "removed "+key)
		}
	}
	slices.Sort(lines)
	if committed != nil && committed.DrizzleOrm != merged.DrizzleOrm {
		lines = append(lines, fmt.Sprintf("drizzle-orm version %s -> %s", committed.DrizzleOrm, merged.DrizzleOrm))
	}
	return lines
}

func run(repoRoot string, check bool) error {
	manifestDir := filepath.Join(repoRoot, filepath.FromSlash(manifestDirRelPath))
	fresh, localExportsByDialect, err := extract(repoRoot)
	if err != nil {
		return err
	}
	committed, err := loadCommitted(manifestDir)
	if err != nil {
		return err
	}
	merged := merge(fresh, committed)
	if err := validate(merged, localExportsByDialect); err != nil {
		return err
	}
	strays, err := strayManifestFiles(manifestDir)
	if err != nil {
		return err
	}
	encodedIndex, err := marshalIndex(buildIndex(merged.DrizzleOrm))
	if err != nil {
		return err
	}
	if check {
		var drifted []string
		for _, dialectManifest := range splitByDialect(merged) {
			encoded, marshalErr := marshalManifest(dialectManifest)
			if marshalErr != nil {
				return marshalErr
			}
			fileName := manifestFileName(dialectManifest.Dialect)
			committedRaw, readErr := os.ReadFile(filepath.Join(manifestDir, fileName))
			if readErr != nil {
				return fmt.Errorf("--check: %s/%s missing - run `pnpm rtx core drizzle-manifest` and commit it", manifestDirRelPath, fileName)
			}
			if !bytes.Equal(committedRaw, encoded) {
				drifted = append(drifted, fileName)
			}
		}
		committedIndex, readErr := os.ReadFile(filepath.Join(manifestDir, indexFileName))
		if readErr != nil || !bytes.Equal(committedIndex, encodedIndex) {
			drifted = append(drifted, indexFileName)
		}
		if len(strays) > 0 {
			return fmt.Errorf("--check: unknown manifest files in %s (removed dialect or hand-made file): %s - run `pnpm rtx core drizzle-manifest` and commit", manifestDirRelPath, strings.Join(strays, ", "))
		}
		if len(drifted) > 0 {
			return errors.New("manifest drift in " + strings.Join(drifted, ", ") + " - run `pnpm rtx core drizzle-manifest` and commit:\n  " + strings.Join(diffSummary(committed, merged), "\n  "))
		}
		var pending []string
		for _, entry := range merged.Entries {
			if entry.Status == statusPending {
				pending = append(pending, entryKey(entry))
			}
		}
		if len(pending) > 0 {
			return errors.New("pending manifest entries (run the drizzle-proxy-migration skill):\n  " + strings.Join(pending, "\n  "))
		}
	} else {
		if err := os.MkdirAll(manifestDir, 0o755); err != nil {
			return err
		}
		for _, dialectManifest := range splitByDialect(merged) {
			encoded, marshalErr := marshalManifest(dialectManifest)
			if marshalErr != nil {
				return marshalErr
			}
			if err := os.WriteFile(filepath.Join(manifestDir, manifestFileName(dialectManifest.Dialect)), encoded, 0o644); err != nil {
				return err
			}
		}
		if err := os.WriteFile(filepath.Join(manifestDir, indexFileName), encodedIndex, 0o644); err != nil {
			return err
		}
		// the dir is generator-owned: files for dialects we no longer know go away
		for _, stray := range strays {
			if err := os.Remove(filepath.Join(manifestDir, stray)); err != nil {
				return err
			}
			fmt.Printf("removed stray manifest %s\n", stray)
		}
	}
	printSummary(merged)
	return nil
}

func printSummary(manifest *Manifest) {
	for _, dialect := range dialects {
		for _, kind := range []string{"column", "function"} {
			counts := map[string]int{}
			total := 0
			for _, entry := range manifest.Entries {
				if entry.Dialect == dialect.Name && entry.Kind == kind {
					counts[entry.Status]++
					total++
				}
			}
			fmt.Printf("%s: %d %s entries - %d migrated, %d pending, %d skipped\n",
				dialect.Name, total, kind, counts[statusMigrated], counts[statusPending], counts[statusSkipped])
		}
	}
}

// reviewableKind reports whether hand-set statuses on this kind survive
// regeneration (columns and callable functions; passthrough never does).
func reviewableKind(kind string) bool {
	return kind == "column" || kind == "function"
}
