/* ########
 * 2026 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import {describe, it, expect, afterAll} from 'vitest';
import {existsSync, readdirSync, readFileSync, statSync} from 'fs';
import {dirname, relative, resolve} from 'path';
import {pathToFileURL} from 'url';
import {spawn, type ChildProcess} from 'child_process';

// Runs AFTER scripts/release/e2e.mjs compiles with the PUBLISHED binary: tsconfig.compile.json into .mion-cli,
// then tsconfig.compile-fetch.json into .mion-cli-fetch with `--client-routes fetch`.
// Both emitted servers boot under plain node and answer their emitted client.

const rootDir = resolve(__dirname, '../..');
const outDir = resolve(rootDir, 'dist-cli');
const genDir = resolve(rootDir, '.mion-cli');
const serverJs = resolve(outDir, 'src/server/server.js');
const flowJs = resolve(outDir, 'src/client/batchFlow.js');
const tableJs = resolve(genDir, 'rpc/batches.generated.js');
const PORT = 8087;
const fetchOutDir = resolve(rootDir, 'dist-cli-fetch');
const fetchGenDir = resolve(rootDir, '.mion-cli-fetch');
const FETCH_PORT = 8088;

const servers: ChildProcess[] = [];

/** Every file under dir, recursively. */
function filesUnder(dir: string): string[] {
    if (!existsSync(dir)) return [];
    return readdirSync(dir).flatMap((name) => {
        const full = resolve(dir, name);
        return statSync(full).isDirectory() ? filesUnder(full) : [full];
    });
}

afterAll(() => servers.forEach((server) => server.kill('SIGTERM')));

function bootServer(file: string, port: number): ChildProcess {
    const server = spawn(process.execPath, [file], {
        cwd: rootDir,
        env: {...process.env, MION_TEST_PORT: String(port), MION_TEST_SERVER_AUTO_START: 'true'},
        stdio: ['ignore', 'inherit', 'inherit'],
    });
    servers.push(server);
    return server;
}

async function waitForPort(port: number, child: ChildProcess, timeoutMs = 60000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    let exited = false;
    child.once('exit', () => (exited = true));
    while (Date.now() < deadline) {
        if (exited) throw new Error(`the compiled server exited before accepting connections on ${port}`);
        try {
            await fetch(`http://127.0.0.1:${port}/`);
            return;
        } catch {
            await new Promise((r) => setTimeout(r, 200));
        }
    }
    throw new Error(`the compiled server did not accept connections on ${port} within ${timeoutMs}ms`);
}

describe('mion compile output', () => {
    it('emits the batch transport under the gen dir, relative imports only', () => {
        expect(existsSync(tableJs)).toBe(true);
        const table = readFileSync(tableJs, 'utf-8');
        expect(table).toMatch(/^\/\/ GENERATED by mion/);
        expect(table).toContain('replaceBatches({');
        // two package imports (the registries), then one relative import per mapper module
        const imports = [...table.matchAll(/import \{[^}]+\} from '([^']+)';/g)].map((m) => m[1]);
        const packages = imports.filter((specifier) => !specifier.startsWith('.'));
        const mapperImports = imports.filter((specifier) => specifier.startsWith('.'));
        expect(packages.sort()).toEqual(['@mionjs/core', '@mionjs/router']);
        expect(mapperImports.length).toBeGreaterThan(0);
        for (const specifier of mapperImports) {
            expect(specifier.startsWith('./pf/')).toBe(true);
            expect(existsSync(resolve(genDir, 'rpc', specifier))).toBe(true);
        }
        expect(table).not.toContain(rootDir);
        expect(table).not.toContain('clientRoot');
        // one batch, src/client/batchFlow.ts: the specs are not part of this compile
        const ids = [...table.matchAll(/"(b_[A-Za-z0-9_-]+)"/g)].map((m) => m[1]);
        expect(ids).toHaveLength(1);
        // one generated pure-fn module, under the path its id names: the package
        // that owns the mapper, then the hash half. No source path, because the id
        // carries none.
        const mappers = filesUnder(resolve(genDir, 'rpc/pf'));
        expect(mappers).toHaveLength(1);
        expect(mappers[0]).toMatch(/[\\/]pf[\\/].+[\\/][A-Za-z0-9_-]{14}\.js$/);
        // the mapper body authored in src/client/batchFlow.ts
        expect(readFileSync(mappers[0], 'utf-8')).toContain('customerValue.preferenceId');
    });

    it('the emitted server imports the table by itself, relativized to the gen dir', () => {
        const content = readFileSync(serverJs, 'utf-8');
        expect(content).not.toContain('rtrpc:');
        // dist-cli/src/server/server.js reaches .mion-cli/ three levels up
        const tableImport = relative(dirname(serverJs), tableJs);
        expect(tableImport).toBe('../../../.mion-cli/rpc/batches.generated.js');
        expect(content).toContain(`import '${tableImport}';`);
        expect(content).toContain('createMionRouter(');
    });

    it('the emitted client flow carries the batch id and mapper id the table registers', () => {
        const content = readFileSync(flowJs, 'utf-8');
        const table = readFileSync(tableJs, 'utf-8');
        const batchId = /'(b_[A-Za-z0-9_-]+)'/.exec(content)?.[1];
        const mapperKey = /'([^']+#[A-Za-z0-9_-]+)'/.exec(content)?.[1];
        expect(batchId, content).toBeDefined();
        expect(mapperKey, content).toBeDefined();
        expect(table).toContain(`"${batchId}"`);
        expect(table).toContain(`'${mapperKey}'`);
    });

    it('answers a batch with an inline mapper from the compiled client, under plain node', async () => {
        await waitForPort(PORT, bootServer(serverJs, PORT));
        const flow = (await import(pathToFileURL(flowJs).href)) as {
            runInlineMapperBatch: (baseURL: string) => Promise<{customer: unknown; prefs: unknown; errors: unknown[]}>;
        };
        const result = await flow.runInlineMapperBatch(`http://127.0.0.1:${PORT}`);
        expect(result.errors.filter(Boolean)).toEqual([]);
        expect(result.customer).toEqual({id: 7, name: 'Test Customer', preferenceId: 107});
        expect(result.prefs).toEqual({id: 107, userId: 7, theme: 'light'});
    });

    it('writes the server and the client manifests from one build, for mion api-check', () => {
        const server = JSON.parse(readFileSync(resolve(genDir, 'api/manifest.json'), 'utf-8')) as {kind: string};
        const client = JSON.parse(readFileSync(resolve(genDir, 'api/client-manifest.json'), 'utf-8')) as {
            kind: string;
            methods: Record<string, unknown>;
        };
        expect(server.kind).toBe('server');
        expect(client.kind).toBe('client');
        expect(Object.keys(client.methods)).toContain('getCustomerById');
    });
});

describe('mion compile output, client routes fetched', () => {
    it('bundles nothing for the client', () => {
        expect(existsSync(resolve(fetchGenDir, 'api/client-manifest.json'))).toBe(false);
        expect(readFileSync(resolve(fetchOutDir, 'src/client/fetchFlow.js'), 'utf-8')).not.toContain('.mion-cli-fetch/api/');
    });

    it('answers a call whose metadata the client fetched from the server, under plain node', async () => {
        await waitForPort(FETCH_PORT, bootServer(resolve(fetchOutDir, 'src/server/server.js'), FETCH_PORT));
        const flow = (await import(pathToFileURL(resolve(fetchOutDir, 'src/client/fetchFlow.js')).href)) as {
            runFetchedCall: (baseURL: string) => Promise<{customer: unknown; error: unknown}>;
        };
        const result = await flow.runFetchedCall(`http://127.0.0.1:${FETCH_PORT}`);
        expect(result.error).toBeUndefined();
        expect(result.customer).toEqual({id: 7, name: 'Test Customer', preferenceId: 107});
    });
});
