/* ########
 * 2026 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import {describe, it, expect, afterAll} from 'vitest';
import {existsSync, readdirSync, readFileSync} from 'fs';
import {resolve} from 'path';
import {pathToFileURL} from 'url';
import {spawn, type ChildProcess} from 'child_process';

// Runs AFTER `mion compile --tsconfig tsconfig.compile.json --gen-dir .mion-cli`, the tsc-like lane
// of the PUBLISHED binary over this consumer: client and server are one program here, so the compile
// generates the batch transport from its own batch() calls and inline inputFrom mappers into
// .mion-cli/rpc/, appends the table's import to the emitted router-init module, and splices the
// batch ids and mapper hashes into the emitted client flow. The last test boots that emitted server
// under plain node and runs the emitted client flow against it.

const rootDir = resolve(__dirname, '../..');
const outDir = resolve(rootDir, 'dist-cli');
const genDir = resolve(rootDir, '.mion-cli');
const serverJs = resolve(outDir, 'src/server/server.js');
const flowJs = resolve(outDir, 'src/client/batchFlow.js');
const tableJs = resolve(genDir, 'rpc/batches.generated.js');
const PORT = 8087;

let server: ChildProcess | undefined;
afterAll(() => server?.kill('SIGTERM'));

async function waitForPort(port: number, child: ChildProcess, timeoutMs = 60000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    let exited = false;
    child.once('exit', () => (exited = true));
    while (Date.now() < deadline) {
        if (exited) throw new Error(`the compiled server exited before accepting connections on ${port}`);
        try {
            await fetch(`http://127.0.0.1:${port}/`);
            return;
        } catch {
            await new Promise((r) => setTimeout(r, 200));
        }
    }
    throw new Error(`the compiled server did not accept connections on ${port} within ${timeoutMs}ms`);
}

describe('mion compile output', () => {
    it('emits the batch transport under the gen dir, relative imports only', () => {
        expect(existsSync(tableJs)).toBe(true);
        const table = readFileSync(tableJs, 'utf-8');
        expect(table).toMatch(/^\/\/ GENERATED by mion/);
        expect(table).toContain('replaceBatches({');
        const imports = [...table.matchAll(/import \{[^}]+\} from '([^']+)';/g)].map((m) => m[1]);
        expect(imports.length).toBeGreaterThan(0);
        for (const specifier of imports) {
            expect(specifier.startsWith('./')).toBe(true);
            expect(existsSync(resolve(genDir, 'rpc', specifier))).toBe(true);
        }
        expect(table).not.toContain(rootDir);
        expect(table).not.toContain('clientRoot');
        const mappers = readdirSync(resolve(genDir, 'rpc/pf/rt'));
        expect(mappers.length).toBeGreaterThan(0);
        // the mapper body authored in src/client/batchFlow.ts (and in json.spec.ts) is one of them
        expect(mappers.some((file) => readFileSync(resolve(genDir, 'rpc/pf/rt', file), 'utf-8').includes('customerValue.preferenceId'))).toBe(true);
    });

    it('the emitted server imports the table by itself, relativized to the gen dir', () => {
        const content = readFileSync(serverJs, 'utf-8');
        expect(content).not.toContain('rtrpc:');
        expect(content).toContain("import '../../.mion-cli/rpc/batches.generated.js';");
        expect(content).toContain('createMionRouter(');
    });

    it('the emitted client flow carries its batch id and mapper hash', () => {
        const content = readFileSync(flowJs, 'utf-8');
        expect(content).toMatch(/'b_[A-Za-z0-9_-]+'/);
        expect(content).toMatch(/'rt::[A-Za-z0-9_-]+'/);
    });

    it('answers a batch with an inline mapper from the compiled client, under plain node', async () => {
        server = spawn(process.execPath, [serverJs], {
            cwd: rootDir,
            env: {...process.env, MION_TEST_PORT: String(PORT), MION_TEST_SERVER_AUTO_START: 'true'},
            stdio: ['ignore', 'inherit', 'inherit'],
        });
        await waitForPort(PORT, server);
        const flow = (await import(pathToFileURL(flowJs).href)) as {
            runInlineMapperBatch: (baseURL: string) => Promise<{customer: unknown; prefs: unknown; errors: unknown[]}>;
        };
        const result = await flow.runInlineMapperBatch(`http://127.0.0.1:${PORT}`);
        expect(result.errors.filter(Boolean)).toEqual([]);
        expect(result.customer).toEqual({id: 7, name: 'Test Customer', preferenceId: 107});
        expect(result.prefs).toEqual({id: 107, userId: 7, theme: 'light'});
    });
});
