/* ########
 * 2026 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import {describe, it, expect, afterAll} from 'vitest';
import {existsSync, readdirSync, readFileSync, statSync} from 'fs';
import {dirname, relative, resolve} from 'path';
import {pathToFileURL} from 'url';
import {spawn, type ChildProcess} from 'child_process';

// Runs AFTER the two `mion compile` runs of the PUBLISHED binary (scripts/release/e2e.mjs):
//
//   mion compile --tsconfig tsconfig.compile.json --client-tsconfig client-app/tsconfig.json --gen-dir .mion-cli
//   mion compile --cwd client-app --tsconfig tsconfig.json --gen-dir .mion-cli
//
// The server and the client are SEPARATE projects here: the server compile generates the batch
// table and the inline inputFrom mapper modules from the client-app program into .mion-cli/rpc/,
// appends the table's import to the emitted router-init module, and the client compile splices
// the batch id and mapper hash into the emitted flow. The last test boots the emitted server
// under plain node and runs the emitted client flow against it.
//
// tsconfig.compile.json excludes src/tests/ so the server program carries no batch of its own:
// with a client pointer set, one written here never reaches the table and the build says so
// fatally (BAT008).

const rootDir = resolve(__dirname, '../..');
const outDir = resolve(rootDir, 'dist-cli');
const genDir = resolve(rootDir, '.mion-cli');
const serverJs = resolve(outDir, 'src/server/server.js');
// client-app's rootDir is the consumer root (its program reaches the server's types), so its
// out dir mirrors that layout
const flowJs = resolve(rootDir, 'client-app/dist-cli/client-app/src/batchFlow.js');
const tableJs = resolve(genDir, 'rpc/batches.generated.js');
const PORT = 8087;

let server: ChildProcess | undefined;

/** Every file under dir, recursively. */
function filesUnder(dir: string): string[] {
    if (!existsSync(dir)) return [];
    return readdirSync(dir).flatMap((name) => {
        const full = resolve(dir, name);
        return statSync(full).isDirectory() ? filesUnder(full) : [full];
    });
}

const anyFileContains = (dir: string, needle: string): boolean => filesUnder(dir).some((file) => readFileSync(file, 'utf-8').includes(needle));
afterAll(() => server?.kill('SIGTERM'));

async function waitForPort(port: number, child: ChildProcess, timeoutMs = 60000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    let exited = false;
    child.once('exit', () => (exited = true));
    while (Date.now() < deadline) {
        if (exited) throw new Error(`the compiled server exited before accepting connections on ${port}`);
        try {
            await fetch(`http://127.0.0.1:${port}/`);
            return;
        } catch {
            await new Promise((r) => setTimeout(r, 200));
        }
    }
    throw new Error(`the compiled server did not accept connections on ${port} within ${timeoutMs}ms`);
}

describe('mion compile output', () => {
    it('emits the batch transport under the gen dir, relative imports only', () => {
        expect(existsSync(tableJs)).toBe(true);
        const table = readFileSync(tableJs, 'utf-8');
        expect(table).toMatch(/^\/\/ GENERATED by mion/);
        expect(table).toContain('replaceBatches({');
        // two package imports (the registries), then one relative import per mapper module
        const imports = [...table.matchAll(/import \{[^}]+\} from '([^']+)';/g)].map((m) => m[1]);
        const packages = imports.filter((specifier) => !specifier.startsWith('.'));
        const mapperImports = imports.filter((specifier) => specifier.startsWith('.'));
        expect(packages.sort()).toEqual(['@mionjs/core', '@mionjs/router']);
        expect(mapperImports.length).toBeGreaterThan(0);
        for (const specifier of mapperImports) {
            expect(specifier.startsWith('./pf/')).toBe(true);
            expect(existsSync(resolve(genDir, 'rpc', specifier))).toBe(true);
        }
        expect(table).not.toContain(rootDir);
        expect(table).not.toContain('clientRoot');
        // the table comes from the client project alone, and that project holds exactly one batch
        const ids = [...table.matchAll(/"(b_[A-Za-z0-9_-]+)"/g)].map((m) => m[1]);
        expect(ids).toHaveLength(1);
        const mappers = readdirSync(resolve(genDir, 'rpc/pf/rt'));
        expect(mappers).toHaveLength(1);
        // the mapper body authored in client-app/src/batchFlow.ts
        expect(readFileSync(resolve(genDir, 'rpc/pf/rt', mappers[0]), 'utf-8')).toContain('customerValue.preferenceId');
    });

    it('copies the inline mapper and nothing else of the client project', () => {
        // client-app/src/decoys.ts declares a reflection marker and a named pure function of its
        // own; the server pass over the client program must not compile either of them
        expect(anyFileContains(resolve(genDir, 'types'), 'clientOnlyField')).toBe(false);
        expect(anyFileContains(resolve(genDir, 'rpc'), 'clientOnlyHelper')).toBe(false);
        expect(existsSync(resolve(genDir, 'rpc/pf/mionjs'))).toBe(false);
        // the decoys are live: the client's own compile generates both
        const clientGenDir = resolve(rootDir, 'client-app/.mion-cli');
        expect(anyFileContains(resolve(clientGenDir, 'types'), 'clientOnlyField')).toBe(true);
        expect(anyFileContains(resolve(clientGenDir, 'types'), 'clientOnlyHelper')).toBe(true);
    });

    it('the emitted server imports the table by itself, relativized to the gen dir', () => {
        const content = readFileSync(serverJs, 'utf-8');
        expect(content).not.toContain('rtrpc:');
        // dist-cli/src/server/server.js reaches .mion-cli/ three levels up
        const tableImport = relative(dirname(serverJs), tableJs);
        expect(tableImport).toBe('../../../.mion-cli/rpc/batches.generated.js');
        expect(content).toContain(`import '${tableImport}';`);
        expect(content).toContain('createMionRouter(');
    });

    it('the emitted client flow carries the batch id and mapper hash the table registers', () => {
        const content = readFileSync(flowJs, 'utf-8');
        const table = readFileSync(tableJs, 'utf-8');
        const batchId = /'(b_[A-Za-z0-9_-]+)'/.exec(content)?.[1];
        const mapperKey = /'(rt::[A-Za-z0-9_-]+)'/.exec(content)?.[1];
        expect(batchId, content).toBeDefined();
        expect(mapperKey, content).toBeDefined();
        expect(table).toContain(`"${batchId}"`);
        expect(table).toContain(`'${mapperKey}'`);
    });

    it('answers a batch with an inline mapper from the compiled client, under plain node', async () => {
        server = spawn(process.execPath, [serverJs], {
            cwd: rootDir,
            env: {...process.env, MION_TEST_PORT: String(PORT), MION_TEST_SERVER_AUTO_START: 'true'},
            stdio: ['ignore', 'inherit', 'inherit'],
        });
        await waitForPort(PORT, server);
        const flow = (await import(pathToFileURL(flowJs).href)) as {
            runInlineMapperBatch: (baseURL: string) => Promise<{customer: unknown; prefs: unknown; errors: unknown[]}>;
        };
        const result = await flow.runInlineMapperBatch(`http://127.0.0.1:${PORT}`);
        expect(result.errors.filter(Boolean)).toEqual([]);
        expect(result.customer).toEqual({id: 7, name: 'Test Customer', preferenceId: 107});
        expect(result.prefs).toEqual({id: 107, userId: 7, theme: 'light'});
    });
});
