/* ########
 * 2026 mion
 * Author: Ma-jerez
 * License: MIT
 * The software is provided "as is", without warranty of any kind.
 * ######## */

import {describe, expect, it} from 'vitest';
import {createBatchTransportSignals, mionVitePlugin} from './mionVitePlugin.ts';
import type {GenerateInfo} from '../core/unplugin.ts';
import type {Plugin} from 'vite';

// The batch transport is generated by the resolver (the table module plus its mapper modules
// under `<genDir>/rpc/`, the import appended to the router-init modules in the transform), so what
// the vite preset keeps is small: fold the generate echo into the three signals vite needs. This
// spec drives those signals directly; batchesBuild.spec.ts proves a real build over the generated
// tree, and middlewareMode.spec.ts the dev reload.

const info = (batchesModule: string, routerInitFiles: string[] = ['/app/src/server.ts']): GenerateInfo => ({
  outDir: '/app/.mion',
  batchesModule,
  batchSourceFiles: [],
  batchSourceRoots: [],
  routerInitFiles,
});

describe('createBatchTransportSignals — the generate echo, as vite needs it', () => {
  it('reports the module path from the first echo on', () => {
    const invalidated: string[][] = [];
    const signals = createBatchTransportSignals((files) => invalidated.push(files));
    expect(signals.batchesModuleOf()).toBe('');

    signals.onGenerate(info('/app/.mion/rpc/batches.generated.js'));
    expect(signals.batchesModuleOf()).toBe('/app/.mion/rpc/batches.generated.js');
    // the first echo is the buildStart one: the router-init modules are transformed AFTER it,
    // so nothing was loaded without the import and nothing is invalidated
    expect(invalidated).toEqual([]);
  });

  it('re-transforms the router-init modules when the module first appears after they were loaded', () => {
    const invalidated: string[][] = [];
    const signals = createBatchTransportSignals((files) => invalidated.push(files));
    signals.onGenerate(info(''));
    expect(signals.batchesModuleOf()).toBe('');
    // a client adds its first batch while the dev server runs
    signals.onGenerate(info('/app/.mion/rpc/batches.generated.js', ['/app/src/server.ts', '/app/src/admin.ts']));
    expect(invalidated).toEqual([['/app/src/server.ts', '/app/src/admin.ts']]);
    expect(signals.batchesModuleOf()).toBe('/app/.mion/rpc/batches.generated.js');
  });

  it('re-transforms them again when the last batch goes away, and not on a plain rewrite', () => {
    const invalidated: string[][] = [];
    const signals = createBatchTransportSignals((files) => invalidated.push(files));
    signals.onGenerate(info('/app/.mion/rpc/batches.generated.js'));
    // a rewrite of the table is an ordinary change vite sees by itself
    signals.onGenerate(info('/app/.mion/rpc/batches.generated.js'));
    expect(invalidated).toEqual([]);
    // the module vanished: the entry still imports a file that no longer exists
    signals.onGenerate(info(''));
    expect(invalidated).toEqual([['/app/src/server.ts']]);
    expect(signals.batchesModuleOf()).toBe('');
  });

  it('never invalidates on the FIRST echo, module or not — nothing has been transformed yet', () => {
    const withModule: string[][] = [];
    const first = createBatchTransportSignals((files) => withModule.push(files));
    first.onGenerate(info('/app/.mion/rpc/batches.generated.js'));
    expect(withModule).toEqual([]);
    const without: string[][] = [];
    const second = createBatchTransportSignals((files) => without.push(files));
    second.onGenerate(info(''));
    expect(without).toEqual([]);
    expect(second.batchesModuleOf()).toBe('');
  });
});

describe('mionVitePlugin — the batch transport needs no plugin of its own', () => {
  it('registers no batch plugin: generation and injection happen in the resolver', () => {
    const names = (mionVitePlugin({}) as unknown as Plugin[]).flat().map((plugin) => (plugin as Plugin)?.name);
    expect(names.some((name) => /batch/i.test(name ?? ''))).toBe(false);
  });

  it('accepts the client pointer beside the server block', () => {
    expect(() =>
      mionVitePlugin({
        client: {tsConfig: '../client/tsconfig.json'},
        server: {startScript: '/srv.ts'},
      })
    ).not.toThrow();
  });

  it('rejects an empty client pointer, which can only be a config mistake', () => {
    expect(() => mionVitePlugin({client: {tsConfig: ''}})).toThrow(/client\.tsConfig/);
  });
});
