"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.__ΩDataOnly = exports.__ΩJSONString = exports.__ΩJSONValue = exports.__ΩMutable = exports.__ΩDeserializeClassFn = exports.__ΩSerializableClass = exports.__ΩAnyClass = exports.__ΩAnyObject = exports.__ΩSrcCodePureFunctionsCache = exports.__ΩSrcCodeJITCompiledFnsCache = exports.__ΩSrcCodeCompiledPureFunction = exports.__ΩSrcCodeJitCompiledFn = exports.__ΩPureFunctionsCache = exports.__ΩJitFunctionsCache = exports.__ΩToCodeFn = exports.__ΩIsTypeFn = exports.__ΩTypeErrorsFn = exports.__ΩToJsonValFn = exports.__ΩFromJsonValFn = exports.__ΩJsonStringifyFn = exports.__ΩJitFunctionsHashes = exports.__ΩSerializableJITFunctions = exports.__ΩJitCompiledFunctions = exports.__ΩJitCompiledFn = exports.__ΩJitCompiledFnData = exports.__ΩJitFnArgs = exports.__ΩAnyFn = exports.__ΩCompiledPureFunction = exports.__ΩPureFunctionData = exports.__ΩPureFunctionClosure = exports.__ΩPureFunction = exports.__ΩErrorsPureFunction = exports.__ΩGenericPureFunction = exports.__ΩPureFunctionDeps = exports.__ΩTypeFormatParsedParams = exports.__ΩTypeFormatParams = exports.__ΩFormatParam = exports.__ΩFormatParamMeta = exports.__ΩTypeFormatValue = exports.__ΩFormatParamLiteral = exports.__ΩTypeFormatError = exports.__ΩRunTypeError = exports.__ΩAnyErrorParams = exports.__ΩPublicRpcError = exports.__ΩRpcErrorWithPrivate = exports.__ΩRpcErrorWithPublic = exports.__ΩRpcErrorParams = exports.__ΩCoreOptions = exports.__ΩJITUtils = exports.__ΩStrNumber = void 0;
const __ΩInstanceType = ['T', 'args', 'new', 'InstanceType', 'l>e"!R"RPde#!P"@2"h"!/#qk#\'QRb!Pde"!p)w$y'];
const __ΩRecord = ['K', 'T', 'Record', 'l\'e#"Rb!b"Pde"!N#!w#y'];
const __ΩError = ['name', 'message', 'stack', 'Error', 'P&4!&4"&4#8Mw$y'];
const __ΩOmit = ['T', 'K', () => __ΩPick, () => __ΩExclude, 'Omit', 'b!b"e!!e!!ge!"o$#o##w%y'];
const __ΩSharedArrayBuffer = ['byteLength', 'begin', 'end', 0, 'slice', 0, () => Symbol.species, "SharedArrayBuffer", () => Symbol.toStringTag, 'SharedArrayBuffer', 'P\'4!9P\'2"8\'2#8n$1%n&4\'9.(4)9Mw*y'];
const __ΩDataView = [() => __ΩArrayBufferLike, 'TArrayBuffer', 'buffer', 'byteLength', 'byteOffset', 'littleEndian', 'getFloat32', 'getFloat64', 'getInt8', 'getInt16', 'getInt32', 'getUint8', 'getUint16', 'getUint32', 'value', 'setFloat32', 'setFloat64', 'setInt8', 'setInt16', 'setInt32', 'setUint8', 'setUint16', 'setUint32', 'DataView', 'n!c"Pe"!4#9\'4$9\'4%9P\'2%)2&8\'1\'P\'2%)2&8\'1(P\'2%\'1)P\'2%)2&8\'1*P\'2%)2&8\'1+P\'2%\'1,P\'2%)2&8\'1-P\'2%)2&8\'1.P\'2%\'2/)2&8$10P\'2%\'2/)2&8$11P\'2%\'2/$12P\'2%\'2/)2&8$13P\'2%\'2/)2&8$14P\'2%\'2/$15P\'2%\'2/)2&8$16P\'2%\'2/)2&8$17Mw8y'];
const __ΩBigUint64Array = [() => __ΩArrayBufferLike, 'TArrayBuffer', 'BYTES_PER_ELEMENT', 'buffer', 'byteLength', 'byteOffset', 'target', 'start', 'end', 'copyWithin', () => __ΩArrayIterator, 'entries', 'value', 'index', 0, 'array', '', 'predicate', 'thisArg', 'every', 'fill', 0, 0, 'filter', 0, 'find', 0, 'findIndex', 0, 'callbackfn', 'forEach', 'searchElement', 'fromIndex', 'includes', 'indexOf', 'separator', 'join', () => __ΩArrayIterator, 'keys', 'lastIndexOf', 'length', 0, 0, 'map', 'previousValue', 'currentValue', 'currentIndex', 0, 'reduce', 0, 'initialValue', 0, 'reduceRight', 0, 'reverse', () => __ΩArrayLike, 'offset', 'set', 0, 'slice', 0, 'some', 'a', 'b', 'compareFn', 'sort', 'begin', 0, 'subarray', 'locales', 'options', 'toLocaleString', 'toString', 0, 'valueOf', () => __ΩArrayIterator, 'values', () => __ΩArrayIterator, () => Symbol.iterator, "BigUint64Array", () => Symbol.toStringTag, 'BigUint64Array', 'n!c"P\'4#9e"!4$9\'4%9\'4&9P\'2\'\'2(\'2)8!1*PP\'*Go+"1,PP*2-\'2.e$!o/"20)/122"238)14P*2-\'2(8\'2)8!15PP*2-\'2.e$!o6"20"/122"238_o7"18PP*2-\'2.e$!o9"20)/122"238P*-J1:PP*2-\'2.e$!o;"20)/122"238\'1<PP*2-\'2.e$!o="20$/12>"238$1?P*2@\'2A8)1BP*2@\'2A8\'1CP&2D8&1EP\'oF"1GP*2@\'2A8\'1H\'4I9PP*2-\'2.e$!oJ"20*/12>"238_oK"1LPP*2M*2N\'2Oe$!oP"20*/12>*1QPP"2M*2N\'2Oe$!oR"20"/12>"2S"1QPP*2M*2N\'2Oe$!oT"20*/12>*1UPP"2M*2N\'2Oe$!oV"20"/12>"2S"1UP!1WP*oX"20\'2Y8$1ZP\'2(8\'2)8_o["1\\PP*2-\'2.e$!o]"20)/122"238)1^PP*2_*2`P\'*J/12a8!1bP\'2c8\'2)8e#!od"1ePP&&FJ2f8!2g8&1hP&1iPe#!oj"1kP*ol"1mP*on"1o.p4q9\'*LMwry'];
const __ΩPick = ['T', 'K', 'Pick', 'l+e#!e"!fRb!b"Pde""N#!w#y'];
const __ΩExclude = ['T', 'U', 'Exclude', 'l6!Re$!RPe#!e$"qk#%QRb!b"Pde"!p)w#y'];
const __ΩArrayBufferLike = [() => __ΩArrayBufferTypes, () => __ΩArrayBufferTypes, 'ArrayBufferLike', 'n!n"gfw#y'];
const __ΩArrayIterator = ['T', () => __ΩIteratorObject, () => __ΩBuiltinIteratorReturn, 0, () => Symbol.iterator, 'ArrayIterator', 'b!Pe"!n##o"$Pe#!o$"1%Mw&y'];
const __ΩArrayLike = ['T', 'length', 'ArrayLike', 'b!P\'4"9\'e"!LMw#y'];
const __ΩArrayBufferTypes = ['ArrayBuffer', 'ArrayBufferTypes', 'P_4!Mw"y'];
const __ΩIteratorObject = ['T', 'TReturn', 'TNext', () => __ΩIterator, 0, () => Symbol.iterator, 'IteratorObject', 'b!#c"#c#Pe"!e""e"#o$$Pe#!e#"e##o%$1&Mw\'y'];
const __ΩBuiltinIteratorReturn = ['BuiltinIteratorReturn', '!w!y'];
const __ΩIterator = ['T', 'TReturn', 'TNext', 'param0', () => __ΩIteratorResult, 'next', 'value', () => __ΩIteratorResult, 'return', 'e', () => __ΩIteratorResult, 'throw', 'Iterator', 'b!"c""c#PPPPGPe%#GJ@2$e#!e#"o%#1&Pe#"2\'8e#!e#"o(#1)P"2*8e#!e#"o+#1,Mw-y'];
const __ΩIteratorResult = ['T', 'TReturn', () => __ΩIteratorYieldResult, () => __ΩIteratorReturnResult, 'IteratorResult', 'b!"c"Pe"!o#"e""o$"Jw%y'];
const __ΩIteratorYieldResult = ['TYield', false, 'done', 'value', 'IteratorYieldResult', 'b!P."4#8e"!4$Mw%y'];
const __ΩIteratorReturnResult = ['TReturn', true, 'done', 'value', 'IteratorReturnResult', 'b!P."4#e"!4$Mw%y'];
const __ΩStrNumber = ['StrNumber', 'P&\'Jw!y'];
exports.__ΩStrNumber = __ΩStrNumber;
const __ΩJITUtils = ['str', 'asJSONString', () => __ΩJitCompiledFn, 'comp', 'addToJitCache', () => __ΩJitCompiledFn, 'removeFromJitCache', 'jitFnHash', () => __ΩJitCompiledFn, 'getJIT', 'args', '', 'getJitFn', 'hasJitFn', () => __ΩCompiledPureFunction, 'compiledFn', 'addPureFn', 'name', () => __ΩPureFunction, 'usePureFn', () => __ΩPureFunction, 'getPureFn', () => __ΩCompiledPureFunction, 'getCompiledPureFn', 'hasPureFn', 'cls', 'setSerializableClass', 'className', () => __ΩSerializableClass, 'useSerializeClass', () => __ΩSerializableClass, 'getSerializeClass', () => __ΩDeserializeClassFn, () => __ΩInstanceType, 'deserializeFn', 'setDeserializeFn', () => __ΩDeserializeClassFn, 'useDeserializeFn', () => __ΩDeserializeClassFn, 'getDeserializeFn', () => __ΩRecord, () => __ΩStrNumber, 'obj', () => __ΩStrNumber, 'keys', () => __ΩStrNumber, 'getUnknownKeysFromArray', () => __ΩRecord, () => __ΩStrNumber, () => __ΩStrNumber, 'hasUnknownKeysFromArray', () => __ΩStrNumber, 'p\u03BBth', () => __ΩRunTypeError, '\u03B5rr', 'expected', () => __ΩStrNumber, 'accessPath', 'err', () => __ΩStrNumber, () => __ΩRunTypeError, 'fmtName', 'paramName', 'paramVal', () => __ΩStrNumber, 'fmtPath', () => __ΩStrNumber, () => __ΩStrNumber, 'fmtAccessPath', 'formatErr', 'value', 'safeKey', 'JITUtils', 'PP&2!&1"Pn#2$$1%Pn&2$$1\'P&2(Pn)-J1*P&2(P"@2+"/,1-P&2()1.Pn/20$11P&22n314P&22Pn5-J16P&22Pn7-J18P&22)19P"2:$1;P&2<n=1>P&2<Pn?-J1@P"2:"oB"oA"2C$1DP&2<"oE"1FP&2<P"oG"-J1HPnJ"oI#2KnLF2MnNF1OPnQ"oP#2KnRF2M)1SPnTF92UnVF2W&2XnYF92Z8$1[Pn\\F2Un]F2W&2X&2^&2_P&\')*J2`naF2bncF2Z8ndF2e8$1fP"2g"1hMwiy'];
exports.__ΩJITUtils = __ΩJITUtils;
const __ΩCoreOptions = ['autoGenerateErrorId', 'CoreOptions', 'P)4!Mw"y'];
exports.__ΩCoreOptions = __ΩCoreOptions;
const __ΩRpcErrorParams = ['ErrType', 'ErrData', 'type', 'id', 'statusCode', 'publicMessage', 'message', 'errorData', () => __ΩError, 'originalError', 'name', 'RpcErrorParams', '"c!"c"Pe"!4#8P\'&J4$8\'4%&4&8&4\'8e""4(8n)4*8&4+8Mw,y'];
exports.__ΩRpcErrorParams = __ΩRpcErrorParams;
const __ΩRpcErrorWithPublic = ['ErrType', 'ErrData', () => __ΩRpcErrorParams, 'publicMessage', 'RpcErrorWithPublic', '"c!"c"Pe"!e""o##&4$Mw%y'];
exports.__ΩRpcErrorWithPublic = __ΩRpcErrorWithPublic;
const __ΩRpcErrorWithPrivate = ['ErrType', 'ErrData', () => __ΩRpcErrorParams, 'message', 'RpcErrorWithPrivate', '"c!"c"Pe"!e""o##&4$Mw%y'];
exports.__ΩRpcErrorWithPrivate = __ΩRpcErrorWithPrivate;
const __ΩPublicRpcError = ['ErrType', 'ErrData', () => __ΩOmit, () => __ΩRpcErrorParams, "publicMessage", "originalError", true, 'is\u03A3rr\u03B8r', 'type', 'message', 'statusCode', 'name', 'errorData', 'PublicRpcError', '"c!"c"Pn$P.%.&Jo##.\'4(e"!4)&4*\'4+&4,e""4-8Mw.y'];
exports.__ΩPublicRpcError = __ΩPublicRpcError;
const __ΩAnyErrorParams = ['ErrType', 'ErrData', () => __ΩRpcErrorWithPublic, () => __ΩRpcErrorWithPrivate, 'AnyErrorParams', '"c!"c"Pe"!e""o##e"!e""o$#Jw%y'];
exports.__ΩAnyErrorParams = __ΩAnyErrorParams;
const __ΩRunTypeError = [() => __ΩStrNumber, 'path', 'expected', () => __ΩTypeFormatError, 'format', 'RunTypeError', 'Pn!F4"&4#n$4%8Mw&y'];
exports.__ΩRunTypeError = __ΩRunTypeError;
const __ΩTypeFormatError = ['name', () => __ΩStrNumber, () => __ΩStrNumber, 'val', () => __ΩStrNumber, 'formatPath', 'TypeFormatError', 'P&4!Pn")*Pn#)*JFJ4$n%F4&Mw\'y'];
exports.__ΩTypeFormatError = __ΩTypeFormatError;
const __ΩFormatParamLiteral = ['FormatParamLiteral', 'P&\')A*Jw!y'];
exports.__ΩFormatParamLiteral = __ΩFormatParamLiteral;
const __ΩTypeFormatValue = [() => __ΩFormatParamLiteral, 0, 0, 'TypeFormatValue', 'Pn!n"F9P&Pn#-!JLMJw$y'];
exports.__ΩTypeFormatValue = __ΩTypeFormatValue;
const __ΩFormatParamMeta = [() => __ΩTypeFormatValue, 'L', 'val', 'errorMessage', 'desc', 'FormatParamMeta', 'n!c"Pe"!4#&4$&4%8Mw&y'];
exports.__ΩFormatParamMeta = __ΩFormatParamMeta;
const __ΩFormatParam = ['L', () => __ΩFormatParamMeta, 'FormatParam', 'b!Pe"!e"!o""Jw#y'];
exports.__ΩFormatParam = __ΩFormatParam;
const __ΩTypeFormatParams = [() => __ΩRecord, () => __ΩTypeFormatValue, 'TypeFormatParams', '&Pn"-!Jo!#w#y'];
exports.__ΩTypeFormatParams = __ΩTypeFormatParams;
const __ΩTypeFormatParsedParams = ['__jitId', () => __ΩTypeFormatValue, 'TypeFormatParsedParams', 'P&4!&n"LMw#y'];
exports.__ΩTypeFormatParsedParams = __ΩTypeFormatParsedParams;
const __ΩPureFunctionDeps = [() => __ΩRecord, () => __ΩPureFunction, 'PureFunctionDeps', '&n"o!#w#y'];
exports.__ΩPureFunctionDeps = __ΩPureFunctionDeps;
const __ΩGenericPureFunction = ['P', 'val', 'formatParams', () => __ΩPureFunctionDeps, 'deps', '', 'GenericPureFunction', 'b!P"2"e"!2#n$2%"/&w\'y'];
exports.__ΩGenericPureFunction = __ΩGenericPureFunction;
const __ΩErrorsPureFunction = ['P', 'val', () => __ΩStrNumber, 'p\u03BBth', () => __ΩRunTypeError, '\u03B5rr', 'expected', 'formatName', 'formatParams', () => __ΩStrNumber, 'formatPath', () => __ΩPureFunctionDeps, 'deps', () => __ΩStrNumber, 'accessPath', () => __ΩStrNumber, 'fmtAccessPath', () => __ΩRunTypeError, '', 'ErrorsPureFunction', 'b!P"2"n#F2$n%F2&&2\'&2(e"!2)n*F2+n,2-n.F2/8n0F218n2F/3w4y'];
exports.__ΩErrorsPureFunction = __ΩErrorsPureFunction;
const __ΩPureFunction = ['args', '', 'PureFunction', 'P"@2!"/"w#y'];
exports.__ΩPureFunction = __ΩPureFunction;
const __ΩPureFunctionClosure = [() => __ΩJITUtils, 'jitUtils', () => __ΩPureFunction, '', 'PureFunctionClosure', 'Pn!2"n#/$w%y'];
exports.__ΩPureFunctionClosure = __ΩPureFunctionClosure;
const __ΩPureFunctionData = ['paramNames', 'code', 'pureFnHash', 'dependencies', 'PureFunctionData', 'P&F4!9&4"9&4#9&D4$9Mw%y'];
exports.__ΩPureFunctionData = __ΩPureFunctionData;
const __ΩCompiledPureFunction = [() => __ΩPureFunctionData, () => __ΩPureFunctionClosure, 'closureFn', () => __ΩPureFunction, 'fn', 'CompiledPureFunction', 'Pn!n"4#n$4%8Mw&y'];
exports.__ΩCompiledPureFunction = __ΩCompiledPureFunction;
const __ΩAnyFn = ['args', '', 'AnyFn', 'P"@2!"/"w#y'];
exports.__ΩAnyFn = __ΩAnyFn;
const __ΩJitFnArgs = ['v\u03BBl', 'JitFnArgs', 'P&4!&&LMw"y'];
exports.__ΩJitFnArgs = __ΩJitFnArgs;
const __ΩJitCompiledFnData = ['typeName', 'fnID', 'jitFnHash', () => __ΩJitFnArgs, 'args', () => __ΩJitFnArgs, 'defaultParamValues', 'isNoop', 'code', 'dependenciesSet', 'pureFnDependencies', 'paramNames', 'JitCompiledFnData', 'P&4!9&4"9&4#9n$4%9n&4\'9)4(89&4)9&D4*9&D4+9&F4,8Mw-y'];
exports.__ΩJitCompiledFnData = __ΩJitCompiledFnData;
const __ΩJitCompiledFn = [() => __ΩAnyFn, 'Fn', () => __ΩJitCompiledFnData, () => __ΩJITUtils, 'utl', '', 'closureFn', 'fn', 'JitCompiledFn', 'n!c"Pn#Pn$2%e#!/&4\'9e"!4(9Mw)y'];
exports.__ΩJitCompiledFn = __ΩJitCompiledFn;
const __ΩJitCompiledFunctions = [() => __ΩJitCompiledFn, () => __ΩIsTypeFn, 'isType', () => __ΩJitCompiledFn, () => __ΩTypeErrorsFn, 'typeErrors', () => __ΩJitCompiledFn, () => __ΩToJsonValFn, 'toJsonVal', () => __ΩJitCompiledFn, () => __ΩFromJsonValFn, 'fromJsonVal', () => __ΩJitCompiledFn, () => __ΩJsonStringifyFn, 'jsonStringify', 'JitCompiledFunctions', 'Pn"o!"4#n%o$"4&n(o\'"4)n+o*"4,n.o-"4/Mw0y'];
exports.__ΩJitCompiledFunctions = __ΩJitCompiledFunctions;
const __ΩSerializableJITFunctions = [() => __ΩJitCompiledFnData, 'isType', () => __ΩJitCompiledFnData, 'typeErrors', () => __ΩJitCompiledFnData, 'toJsonVal', () => __ΩJitCompiledFnData, 'fromJsonVal', () => __ΩJitCompiledFnData, 'jsonStringify', 'SerializableJITFunctions', 'Pn!4"n#4$n%4&n\'4(n)4*Mw+y'];
exports.__ΩSerializableJITFunctions = __ΩSerializableJITFunctions;
const __ΩJitFunctionsHashes = ['isType', 'typeErrors', 'toJsonVal', 'fromJsonVal', 'jsonStringify', 'JitFunctionsHashes', 'P&4!&4"&4#&4$&4%Mw&y'];
exports.__ΩJitFunctionsHashes = __ΩJitFunctionsHashes;
const __ΩJsonStringifyFn = ['value', () => __ΩJSONString, '', 'JsonStringifyFn', 'P"2!n"/#w$y'];
exports.__ΩJsonStringifyFn = __ΩJsonStringifyFn;
const __ΩFromJsonValFn = [() => __ΩJSONValue, 'value', '', 'FromJsonValFn', 'Pn!2""/#w$y'];
exports.__ΩFromJsonValFn = __ΩFromJsonValFn;
const __ΩToJsonValFn = ['value', () => __ΩJSONValue, '', 'ToJsonValFn', 'P"2!n"/#w$y'];
exports.__ΩToJsonValFn = __ΩToJsonValFn;
const __ΩTypeErrorsFn = ['value', () => __ΩRunTypeError, '', 'TypeErrorsFn', 'P"2!n"F/#w$y'];
exports.__ΩTypeErrorsFn = __ΩTypeErrorsFn;
const __ΩIsTypeFn = ['value', '', 'IsTypeFn', 'P"2!)/"w#y'];
exports.__ΩIsTypeFn = __ΩIsTypeFn;
const __ΩToCodeFn = ['value', '', 'ToCodeFn', 'P"2!&/"w#y'];
exports.__ΩToCodeFn = __ΩToCodeFn;
const __ΩJitFunctionsCache = [() => __ΩRecord, () => __ΩJitCompiledFn, 'JitFunctionsCache', '&n"o!#w#y'];
exports.__ΩJitFunctionsCache = __ΩJitFunctionsCache;
const __ΩPureFunctionsCache = [() => __ΩRecord, () => __ΩCompiledPureFunction, 'PureFunctionsCache', '&n"o!#w#y'];
exports.__ΩPureFunctionsCache = __ΩPureFunctionsCache;
const __ΩSrcCodeJitCompiledFn = [() => __ΩJitCompiledFnData, () => __ΩJITUtils, 'utl', () => __ΩAnyFn, '', 'closureFn', 'fn', 'SrcCodeJitCompiledFn', 'Pn!Pn"2#n$/%4&9-4\'9Mw(y'];
exports.__ΩSrcCodeJitCompiledFn = __ΩSrcCodeJitCompiledFn;
const __ΩSrcCodeCompiledPureFunction = [() => __ΩPureFunctionData, () => __ΩJITUtils, 'utl', () => __ΩAnyFn, '', 'closureFn', 'fn', 'SrcCodeCompiledPureFunction', 'Pn!Pn"2#n$/%4&9-4\'9Mw(y'];
exports.__ΩSrcCodeCompiledPureFunction = __ΩSrcCodeCompiledPureFunction;
const __ΩSrcCodeJITCompiledFnsCache = [() => __ΩRecord, () => __ΩSrcCodeJitCompiledFn, 'SrcCodeJITCompiledFnsCache', '&n"o!#w#y'];
exports.__ΩSrcCodeJITCompiledFnsCache = __ΩSrcCodeJITCompiledFnsCache;
const __ΩSrcCodePureFunctionsCache = [() => __ΩRecord, () => __ΩSrcCodeCompiledPureFunction, 'SrcCodePureFunctionsCache', '&n"o!#w#y'];
exports.__ΩSrcCodePureFunctionsCache = __ΩSrcCodePureFunctionsCache;
const __ΩAnyObject = [() => __ΩRecord, 'AnyObject', '&#o!#w"y'];
exports.__ΩAnyObject = __ΩAnyObject;
const __ΩAnyClass = ['T', 'args', 'new', 'AnyClass', '"c!PP"@2"e#!1#Mw$y'];
exports.__ΩAnyClass = __ΩAnyClass;
const __ΩSerializableClass = ['T', 'new', 'SerializableClass', '"c!PPe#!1"Mw#y'];
exports.__ΩSerializableClass = __ΩSerializableClass;
const __ΩDeserializeClassFn = ['C', () => __ΩDataOnly, 'deserialized', '', 'DeserializeClassFn', 'b!Pe"!o""2#e"!/$w%y'];
exports.__ΩDeserializeClassFn = __ΩDeserializeClassFn;
const __ΩMutable = ['T', 'Mutable', 'l+e#!e"!fRb!Pde"!gN#)w"y'];
exports.__ΩMutable = __ΩMutable;
const __ΩJSONValue = [() => __ΩStrNumber, 0, 0, 'JSONValue', 'Pn!),P&n"LMn#FJw$y'];
exports.__ΩJSONValue = __ΩJSONValue;
const __ΩJSONString = ['JSONString', '&w!y'];
exports.__ΩJSONString = __ΩJSONString;
const __ΩNative = [() => __ΩSharedArrayBuffer, () => __ΩDataView, () => __ΩBigUint64Array, 'Native', 'PTA!!!!!!_n!n"UWVXYZ[\\]^n#Jw$y'];
const __ΩDataOnly = ['T', () => __ΩNative, () => Function, 'args', 'new', 0, 0, 0, 0, 0, () => Function, 'DataOnly', 'l\u0110e$!R!R!Re"!o&"FRe"!o\'"e""o("ERe*!o)"DR!Re%!RPe\'!e#!fo*"Pe(!e$!fPu+qkIKQGRPde%!gtO!RPe#!h)!DqkAlQRPde%!pvRPdde#!h!!h!"Eqk3\u0084QRPde%!p\u008CRPde#!h!!Fqk+\u009FQRPde%!p\u00A7RPe#!P"@2$"/%qk)\u00B6QRPde%!p\u00BERPe#!Pu#qk\'\u00D0QRPde%!p\u00D8RPe#!n"qk#\u00E5QRPde%!p\u00EDRe$!RPe#!%qk\u00F9\u0101QRb!Pde"!p\u0105w,y'];
exports.__ΩDataOnly = __ΩDataOnly;
//# sourceMappingURL=types.js.map