// The batch transport end to end, on the real separate-project pair: @mionjs/client
// is the client, @mionjs/test-server is the server. Both lanes build the pair and run
// it under plain node against the built dists, which `pnpm run test:batch-e2e` builds
// BEFORE vitest starts (see globalSetup.ts); without them the suite skips itself.
// Every build here uses its own gen dir (`.mion-e2e`, `.dist/e2e-cli/.mion`), never a
// package's live one, so a concurrent test project's modules are never pruned.
//
//   vite lane   test-server's lib build (the real preset, `client.tsConfig` naming the
//               client package) + a vite build of the client fixture; the SERVER gen dir
//               holds rpc/ with every mapper the client suite declares, and the emitted
//               tree carries the table and the mappers beside the server module.
//   CLI lane    `mion compile` on both packages, `--client-tsconfig` on the server; the
//               same rpc/ tree lands under the CLI gen dir, the emitted router-init module
//               ends with the relativized table import, the emitted client carries its ids.
//
// Then, in each lane, a batch with an inline mapper round-trips against the server that
// lane built, and the two rpc/ trees are byte-identical.
import {afterAll, beforeAll, describe, expect, it} from 'vitest';
import {execFileSync, spawn, type ChildProcess} from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import {pathToFileURL, fileURLToPath} from 'node:url';
import {build} from 'vite';
import {mionVitePlugin} from '../../src/vite/index.ts';
import {missingDists} from './globalSetup.ts';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../..');
const BIN = path.join(REPO_ROOT, 'mion-bin', 'mion');
const CLIENT_DIR = path.join(REPO_ROOT, 'packages', 'client');
const SERVER_DIR = path.join(REPO_ROOT, 'packages', 'test-server');
const CLIENT_TSCONFIG = path.join(CLIENT_DIR, 'tsconfig.json');
// the mapper body the fixture (and the client suite) authors in client code
const MAPPER_BODY = 'customerValue.preferenceId';
// what the test server answers for customer 7 (see packages/test-server/src/test-server.ts)
const EXPECTED_PREFS = {id: 107, userId: 7, theme: 'light', lang: 'en'};

interface RpcTree {
  files: Record<string, string>;
  ids: string[];
  mapperKeys: string[];
}

/** Reads `<genDir>/rpc/` and checks the invariants every lane must hold. */
function expectRpcTree(genDir: string): RpcTree {
  const rpcDir = path.join(genDir, 'rpc');
  const table = fs.readFileSync(path.join(rpcDir, 'batches.generated.js'), 'utf8');
  expect(table).toMatch(/^\/\/ GENERATED by mion/);
  const files: Record<string, string> = {};
  const walk = (dir: string): void => {
    for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else files[path.relative(rpcDir, full).split(path.sep).join('/')] = fs.readFileSync(full, 'utf8');
    }
  };
  walk(rpcDir);
  // every import is a package (the registrars) or relative, and the relative ones resolve inside rpc/
  const imports = [...table.matchAll(/import \{[^}]+\} from '([^']+)';/g)].map((match) => match[1]);
  const mapperImports = imports.filter((specifier) => !specifier.startsWith('@mionjs/'));
  expect(mapperImports.length).toBeGreaterThan(0);
  for (const specifier of mapperImports) {
    expect(specifier.startsWith('./'), specifier).toBe(true);
    expect(files[specifier.slice(2)], `${specifier} must exist under rpc/`).toBeDefined();
  }
  for (const content of Object.values(files)) {
    expect(content).not.toContain(REPO_ROOT);
    expect(content).not.toContain('clientRoot');
  }
  const ids = [...table.matchAll(/"(b_[A-Za-z0-9_-]+)"/g)].map((match) => match[1]);
  const mapperKeys = [...table.matchAll(/registerInputMapperTuple\('(rt::[A-Za-z0-9_-]+)'/g)].map((match) => match[1]);
  expect(ids.length).toBeGreaterThan(0);
  expect(mapperKeys.length).toBeGreaterThan(0);
  // the fixture's mapper (and the client suite's, same body) is one of the copied modules
  expect(Object.values(files).some((content) => content.includes(MAPPER_BODY))).toBe(true);
  return {files, ids, mapperKeys};
}

async function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const probe = net.createServer();
    probe.listen(0, '127.0.0.1', () => {
      const port = (probe.address() as net.AddressInfo).port;
      probe.close(() => resolve(port));
    });
    probe.on('error', reject);
  });
}

async function waitForPort(port: number, child: ChildProcess, timeoutMs = 60_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  let exited = false;
  child.once('exit', () => (exited = true));
  while (Date.now() < deadline) {
    if (exited) throw new Error(`the server exited before accepting connections on ${port}`);
    try {
      await fetch(`http://127.0.0.1:${port}/`);
      return;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 200));
    }
  }
  throw new Error(`the server did not accept connections on ${port} within ${timeoutMs}ms`);
}

/** Starts an emitted server under plain node and returns its base URL plus a stop function. */
async function startServer(entry: string): Promise<{baseURL: string; stop: () => void}> {
  const port = await freePort();
  const child = spawn(process.execPath, [entry], {
    cwd: SERVER_DIR,
    env: {...process.env, MION_TEST_PORT: String(port), MION_TEST_SERVER_AUTO_START: 'true'},
    stdio: ['ignore', 'inherit', 'inherit'],
  });
  await waitForPort(port, child);
  return {baseURL: `http://127.0.0.1:${port}`, stop: () => child.kill('SIGTERM')};
}

/** Imports a compiled fixture and runs its batch against a server. */
async function runFixture(fixture: string, baseURL: string): Promise<void> {
  const mod = (await import(pathToFileURL(fixture).href)) as {
    runBatch: (baseURL: string) => Promise<{customer: unknown; prefs: unknown; errors: unknown[]}>;
  };
  const result = await mod.runBatch(baseURL);
  expect(result.errors.filter(Boolean)).toEqual([]);
  expect(result.customer).toMatchObject({id: 7, preferenceId: 107});
  expect(result.prefs).toEqual(EXPECTED_PREFS);
}

const stripRegions = (code: string): string => code.replace(/^\/\/#(end)?region.*$/gm, '');

const distsMissing = missingDists();

describe.skipIf(distsMissing.length > 0)('batch transport end to end: @mionjs/client → @mionjs/test-server', () => {
  const stops: (() => void)[] = [];
  // the vite lane's own gen dir and out dir (never the package's live `.mion`)
  const viteGenDir = path.join(SERVER_DIR, '.mion-e2e');
  const viteOut = path.join(SERVER_DIR, '.dist', 'e2e-vite');
  const cliOut = '.dist/e2e-cli';
  const serverCliDir = path.join(SERVER_DIR, cliOut);
  const clientCliDir = path.join(CLIENT_DIR, cliOut);
  const serverCliTsconfig = path.join(SERVER_DIR, 'tsconfig.e2e-cli.json');
  const clientCliTsconfig = path.join(CLIENT_DIR, 'tsconfig.e2e-cli.json');
  let viteTree: RpcTree;
  let cliTree: RpcTree;

  beforeAll(() => {
    fs.rmSync(serverCliDir, {recursive: true, force: true});
    fs.rmSync(clientCliDir, {recursive: true, force: true});
    fs.rmSync(viteGenDir, {recursive: true, force: true});
    fs.rmSync(path.join(CLIENT_DIR, '.mion-e2e'), {recursive: true, force: true});
  });

  afterAll(() => {
    for (const stop of stops) stop();
    fs.rmSync(serverCliTsconfig, {force: true});
    fs.rmSync(clientCliTsconfig, {force: true});
  });

  describe('vite lane', () => {
    it('the server build generates rpc/ from the client package and emits it beside the artifact', async () => {
      // packages/test-server's lib build, as its vite.config.ts declares it, with the gen dir and
      // the out dir moved under this suite so nothing of the package's live tree is touched
      await build({
        root: SERVER_DIR,
        configFile: false,
        logLevel: 'silent',
        plugins: mionVitePlugin({
          runTypes: {tsConfig: path.join(SERVER_DIR, 'tsconfig.build.json'), binary: BIN, genDir: viteGenDir},
          client: {tsConfig: CLIENT_TSCONFIG},
        }),
        resolve: {conditions: ['source']},
        ssr: {resolve: {conditions: ['source']}},
        build: {
          lib: {entry: {'src/test-server-json': path.join(SERVER_DIR, 'src', 'test-server.ts')}, formats: ['es']},
          outDir: viteOut,
          emptyOutDir: true,
          minify: false,
          rollupOptions: {
            output: {format: 'es', entryFileNames: '[name].js', preserveModules: true, preserveModulesRoot: SERVER_DIR},
            external: ['@mionjs/core', '@mionjs/router', '@mionjs/platform-node', /^[^./]/],
          },
        },
      });
      viteTree = expectRpcTree(viteGenDir);
      // the build preserves modules, so the table and the mappers are emitted as their own files
      // under the out dir and the server module imports the table by a relative path: the emitted
      // tree is self-contained, nothing points back at a source tree
      const artifact = fs.readFileSync(path.join(viteOut, 'src', 'test-server-json.js'), 'utf8');
      expect(artifact).toContain('import "../.mion-e2e/rpc/batches.generated.js";');
      expect(artifact).not.toContain('node:fs');
      expect(artifact).not.toContain('rtrpc:');
      expect(stripRegions(artifact)).not.toContain(REPO_ROOT);
      const table = fs.readFileSync(path.join(viteOut, '.mion-e2e', 'rpc', 'batches.generated.js'), 'utf8');
      expect(table).toContain('registerInputMapperTuple');
      expect(table).toContain('replaceBatches');
      expect(stripRegions(table)).not.toContain(REPO_ROOT);
      for (const id of viteTree.ids) expect(table).toContain(`"${id}"`);
      const mappers = fs.readdirSync(path.join(viteOut, '.mion-e2e', 'rpc', 'pf', 'rt')).filter((file) => file.endsWith('.js'));
      expect(mappers.length).toBe(viteTree.mapperKeys.length);
      expect(
        mappers.some((file) =>
          fs.readFileSync(path.join(viteOut, '.mion-e2e', 'rpc', 'pf', 'rt', file), 'utf8').includes(MAPPER_BODY)
        )
      ).toBe(true);
    });

    it('a batch with an inline mapper round-trips against the built server', async () => {
      const outDir = path.join(CLIENT_DIR, '.dist', 'e2e-vite');
      await build({
        root: CLIENT_DIR,
        configFile: false,
        logLevel: 'silent',
        resolve: {conditions: ['source']},
        plugins: mionVitePlugin({runTypes: {tsConfig: CLIENT_TSCONFIG, binary: BIN, genDir: path.join(CLIENT_DIR, '.mion-e2e')}}),
        build: {
          outDir,
          emptyOutDir: true,
          minify: false,
          lib: {entry: path.join(CLIENT_DIR, 'e2e', 'batchClient.fixture.ts'), formats: ['es'], fileName: 'fixture'},
          rollupOptions: {external: [/^@mionjs\//, /^[^./]/]},
        },
      });
      const fixture = path.join(outDir, 'fixture.js');
      const compiled = fs.readFileSync(fixture, 'utf8');
      // the bundler picks the quote style; the ids are what matters
      expect(compiled).toMatch(/["']b_[A-Za-z0-9_-]+["']/);
      expect(compiled).toMatch(/["']rt::[A-Za-z0-9_-]+["']/);
      const server = await startServer(path.join(viteOut, 'src', 'test-server-json.js'));
      stops.push(server.stop);
      await runFixture(fixture, server.baseURL);
    });
  });

  describe('CLI lane (mion compile)', () => {
    it('the server compile emits rpc/ from --client-tsconfig and the relativized table import', () => {
      fs.writeFileSync(
        serverCliTsconfig,
        JSON.stringify(
          {
            extends: './tsconfig.build.json',
            compilerOptions: {
              outDir: cliOut,
              composite: false,
              declaration: false,
              declarationMap: false,
              sourceMap: false,
              incremental: false,
            },
          },
          null,
          2
        )
      );
      execFileSync(
        BIN,
        [
          'compile',
          '--cwd',
          SERVER_DIR,
          '--tsconfig',
          'tsconfig.e2e-cli.json',
          '--client-tsconfig',
          CLIENT_TSCONFIG,
          '--gen-dir',
          path.join(serverCliDir, '.mion'),
        ],
        {stdio: 'inherit'}
      );
      cliTree = expectRpcTree(path.join(serverCliDir, '.mion'));
      const emitted = fs.readFileSync(path.join(serverCliDir, 'src', 'test-server.js'), 'utf8');
      expect(emitted).not.toContain('rtrpc:');
      expect(emitted).toContain("import '../.mion/rpc/batches.generated.js';");
    });

    it('the client compile carries its ids, and the batch round-trips against the compiled server', async () => {
      fs.writeFileSync(
        clientCliTsconfig,
        JSON.stringify(
          {
            extends: './tsconfig.json',
            compilerOptions: {
              outDir: cliOut,
              composite: false,
              declaration: false,
              declarationMap: false,
              sourceMap: false,
              incremental: false,
            },
          },
          null,
          2
        )
      );
      execFileSync(
        BIN,
        ['compile', '--cwd', CLIENT_DIR, '--tsconfig', 'tsconfig.e2e-cli.json', '--gen-dir', path.join(clientCliDir, '.mion')],
        {
          stdio: 'inherit',
        }
      );
      const fixture = path.join(clientCliDir, 'e2e', 'batchClient.fixture.js');
      const compiled = fs.readFileSync(fixture, 'utf8');
      // the bundler picks the quote style; the ids are what matters
      expect(compiled).toMatch(/["']b_[A-Za-z0-9_-]+["']/);
      expect(compiled).toMatch(/["']rt::[A-Za-z0-9_-]+["']/);
      // (the client package's own suite hosts a router for its middleware tests, so its program
      // legitimately generates a table of its own; the client-only case is pinned by the Go tests)
      const server = await startServer(path.join(serverCliDir, 'src', 'test-server.js'));
      stops.push(server.stop);
      await runFixture(fixture, server.baseURL);
    });
  });

  it('both lanes generate the same rpc/ tree, byte for byte', () => {
    expect(Object.keys(cliTree.files).sort()).toEqual(Object.keys(viteTree.files).sort());
    for (const [file, content] of Object.entries(viteTree.files)) expect(cliTree.files[file], file).toBe(content);
    expect(cliTree.ids).toEqual(viteTree.ids);
    expect(cliTree.mapperKeys).toEqual(viteTree.mapperKeys);
  });
});
