// `miondevx card export <name…> | --all`: hands finished cards to the website. Per card the HTML fragment; for all
// cards the stylesheet, the fonts and the player; plus the manifest check-tree uses to catch a stale export.

import {copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {basename, dirname, join, relative} from 'node:path';
import {pathToFileURL} from 'node:url';
import {parseArgs} from 'node:util';
import {CARD_MANIFEST, CARDS_EXPORT_DIR, hashSources} from '../../../scripts/lib/card-manifest.mjs';
import {CARDS_DIR, COMPONENTS_DIR, PACKAGE_DIR, REPO_DIR, resolveCardPath} from './card.ts';
import {FONTS, cardCss, closeRenderer, fontFaces, renderFragment} from './render.ts';

export const EXPORT_USAGE = 'usage: miondevx card export <name…> | --all';
const WEBSITE = join(REPO_DIR, 'container/website');
export const FONT_URL = '/fonts/code-card';
const GENERATED = 'generated by `pnpm miondevx card export` from tools/code-card/, never edit by hand';

export function parseExportArgs(argv: string[]): {all: boolean; cards: string[]} {
  const {values, positionals} = parseArgs({args: argv, allowPositionals: true, options: {all: {type: 'boolean'}}});
  if (values.all && positionals.length) throw new Error(`pass card names or --all, not both. ${EXPORT_USAGE}`);
  if (!values.all && !positionals.length) throw new Error(EXPORT_USAGE);
  return {all: Boolean(values.all), cards: positionals};
}

const repoPath = (path: string) => relative(REPO_DIR, path).split('\\').join('/');

/** Every file a card's HTML depends on: the card, the local files it imports, the components, the stylesheet. */
export function cardSources(cardPath: string): string[] {
  const local = [...readFileSync(cardPath, 'utf8').matchAll(/from\s+'\.\/([^'?]+)/g)].map((m) => join(dirname(cardPath), m[1]));
  const components = readdirSync(COMPONENTS_DIR).map((file) => join(COMPONENTS_DIR, file));
  return [cardPath, ...local, ...components, join(PACKAGE_DIR, 'card.css'), join(PACKAGE_DIR, 'player.ts')].map(repoPath).sort();
}

/** The website's copy of the stylesheet: the card fonts served from public/, then the scaled card rules. */
export const websiteCss = () =>
  `/* ${GENERATED} */\n${fontFaces((file) => `${FONT_URL}/${file}`)}\n${cardCss()}`;

export const websitePlayer = () => `// ${GENERATED}\n${readFileSync(join(PACKAGE_DIR, 'player.ts'), 'utf8')}`;

function writeShared(): void {
  const fonts = join(WEBSITE, 'public', FONT_URL);
  mkdirSync(fonts, {recursive: true});
  for (const file of [...new Set(FONTS.map((font) => font[3]))]) copyFileSync(join(PACKAGE_DIR, 'fonts', file), join(fonts, file));
  for (const license of readdirSync(join(PACKAGE_DIR, 'fonts')).filter((file) => file.startsWith('OFL')))
    copyFileSync(join(PACKAGE_DIR, 'fonts', license), join(fonts, license));
  writeFileSync(join(WEBSITE, 'app/assets/css/code-card.css'), websiteCss());
  writeFileSync(join(WEBSITE, 'app/utils/codeCardPlayer.ts'), websitePlayer());
}

export async function exportCards(paths: string[]): Promise<string[]> {
  const out = join(REPO_DIR, CARDS_EXPORT_DIR);
  mkdirSync(out, {recursive: true});
  const manifestPath = join(REPO_DIR, CARD_MANIFEST);
  const manifest: Record<string, {hash: string; sources: string[]}> = existsSync(manifestPath)
    ? JSON.parse(readFileSync(manifestPath, 'utf8'))
    : {};
  const written: string[] = [];
  for (const path of paths) {
    const name = basename(path, '.vue');
    if (dirname(path) !== CARDS_DIR) throw new Error(`${name}: only cards in tools/code-card/cards/ go to the website`);
    const fragment = join(out, `${name}.html`);
    writeFileSync(fragment, `<!-- ${GENERATED} -->\n${await renderFragment(path)}\n`);
    const sources = cardSources(path);
    manifest[name] = {hash: hashSources(REPO_DIR, sources), sources};
    written.push(fragment);
  }
  writeShared();
  const sorted = Object.fromEntries(Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)));
  writeFileSync(manifestPath, `${JSON.stringify(sorted, null, 2)}\n`);
  return written;
}

export async function main(argv: string[]): Promise<void> {
  const {all, cards} = parseExportArgs(argv);
  const paths = all
    ? readdirSync(CARDS_DIR)
        .filter((file) => file.endsWith('.vue'))
        .map((file) => join(CARDS_DIR, file))
    : cards.map(resolveCardPath);
  try {
    for (const path of await exportCards(paths)) console.log(path);
  } finally {
    await closeRenderer();
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2)).catch((err: Error) => {
    console.error(`card export: ${err.message}`);
    process.exit(1);
  });
}
