// `miondevx card export`: card HTML, shared stylesheet, fonts and player for the website, plus check-tree's manifest.

import {copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import {basename, dirname, join, relative, resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {parseArgs} from 'node:util';
import {CARD_MANIFEST, CARDS_EXPORT_DIR, hashSources} from '../../../scripts/lib/card-manifest.mjs';
import {CARDS_DIR, COMPONENTS_DIR, PACKAGE_DIR, REPO_DIR, keptCards, resolveCardPath} from './card.ts';
import {cardCss, closeRenderer, fontFaces, renderFragment} from './render.ts';

const EXPORT_USAGE = 'usage: miondevx card export <name…> | --all';
const FONT_URL = '/fonts/code-card';
const FONTS_DIR = join(PACKAGE_DIR, 'fonts');
const CSS_OUT = 'container/website/app/assets/css/code-card.css';
const PLAYER_OUT = 'container/website/app/utils/codeCardPlayer.ts';
const FONTS_OUT = `container/website/public${FONT_URL}`;
const GENERATED = 'generated by `pnpm miondevx card export` from tools/code-card/, never edit by hand';
// `from './x'`, `from "../x?raw"`, `import './x'`: every local file a card reads.
const LOCAL_IMPORT = /(?:from|import)\s+['"](\.\.?\/[^'"?]+)/g;

export function parseExportArgs(argv: string[]): {all: boolean; cards: string[]} {
  const {values, positionals} = parseArgs({args: argv, allowPositionals: true, options: {all: {type: 'boolean'}}});
  if (values.all && positionals.length) throw new Error(`pass card names or --all, not both. ${EXPORT_USAGE}`);
  if (!values.all && !positionals.length) throw new Error(EXPORT_USAGE);
  return {all: Boolean(values.all), cards: positionals};
}

const repoPath = (path: string) => relative(REPO_DIR, path).split('\\').join('/');

/** Every file the exported card depends on, the renderer included. */
export function cardSources(cardPath: string): string[] {
  const local = [...readFileSync(cardPath, 'utf8').matchAll(LOCAL_IMPORT)].map((match) => resolve(dirname(cardPath), match[1]));
  const components = readdirSync(COMPONENTS_DIR).map((file) => join(COMPONENTS_DIR, file));
  const fonts = readdirSync(FONTS_DIR).map((file) => join(FONTS_DIR, file));
  const tool = ['card.css', 'player.ts', 'src/render.ts'].map((file) => join(PACKAGE_DIR, file));
  return [...new Set([cardPath, ...local, ...components, ...fonts, ...tool].map(repoPath))].sort();
}

export const websiteCss = () => `/* ${GENERATED} */\n${fontFaces((file) => `${FONT_URL}/${file}`)}\n${cardCss()}`;

/** Writes the files every card shares; returns their repo paths. */
function writeShared(root: string): string[] {
  mkdirSync(join(root, FONTS_OUT), {recursive: true});
  const fonts = readdirSync(FONTS_DIR).map((file) => {
    copyFileSync(join(FONTS_DIR, file), join(root, FONTS_OUT, file));
    return `${FONTS_OUT}/${file}`;
  });
  for (const file of [CSS_OUT, PLAYER_OUT]) mkdirSync(dirname(join(root, file)), {recursive: true});
  writeFileSync(join(root, CSS_OUT), websiteCss());
  writeFileSync(join(root, PLAYER_OUT), `// ${GENERATED}\n${readFileSync(join(PACKAGE_DIR, 'player.ts'), 'utf8')}`);
  return [CSS_OUT, PLAYER_OUT, ...fonts];
}

type ManifestEntry = {hash: string; sources: string[]; outputs: Record<string, string>};

/** Exports `paths` under `root` (the repo by default). `all` rebuilds the manifest, dropping cards that are gone. */
export async function exportCards(paths: string[], {all = false, root = REPO_DIR} = {}): Promise<string[]> {
  if (!paths.length) throw new Error('no cards to export');
  for (const path of paths)
    if (dirname(path) !== CARDS_DIR) throw new Error(`${basename(path)}: only cards in tools/code-card/cards/ go to the website`);
  const outDir = join(root, CARDS_EXPORT_DIR);
  mkdirSync(outDir, {recursive: true});
  const manifestPath = join(root, CARD_MANIFEST);
  const manifest: Record<string, ManifestEntry> = !all && existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, 'utf8')) : {};
  const shared = writeShared(root);
  const written: string[] = [];
  for (const path of paths) {
    const name = basename(path, '.vue');
    const fragment = `${CARDS_EXPORT_DIR}/${name}.html`;
    writeFileSync(join(root, fragment), `<!-- ${GENERATED} -->\n${await renderFragment(path)}\n`);
    const sources = cardSources(path);
    // each output's own hash catches a hand edit on the website side
    const outputs = Object.fromEntries([fragment, ...shared].sort().map((file) => [file, hashSources(root, [file])]));
    manifest[name] = {hash: hashSources(REPO_DIR, sources), sources, outputs};
    written.push(join(root, fragment));
  }
  if (all)
    for (const file of readdirSync(outDir))
      if (file.endsWith('.html') && !manifest[basename(file, '.html')]) rmSync(join(outDir, file));
  const sorted = Object.fromEntries(Object.entries(manifest).sort(([left], [right]) => left.localeCompare(right)));
  writeFileSync(manifestPath, `${JSON.stringify(sorted, null, 2)}\n`);
  return written;
}

export async function main(argv: string[]): Promise<void> {
  const {all, cards} = parseExportArgs(argv);
  try {
    for (const path of await exportCards(all ? keptCards() : cards.map(resolveCardPath), {all})) console.log(path);
  } finally {
    await closeRenderer();
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2)).catch((err: Error) => {
    console.error(`card export: ${err.message}`);
    process.exit(1);
  });
}
