// Code generated by cmd/gen-builtin-purefns; DO NOT EDIT.
// Regenerate with `pnpm miondevx core codegen builtinpurefns` after editing the
// pure-fn sources in this package.
//
// A pure function's id is where it lives, and the build normally injects it.
// This package builds with plain tsc, which injects nothing, so its own
// registrations pass their id from here. The literal types are also how a
// consumer reading only this package's .d.ts still resolves an id.

/** What every id of this package's own pure fns starts with: the package, then the hash prefix. A
 *  built-in is told apart from a consumer's pure fn by this prefix, never by a list. */
export const RUN_TYPES_PURE_FN_ID_PREFIX = '@mionjs/run-types#pf_';

export const isDateString_MDYId = '@mionjs/run-types#pf_-y__pOnrgnvRMz';
export const relativeNowKeyId = '@mionjs/run-types#pf_0DI2YbUTsfcoey';
export const dateStrToMsId = '@mionjs/run-types#pf_0lOuvJ-q2MW6gT';
export const isTimeString_mmssId = '@mionjs/run-types#pf_2xtQHAMu-yOBo6';
export const uniqueMapEntriesId = '@mionjs/run-types#pf_3ALPSmgX80ATiY';
export const punycodeEncodeId = '@mionjs/run-types#pf_5oCqd7YyfA9rEw';
export const isSecondsWithMsId = '@mionjs/run-types#pf_6E7qWsIwaFRGn6';
export const isIdnaLabelId = '@mionjs/run-types#pf_7SetHd9N2sVGrV';
export const matchesCardNetworkId = '@mionjs/run-types#pf_A3KjzpjelkcBST';
export const isTimeZoneId = '@mionjs/run-types#pf_EYsxRHRDgAykA_';
export const isDateString_DMId = '@mionjs/run-types#pf_Eube1z0GFHuqlM';
export const countEnumKeysId = '@mionjs/run-types#pf_G5-z72czuSL8sC';
export const punycodeDecodeId = '@mionjs/run-types#pf_GA20s6bj41GC1A';
export const isDateString_YMId = '@mionjs/run-types#pf_GfQK19ktpvibuZ';
export const isTimeString_HHmmssId = '@mionjs/run-types#pf_IyjvBbz0zSlgCJ';
export const isDateStringId = '@mionjs/run-types#pf_MnJ72PqkyXHiSP';
export const isDateString_MDId = '@mionjs/run-types#pf_NJ9TCGDnkv_9Mn';
export const canonicalJsonId = '@mionjs/run-types#pf_NsFHAjPcl6zHKH';
export const isTimeString_ISOId = '@mionjs/run-types#pf_OCJ1B0-ZCAwagS';
export const isDateString_DMYId = '@mionjs/run-types#pf_PQVLEBllZckw8I';
export const isEcmaRegexId = '@mionjs/run-types#pf_Qd_9GJQlOCVqDe';
export const timeStrToMsId = '@mionjs/run-types#pf_RUAE44N0eAppE7';
export const luhnSumId = '@mionjs/run-types#pf_VJiknJ2exR2oMF';
export const isIPV6Id = '@mionjs/run-types#pf_WMqh9KCFUZK-QD';
export const isIPV4Id = '@mionjs/run-types#pf_Yxs_8lqAG5ppIo';
export const codePointLengthId = '@mionjs/run-types#pf_Z2sc5xQPKB0oav';
export const uniqueArrayItemsId = '@mionjs/run-types#pf_auGH9B61BMDll3';
export const isMinutesId = '@mionjs/run-types#pf_cgwpjq6rGsI8jb';
export const isHoursId = '@mionjs/run-types#pf_d8U9HjmMsNFd6Z';
export const getUnknownKeysFromArrayId = '@mionjs/run-types#pf_fL3v1v6aVZwJ7-';
export const isDateString_YMDId = '@mionjs/run-types#pf_gFl-yXbCxJqWgQ';
export const isTimeString_HHmmId = '@mionjs/run-types#pf_hiotRbfSKFAuK4';
export const isUUIDId = '@mionjs/run-types#pf_jzwmCOXKrhbowQ';
export const isSecondsWithLeapId = '@mionjs/run-types#pf_lFYcgG5ZSI-8em';
export const findCycleId = '@mionjs/run-types#pf_lQvUeXx-d_WXSw';
export const isSecondsId = '@mionjs/run-types#pf_n_ZOWff4X3qBMQ';
export const cardNetworkRulesId = '@mionjs/run-types#pf_nsU8QeJCuCF8Kr';
export const isIdnHostnameId = '@mionjs/run-types#pf_oSEQKIPgV2b85k';
export const isTimeString_ISO_TZId = '@mionjs/run-types#pf_qMsNYN8hy_sC8i';
export const isEmailAddressId = '@mionjs/run-types#pf_qotJfcleAqnWOD';
export const newRunTypeErrId = '@mionjs/run-types#pf_rXVwGkGDX08BsQ';
export const hasUnknownKeysFromArrayId = '@mionjs/run-types#pf_tfRjnFZVF8lqI_';
export const satisfiesBidiId = '@mionjs/run-types#pf_vLId7t0J8HNWlN';
export const uniqueSetMembersId = '@mionjs/run-types#pf_wxoIgaBn9QgDNN';
export const isCreditCardId = '@mionjs/run-types#pf_xkXrw7yD4dileP';
export const isLocalHostId = '@mionjs/run-types#pf_xlhuhlEYNnc0zQ';
