// Code generated by cmd/gen-builtin-purefns; DO NOT EDIT.
// Regenerate with `pnpm miondevx core codegen builtinpurefns` after editing the
// pure-fn sources in this package.
//
// A pure function's id is where it lives, and the build normally injects it.
// This package builds with plain tsc, which injects nothing, so its own
// registrations pass their id from here. The literal types are also how a
// consumer reading only this package's .d.ts still resolves an id.

export const relativeNowKeyId = '@mionjs/run-types#0DI2YbUTsfcoey';
export const dateStrToMsId = '@mionjs/run-types#0lOuvJ-q2MW6gT';
export const isTimeString_mmssId = '@mionjs/run-types#2xtQHAMu-yOBo6';
export const punycodeEncodeId = '@mionjs/run-types#5oCqd7YyfA9rEw';
export const isSecondsWithMsId = '@mionjs/run-types#6E7qWsIwaFRGn6';
export const isDateString_YMId = '@mionjs/run-types#7Rf0Glsc6JUCkf';
export const isIdnaLabelId = '@mionjs/run-types#7SetHd9N2sVGrV';
export const isDateString_YMDId = '@mionjs/run-types#7X6_Cv-vMFpqpV';
export const isCreditCardId = '@mionjs/run-types#89SFfr-VXm6ktw';
export const isDateString_DMYId = '@mionjs/run-types#9iHci0PH3ZkNb8';
export const isDateString_DMId = '@mionjs/run-types#FOpZBW5-MbCTNR';
export const countEnumKeysId = '@mionjs/run-types#G5-z72czuSL8sC';
export const punycodeDecodeId = '@mionjs/run-types#GA20s6bj41GC1A';
export const isTimeString_HHmmssId = '@mionjs/run-types#IyjvBbz0zSlgCJ';
export const uniqueSetMembersId = '@mionjs/run-types#J_iuATWy59X8qQ';
export const isIdnHostnameId = '@mionjs/run-types#LLUDa_Sfw0wwgb';
export const isDateStringId = '@mionjs/run-types#MnJ72PqkyXHiSP';
export const isDateString_MDYId = '@mionjs/run-types#NsC7NEJixjb5KX';
export const canonicalJsonId = '@mionjs/run-types#NsFHAjPcl6zHKH';
export const isTimeString_ISOId = '@mionjs/run-types#OCJ1B0-ZCAwagS';
export const isIPV4Id = '@mionjs/run-types#OsHALYNiRjfkKm';
export const isEcmaRegexId = '@mionjs/run-types#Qd_9GJQlOCVqDe';
export const timeStrToMsId = '@mionjs/run-types#RUAE44N0eAppE7';
export const isTimeZoneId = '@mionjs/run-types#VAMGZVfCSK2ET-';
export const luhnSumId = '@mionjs/run-types#VJiknJ2exR2oMF';
export const matchesCardNetworkId = '@mionjs/run-types#XOwogm1z-3AOuZ';
export const uniqueArrayItemsId = '@mionjs/run-types#YNRWo5_UGDmz2r';
export const codePointLengthId = '@mionjs/run-types#Z2sc5xQPKB0oav';
export const isMinutesId = '@mionjs/run-types#cgwpjq6rGsI8jb';
export const isHoursId = '@mionjs/run-types#d8U9HjmMsNFd6Z';
export const getUnknownKeysFromArrayId = '@mionjs/run-types#fL3v1v6aVZwJ7-';
export const isEmailAddressId = '@mionjs/run-types#goU94DctU2SM-2';
export const isTimeString_HHmmId = '@mionjs/run-types#hiotRbfSKFAuK4';
export const isUUIDId = '@mionjs/run-types#jzwmCOXKrhbowQ';
export const isSecondsWithLeapId = '@mionjs/run-types#lFYcgG5ZSI-8em';
export const findCycleId = '@mionjs/run-types#lQvUeXx-d_WXSw';
export const isSecondsId = '@mionjs/run-types#n_ZOWff4X3qBMQ';
export const cardNetworkRulesId = '@mionjs/run-types#nsU8QeJCuCF8Kr';
export const isDateString_MDId = '@mionjs/run-types#omV6F-j2c23srV';
export const isTimeString_ISO_TZId = '@mionjs/run-types#qMsNYN8hy_sC8i';
export const newRunTypeErrId = '@mionjs/run-types#rXVwGkGDX08BsQ';
export const isIPV6Id = '@mionjs/run-types#sNis5nk-Tkeeag';
export const hasUnknownKeysFromArrayId = '@mionjs/run-types#tfRjnFZVF8lqI_';
export const satisfiesBidiId = '@mionjs/run-types#vLId7t0J8HNWlN';
export const isLocalHostId = '@mionjs/run-types#xlhuhlEYNnc0zQ';
export const uniqueMapEntriesId = '@mionjs/run-types#zaKCyxAHPBeWLi';
