import {defineConfig} from 'vite';
import {resolve} from 'path';
import {mionVitePlugin} from '@mionjs/devtools/vite';

export default defineConfig({
  plugins: [
    mionVitePlugin({
      runTypes: {
        tsConfig: resolve(__dirname, 'tsconfig.build.json'),
      },
      // The batch transport is generated by THIS build from the client package's program: every
      // `batch([...])` and inline inputFrom mapper in @mionjs/client's tests lands under this
      // package's `.mion/rpc/`, and the resolver imports the table from test-server.ts.
      client: {tsConfig: resolve(__dirname, '../client/tsconfig.json')},
    }),
  ],
  resolve: {conditions: ['source']},
  ssr: {resolve: {conditions: ['source']}},
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'index.ts'),
        'src/test-server-json': resolve(__dirname, 'src/test-server.ts'),
      },
      formats: ['es'],
    },
    outDir: '.dist/esm',
    emptyOutDir: true,
    sourcemap: true,
    minify: false,
    rollupOptions: {
      output: {
        format: 'es',
        entryFileNames: '[name].js',
        preserveModules: true,
        preserveModulesRoot: '.',
      },
      external: ['@mionjs/core', '@mionjs/router', '@mionjs/platform-node', /^[^./]/],
    },
  },
});
