// Writes the measured numbers to committed artifacts: a JSON file for tooling
// and a Markdown table for humans.
//
// Both are COMMITTED on purpose. The budgets are hand-maintained, so a report
// that moves without a budget moving is the signal that something changed the
// cost, and it shows up in the pull request diff where a reviewer will see it.
// Nothing time-varying goes in (no timestamps, no durations): the counts are
// deterministic under the exact-pinned `typescript` and `drizzle-orm`, so any
// diff at all means a real change.

import {writeFileSync, mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const REPORT_DIR = fileURLToPath(new URL('../reports/', import.meta.url));

export interface StepReport {
  step: number;
  label: string;
  /** Net instantiations this step added over the previous one. **/
  delta: number;
  budget: number;
  /** Net instantiations of the whole snippet up to and including this step. **/
  cumulative: number;
}

export interface ConsumerReport {
  budget: number;
  netInstantiations: number;
  keepsGenericAlias: boolean;
  dtsBytes: number;
}

/** One dialect's pipeline: the six steps, the chain total and the consumer lane. **/
export interface DialectPipelineReport {
  dialect: string;
  steps: StepReport[];
  /** What the WHOLE chain may cost. The per-step deltas cannot see work moving
   *  between layers, so the cumulative figure is budgeted too. **/
  totalBudget: number;
  consumer: ConsumerReport;
}

export interface PipelineReport {
  typescript: string;
  drizzleOrm: string;
  dialects: DialectPipelineReport[];
}

function dialectPipelineMarkdown(report: DialectPipelineReport): string {
  const rows = report.steps.map((s) => `| ${s.step} | ${s.label} | ${s.delta} | ${s.budget} | ${s.cumulative} |`).join('\n');
  const total = report.steps.reduce((sum, s) => sum + s.delta, 0);
  return `## ${report.dialect}

| Step | Layer | Net instantiations added | Budget | Cumulative |
| ---: | ----- | -----------------------: | -----: | ---------: |
${rows}

Total for the whole chain: **${total}**, against a total budget of **${report.totalBudget}**.

| Downstream consumer, read from the emitted \`.d.ts\` | Value |
| ---- | ----: |
| Consumer net instantiations | ${report.consumer.netInstantiations} |
| Budget | ${report.consumer.budget} |
| Emitted declaration size (bytes) | ${report.consumer.dtsBytes} |
| Declaration keeps the generic alias unresolved | ${report.consumer.keepsGenericAlias ? 'yes' : 'no'} |
`;
}

function markdown(report: PipelineReport): string {
  return `# Model pipeline type-instantiation report

Generated by \`packages/private-type-budget/test/modelPipeline.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript} and drizzle-orm ${report.drizzleOrm}.

Each step adds one layer to the previous snippet, compiled from source. The delta is what that layer
costs the type checker. Budgets may only ever be lowered, and the chain total is budgeted too: the
per-step deltas alone cannot see work moving from one layer to another. Every dialect runs the same
steps 2 to 5; step 1 declares the table with that dialect's builders and step 6 queries through its
drizzle database type.

Every one of these is paid again on every keystroke. TypeScript memoises type instantiations within
a single check, but each edit builds a new checker, so the work is redone.

The downstream consumer reads the models from the emitted \`.d.ts\`. Declaration emit prints the type
alias as it was written, never the type it evaluates to, so \`export type User = InferSelectModel<typeof api>\`
crosses the package boundary unresolved and every consumer runs the refine surgery again in their own
checker.

${report.dialects.map(dialectPipelineMarkdown).join('\n')}`;
}

/** Write reports/model-pipeline.{json,md}. **/
export function writeReport(report: PipelineReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}model-pipeline.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}model-pipeline.md`, markdown(report));
}

// ── Lane comparison ──────────────────────────────────────────────────────────

export interface LaneStepReport {
  step: number;
  label: string;
  delta: number;
  budget: number;
}

export interface LaneReport {
  name: string;
  steps: LaneStepReport[];
  total: number;
}

/** One dialect's three lanes, measured over the same five steps. **/
export interface DialectComparisonReport {
  dialect: string;
  lanes: LaneReport[];
}

export interface ComparisonReport {
  typescript: string;
  drizzleOrm: string;
  dialects: DialectComparisonReport[];
}

// Each lane names its own first two steps ("plain drizzle table" vs "plain row
// type" vs "plain builder object"), so the shared table needs labels that fit
// every column. Per-lane spellings stay in the JSON.
const NEUTRAL_STEP_LABELS = [
  'declare the formatted row',
  'refine two columns',
  'select / insert / update models',
  'mion route api',
  'initClient',
];

function dialectComparisonMarkdown({dialect, lanes}: DialectComparisonReport): string {
  const [first] = lanes;
  const names = lanes.map((l) => l.name);
  const head = `| Step | Layer | ${names.join(' | ')} |`;
  const rule = `| ---: | ----- | ${names.map(() => '---:').join(' | ')} |`;
  const rows = first.steps
    .map(
      (step, i) =>
        `| ${step.step} | ${NEUTRAL_STEP_LABELS[i] ?? step.label} | ${lanes.map((l) => l.steps[i].delta).join(' | ')} |`
    )
    .join('\n');
  const totals = `| | **Total** | ${lanes.map((l) => `**${l.total}**`).join(' | ')} |`;
  return `## ${dialect}

${head}
${rule}
${rows}
${totals}
`;
}

function comparisonMarkdown(report: ComparisonReport): string {
  return `# Model declaration approaches, compared

Generated by \`packages/private-type-budget/test/laneComparison.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript} and drizzle-orm ${report.drizzleOrm}.

Three ways to declare the same model:

- **slim** a table built from the dialect's slim recorder builders, model derived flat
- **type-only** the row written as a plain TypeScript type (formats by hand)
- **builder** the row built with the RT.\* / TF.\* value-first builders

Steps 2 to 5 are the same code in every lane: the same refinement, the same
Select/Insert/Update models, the same mion route api, the same client. Only step
1 differs, so the gap between the totals is the price of how the model was
declared and nothing else. Each dialect's type-only and builder rows spell the
formats that dialect's columns yield. The slim lane is also the only one that
yields a runnable drizzle table (toDrizzle); that db-query cost lives in the
pipeline report, paid only in the files that run queries.

Net instantiations per step, one table per dialect.

${report.dialects.map(dialectComparisonMarkdown).join('\n')}
## Reading this

These numbers price the three approaches, they do not rank them. The slim lane
derives the model from the table, so the database schema and the API types cannot
drift apart. The other two hand you that consistency to keep by hand: the
type-only row has to be edited whenever a column changes, and the builder row is
one authored definition the runtime also uses. What the tables show is the cost of
that guarantee, paid by every consumer's editor on every keystroke.

Steps 4 and 5 are the control. Their code is identical in all three lanes, so
their costs should stay close; the three lanes hand the client structurally
equivalent but differently spelled types (the builder lane's readonly params),
so the suite asserts the control holds within 30% rather than pinning the gap.

The type-only row is the floor: hand-written formats with no table machinery at
all. The slim lane's premium over it is what deriving the models from a real
table costs.
`;
}

/** Write reports/lane-comparison.{json,md}. **/
export function writeComparisonReport(report: ComparisonReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}lane-comparison.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}lane-comparison.md`, comparisonMarkdown(report));
}

// ── Type road vs builder road ────────────────────────────────────────────────

export interface RoadCaseReport {
  dialect: string;
  label: string;
  netInstantiations: number;
  budget: number;
}

export interface RoadReport {
  typescript: string;
  drizzleOrm: string;
  cases: RoadCaseReport[];
}

function roadMarkdown(report: RoadReport): string {
  const rows = report.cases.map((c) => `| ${c.dialect} | ${c.label} | ${c.netInstantiations} | ${c.budget} |`).join('\n');
  return `# Type road vs builder road, per table shape

Generated by \`packages/private-type-budget/test/typeRoad.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript} and drizzle-orm ${report.drizzleOrm}.

The same table, declared three ways in every dialect and read through the same models:

- **builder road** the table built with the builders, \`pgTable('t', {...})\` (or \`mysqlTable\`, \`sqliteTable\`)
- **type road** the table written as a hand-written type, \`PgTable<'t', {...}>\` (or \`MysqlTable\`, \`SqliteTable\`)
- **bare Column interface** the columns named as the \`Column\` interface every column type aliases, so no
  alias or props check runs. Nobody authors this; it is the floor the other two are measured against.

A builder table IS its hand-written twin, so the gap between the two roads is what the builders' props
checks and name lifting cost. A case a dialect cannot spell (a pg identity or array column in mysql or
sqlite) is left out of that dialect's wide vocabulary.

| Dialect | Case | Net instantiations | Budget |
| ------- | ---- | -----------------: | -----: |
${rows}

Budgets may only ever be lowered. Every one of these is paid again on every keystroke, because each
edit builds a new checker.
`;
}

/** Write reports/type-road.{json,md}. **/
export function writeRoadReport(report: RoadReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}type-road.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}type-road.md`, roadMarkdown(report));
}

export interface ColumnFormatsRow {
  dialect: string;
  label: string;
  types: number;
  builders: number;
  budget: {types: number; builders: number};
}

export interface ColumnFormatsReport {
  typescript: string;
  drizzleOrm: string;
  rows: ColumnFormatsRow[];
}

function columnFormatsMarkdown(report: ColumnFormatsReport): string {
  const rows = report.rows
    .map((r) => `| ${r.dialect} | ${r.label} | ${r.types} (${r.budget.types}) | ${r.builders} (${r.budget.builders}) |`)
    .join('\n');
  return `# Column formats, per table shape

Generated by \`packages/private-type-budget/test/columnFormats.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript} and drizzle-orm ${report.drizzleOrm}.

The same table declared two ways and read through the same models:

- **types** a hand-written \`PgTable<'t', {...}>\` (or \`MysqlTable\`, \`SqliteTable\`) with the column types
- **builders** \`pgTable('t', {...})\` (or \`mysqlTable\`, \`sqliteTable\`), whose table IS the hand-written one

Net instantiations, lower is better. Each line carries its budget in parentheses; budgets may only ever be
lowered.

| Dialect | Shape | Types (budget) | Builders (budget) |
| ------- | ----- | -------------: | ----------------: |
${rows}
`;
}

/** Write reports/column-formats.{json,md}. **/
export function writeColumnFormatsReport(report: ColumnFormatsReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}column-formats.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}column-formats.md`, columnFormatsMarkdown(report));
}
