<script setup lang="ts">
// Big, colorful stat tiles for the homepage "Tested to the same standard" card.
// Each tile is one section (front-end / Go / fuzzing); the number is gradient-
// filled text, hue passed per tile so they read as distinct colors. A `wide`
// tile spans the full row (horizontal layout); a `to` tile is a link.
import {resolveComponent} from 'vue'
// Counts generated by scripts/website/gen-test-counts.mjs from `vitest list` and
// `go test -list`. Imported (not fetched) so the real number is in the prerendered
// HTML: a tile that hydrates from "0" to "11,207" is a visible flash on the fold.
import testCounts from '../../data/test-counts.json'

/** Tiles whose number is generated name a `source` instead of a literal `value`,
 *  so the homepage never hand-types a count that then drifts. */
const COUNTS: Record<string, number> = {
  frontEndTests: testCounts.frontEnd.tests,
  frontEndFiles: testCounts.frontEnd.files,
  goTests: testCounts.go.tests,
}

interface Tile {
  /** Literal display value. Ignored when `source` resolves. */
  value?: string
  /** Key into the generated test counts; formatted with thousands separators. */
  source?: keyof typeof COUNTS | string
  label: string
  sub?: string
  hue?: number
  wide?: boolean
  to?: string
}

const props = withDefaults(defineProps<{tiles?: Tile[]}>(), {tiles: () => []})

// An unknown `source` falls back to `value` rather than rendering "undefined", so
// a renamed count degrades to the literal instead of breaking the page.
const display = (tile: Tile): string => {
  const count = tile.source === undefined ? undefined : COUNTS[tile.source]
  return count === undefined ? (tile.value ?? '') : count.toLocaleString('en-US')
}

const NuxtLink = resolveComponent('NuxtLink')
const gradient = (hue = 145) =>
  `linear-gradient(120deg, hsl(${hue} 70% 52%), hsl(${hue + 38} 66% 56%))`
</script>

<template>
  <div class="stat-tiles">
    <component
      :is="tile.to ? NuxtLink : 'div'"
      v-for="tile in tiles"
      :key="tile.label"
      :to="tile.to"
      class="stat-tile"
      :class="{'stat-tile--wide': tile.wide, 'stat-tile--link': tile.to}"
    >
      <span class="stat-tile-value" :style="{backgroundImage: gradient(tile.hue)}">{{ display(tile) }}</span>
      <span class="stat-tile-text">
        <span class="stat-tile-label" :style="tile.wide ? {backgroundImage: gradient(tile.hue)} : undefined">{{ tile.label }}</span>
        <span v-if="tile.sub" class="stat-tile-sub">{{ tile.sub }}</span>
      </span>
    </component>
  </div>
</template>

<style scoped>
.stat-tiles {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0.75rem;
  margin: 0.85rem 0;
}

.stat-tile {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 0.85rem 1rem;
  border: 1px solid var(--ui-border);
  border-radius: 0.6rem;
  background: color-mix(in srgb, var(--ui-text-muted) 6%, transparent);
}

.stat-tile--link {
  text-decoration: none;
  transition: border-color 0.15s ease, background 0.15s ease;
}

.stat-tile--link:hover {
  border-color: var(--ui-primary);
  background: color-mix(in srgb, var(--ui-text-muted) 10%, transparent);
}

.stat-tile--wide {
  grid-column: 1 / -1;
  flex-direction: row;
  align-items: center;
  gap: 1.1rem;
}

.stat-tile-value {
  font-size: 2.5rem;
  font-weight: 700;
  line-height: 1;
  letter-spacing: -0.02em;
  font-variant-numeric: tabular-nums;
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.stat-tile--wide .stat-tile-value {
  font-size: 2.9rem;
}

.stat-tile-text {
  display: flex;
  flex-direction: column;
  gap: 0.1rem;
  margin-top: 0.4rem;
}

.stat-tile--wide .stat-tile-text {
  margin-top: 0;
}

.stat-tile-label {
  font-size: 0.82rem;
  color: var(--ui-text-muted);
}

/* wide tile: the label is a big gradient heading (same hue as the icon) */
.stat-tile--wide .stat-tile-label {
  font-size: 1.5rem;
  font-weight: 700;
  letter-spacing: -0.01em;
  line-height: 1.1;
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.stat-tile--wide .stat-tile-text {
  gap: 0.3rem;
}

.stat-tile-sub {
  font-size: 0.7rem;
  line-height: 1.4;
  color: var(--ui-text-dimmed);
}

@media (max-width: 420px) {
  .stat-tiles {
    grid-template-columns: 1fr;
  }
}
</style>
