import {mapMySqlTable} from '@mionkit/drizzle';
import {varchar, timestamp} from 'drizzle-orm/mysql-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {StrUUIDv7, StrEmail} from '@mionkit/type-formats/FormatsString';
import {NumInteger} from '@mionkit/type-formats/FormatsNumber';

/** User entity with format types for intelligent column mapping */
interface User {
    id: StrUUIDv7;
    email: StrEmail;
    name: string;
    bio?: string; // Optional = nullable column
    age: NumInteger;
    tags: string[]; // Array = json column
    settings: {theme: string; notifications: boolean}; // Nested object = json
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = mapMySqlTable<User>().build('users', {
    id: varchar('id', {length: 36}).primaryKey(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
});
