import {toDrizzlePGTable} from '@mionjs/drizzle';
import {uuid, timestamp} from 'drizzle-orm/pg-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {FormatUUIDv7, FormatEmail} from '@mionjs/type-formats/StringFormats';
import {FormatInteger} from '@mionjs/type-formats/NumberFormats';

/** User entity with format types for intelligent column mapping */
interface User {
    id: FormatUUIDv7;
    email: FormatEmail;
    name: string;
    bio?: string; // Optional = nullable column
    age: FormatInteger;
    tags: string[]; // Array = jsonb column
    settings: {theme: string; notifications: boolean}; // Nested object = jsonb
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = toDrizzlePGTable<User>('users', {
    id: uuid('id').primaryKey(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
});
