import {toDrizzleMySqlTable} from '@mionjs/drizzle';
import {varchar, timestamp} from 'drizzle-orm/mysql-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {UUIDv7, Email} from '@ts-runtypes/core/formats';
import {Integer} from '@ts-runtypes/core/formats';

/** User entity with format types for intelligent column mapping */
interface User {
    id: UUIDv7;
    email: Email;
    name: string;
    bio?: string; // Optional = nullable column
    age: Integer;
    tags: string[]; // Array = json column
    settings: {theme: string; notifications: boolean}; // Nested object = json
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = toDrizzleMySqlTable<User>('users', {
    id: varchar('id', {length: 36}).primaryKey(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
});
