import {toDrizzleSqliteTable} from '@mionjs/drizzle';
import {text, integer} from 'drizzle-orm/sqlite-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {UUIDv7, Email} from '@ts-runtypes/core/formats';
import {Integer} from '@ts-runtypes/core/formats';

/** User entity with format types for intelligent column mapping */
interface User {
    id: UUIDv7;
    email: Email;
    name: string;
    bio?: string; // Optional = nullable column
    age: Integer;
    tags: string[]; // Array = text({mode: 'json'}) column
    settings: {theme: string; notifications: boolean}; // Nested object = text({mode: 'json'})
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = toDrizzleSqliteTable<User>('users', {
    id: text('id').primaryKey(),
    createdAt: integer('created_at', {mode: 'timestamp'}).notNull(),
});
