import {toDrizzleMySqlTable} from '@mionkit/drizzle';
import {varchar, timestamp} from 'drizzle-orm/mysql-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {FormatUUIDv7, FormatEmail} from '@mionkit/type-formats/StringFormats';
import {FormatInteger} from '@mionkit/type-formats/NumberFormats';

/** User entity with format types for intelligent column mapping */
interface User {
    id: FormatUUIDv7;
    email: FormatEmail;
    name: string;
    bio?: string; // Optional = nullable column
    age: FormatInteger;
    tags: string[]; // Array = json column
    settings: {theme: string; notifications: boolean}; // Nested object = json
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = toDrizzleMySqlTable<User>('users', {
    id: varchar('id', {length: 36}).primaryKey(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
});
