import {toDrizzleSqliteTable} from '@mionkit/drizzle';
import {text, integer} from 'drizzle-orm/sqlite-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {FormatUUIDv7, FormatEmail} from '@mionkit/type-formats/StringFormats';
import {FormatInteger} from '@mionkit/type-formats/NumberFormats';

/** User entity with format types for intelligent column mapping */
interface User {
    id: FormatUUIDv7;
    email: FormatEmail;
    name: string;
    bio?: string; // Optional = nullable column
    age: FormatInteger;
    tags: string[]; // Array = text({mode: 'json'}) column
    settings: {theme: string; notifications: boolean}; // Nested object = text({mode: 'json'})
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = toDrizzleSqliteTable<User>('users', {
    id: text('id').primaryKey(),
    createdAt: integer('created_at', {mode: 'timestamp'}).notNull(),
});
