import {mapPGTable} from '@mionkit/drizzle';
import {uuid, timestamp} from 'drizzle-orm/pg-core';
// Note: Must use regular import (not `import type`) for deepkit reflection to work
import {StrUUIDv7, StrEmail} from '@mionkit/type-formats/FormatsString';
import {NumInteger} from '@mionkit/type-formats/FormatsNumber';

/** User entity with format types for intelligent column mapping */
interface User {
    id: StrUUIDv7;
    email: StrEmail;
    name: string;
    bio?: string; // Optional = nullable column
    age: NumInteger;
    tags: string[]; // Array = jsonb column
    settings: {theme: string; notifications: boolean}; // Nested object = jsonb
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = mapPGTable<User>().build('users', {
    id: uuid('id').primaryKey(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
});
