import {mapSqliteTable} from '@mionkit/drizzle';
import {text, integer} from 'drizzle-orm/sqlite-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {StrUUIDv7, StrEmail} from '@mionkit/type-formats/FormatsString';
import {NumInteger} from '@mionkit/type-formats/FormatsNumber';

/** User entity with format types for intelligent column mapping */
interface User {
    id: StrUUIDv7;
    email: StrEmail;
    name: string;
    bio?: string; // Optional = nullable column
    age: NumInteger;
    tags: string[]; // Array = text({mode: 'json'}) column
    settings: {theme: string; notifications: boolean}; // Nested object = text({mode: 'json'})
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = mapSqliteTable<User>().build('users', {
    id: text('id').primaryKey(),
    createdAt: integer('created_at', {mode: 'timestamp'}).notNull(),
});
