import {toDrizzlePGTable} from '@mionjs/drizzle';
import {uuid, timestamp} from 'drizzle-orm/pg-core';
// Note: Must use regular import (not `import type`) for reflection to work
import {UUIDv7, Email} from '@ts-runtypes/core/formats';
import {Integer} from '@ts-runtypes/core/formats';

/** User entity with format types for intelligent column mapping */
interface User {
    id: UUIDv7;
    email: Email;
    name: string;
    bio?: string; // Optional = nullable column
    age: Integer;
    tags: string[]; // Array = jsonb column
    settings: {theme: string; notifications: boolean}; // Nested object = jsonb
    createdAt: Date;
}

// we should always configure primary and foreign keys
export const usersAutoGenerated = toDrizzlePGTable<User>('users', {
    id: uuid('id').primaryKey(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
});
