// Writes builder / format call-site costs to a committed JSON file and Markdown table. Committed on purpose, as
// in packages/private-type-budget/test/report.ts: budgets are hand-maintained, so a report moving without a budget
// shows in the PR diff. Nothing time-varying goes in: counts are deterministic under the exact-pinned `typescript`.

import {writeFileSync, mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const REPORT_DIR = fileURLToPath(new URL('../../reports/', import.meta.url));

export interface CallRow {
  group: string;
  label: string;
  /** Net instantiations the FIRST call site costs — the one-time price of
   *  touching this builder in a file. **/
  fixed: number;
  fixedBudget: number;
  /** Net instantiations each ADDITIONAL call adds — what scales with schema
   *  size, and the number worth optimising. **/
  marginal: number;
  marginalBudget: number;
}

export interface MemberRow {
  group: string;
  label: string;
  base: number;
  baseBudget: number;
  /** Net instantiations each additional member adds. **/
  perMember: number;
  perMemberBudget: number;
}

export interface BuilderCostReport {
  typescript: string;
  calls: CallRow[];
  members: MemberRow[];
}

function callTable(rows: CallRow[]): string {
  return rows
    .map((r) => `| ${r.group} | \`${r.label}\` | ${r.fixed} | ${r.fixedBudget} | ${r.marginal} | ${r.marginalBudget} |`)
    .join('\n');
}

function memberTable(rows: MemberRow[]): string {
  return rows
    .map((r) => `| ${r.group} | ${r.label} | ${r.base} | ${r.baseBudget} | ${r.perMember} | ${r.perMemberBudget} |`)
    .join('\n');
}

function markdown(report: BuilderCostReport): string {
  const byMarginal = [...report.calls].sort((a, b) => b.marginal - a.marginal).slice(0, 8);
  const worst = byMarginal.map((r) => `| \`${r.label}\` | ${r.marginal} |`).join('\n');
  return `# Builder and format type-instantiation report

Generated by \`packages/run-types/test/types/builderCost.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript}.

## Why two numbers

A single call's instantiation count is not the cost that scales. Most of what a
one-call measurement reports is a ONE-TIME cost that a file pays once, no matter
how many fields it declares: resolving the overload set and the params interface.
A real schema file is one import and many calls.

- **fixed** is what the first call site in a file costs.
- **marginal** is what each additional call adds. This is the number that scales,
  and the one worth optimising.

Budgets may only ever be lowered.

## Highest marginal cost

| Call | Net instantiations per additional call |
| ---- | -------------------------------------: |
${worst}

## Per call site

| Group | Call | Fixed | Budget | Marginal | Budget |
| ----- | ---- | ----: | -----: | -------: | -----: |
${callTable(report.calls)}

## Per member

How a container's cost grows with the number of members it holds. \`base\` is the
8-member container; \`per member\` is the slope from 8 to 16 members.

| Group | Case | Base (8) | Budget | Per member | Budget |
| ----- | ---- | -------: | -----: | ---------: | -----: |
${memberTable(report.members)}

Every one of these is paid again on every keystroke. TypeScript memoises type
instantiations within a single check, but each edit builds a new checker, so the
work is redone.
`;
}

/** Write reports/builder-cost.{json,md}. **/
export function writeBuilderCostReport(report: BuilderCostReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}builder-cost.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}builder-cost.md`, markdown(report));
}
