// Writes the builder / format call-site costs to committed artifacts: a JSON
// file for tooling and a Markdown table for humans.
//
// Both are COMMITTED on purpose, same reasoning as
// packages/type-budget/test/report.ts: the budgets are hand-maintained, so a
// report that moves without a budget moving is the signal that something changed
// the cost, and it shows up in the pull request diff where a reviewer sees it.
// It is also what makes "measured this family, found no win" a reviewable fact
// rather than a claim in a commit message.
//
// Nothing time-varying goes in (no timestamps, no durations): the counts are
// deterministic under the exact-pinned `typescript`, so any diff at all means a
// real change.

import {writeFileSync, mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

const REPORT_DIR = fileURLToPath(new URL('../../reports/', import.meta.url));

export interface CallRow {
  group: string;
  label: string;
  /** Net instantiations the FIRST call site costs — the one-time price of
   *  touching this builder in a file. **/
  fixed: number;
  fixedBudget: number;
  /** Net instantiations each ADDITIONAL call adds — what scales with schema
   *  size, and the number worth optimising. **/
  marginal: number;
  marginalBudget: number;
}

export interface MemberRow {
  group: string;
  label: string;
  base: number;
  baseBudget: number;
  /** Net instantiations each additional member adds. **/
  perMember: number;
  perMemberBudget: number;
}

export interface BuilderCostReport {
  typescript: string;
  calls: CallRow[];
  members: MemberRow[];
}

function callTable(rows: CallRow[]): string {
  return rows
    .map((r) => `| ${r.group} | \`${r.label}\` | ${r.fixed} | ${r.fixedBudget} | ${r.marginal} | ${r.marginalBudget} |`)
    .join('\n');
}

function memberTable(rows: MemberRow[]): string {
  return rows
    .map((r) => `| ${r.group} | ${r.label} | ${r.base} | ${r.baseBudget} | ${r.perMember} | ${r.perMemberBudget} |`)
    .join('\n');
}

function markdown(report: BuilderCostReport): string {
  const byMarginal = [...report.calls].sort((a, b) => b.marginal - a.marginal).slice(0, 8);
  const worst = byMarginal.map((r) => `| \`${r.label}\` | ${r.marginal} |`).join('\n');
  return `# Builder and format type-instantiation report

Generated by \`packages/run-types/test/types/builderCost.compile.test.ts\`. Do not edit by hand.
Measured with TypeScript ${report.typescript}.

## Why two numbers

A single call's instantiation count is not the cost that scales. Most of what a
one-call measurement reports is a ONE-TIME cost that a file pays once, no matter
how many fields it declares: resolving the overload set and the params interface.
A real schema file is one import and many calls.

- **fixed** is what the first call site in a file costs.
- **marginal** is what each additional call adds. This is the number that scales,
  and the one worth optimising.

Budgets may only ever be lowered.

## Highest marginal cost

| Call | Net instantiations per additional call |
| ---- | -------------------------------------: |
${worst}

## Per call site

| Group | Call | Fixed | Budget | Marginal | Budget |
| ----- | ---- | ----: | -----: | -------: | -----: |
${callTable(report.calls)}

## Per member

How a container's cost grows with the number of members it holds. \`base\` is the
8-member container; \`per member\` is the slope from 8 to 16 members.

| Group | Case | Base (8) | Budget | Per member | Budget |
| ----- | ---- | -------: | -----: | ---------: | -----: |
${memberTable(report.members)}

Every one of these is paid again on every keystroke. TypeScript memoises type
instantiations within a single check, but each edit builds a new checker, so the
work is redone.
`;
}

/** Write reports/builder-cost.{json,md}. **/
export function writeBuilderCostReport(report: BuilderCostReport): void {
  mkdirSync(REPORT_DIR, {recursive: true});
  writeFileSync(`${REPORT_DIR}builder-cost.json`, `${JSON.stringify(report, null, 2)}\n`);
  writeFileSync(`${REPORT_DIR}builder-cost.md`, markdown(report));
}
