import {existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {afterAll, describe, expect, it} from 'vitest';
import {CARD_MANIFEST, CARDS_EXPORT_DIR, hashSources} from '../../../scripts/lib/card-manifest.mjs';
import {CARDS_DIR, REPO_DIR, TMP_DIR} from '../src/card.ts';
import {cardSources, exportCards, parseExportArgs, websiteCss} from '../src/export.ts';
import {closeRenderer} from '../src/render.ts';

const root = mkdtempSync(join(tmpdir(), 'card-export-'));
afterAll(async () => {
  await closeRenderer();
  rmSync(root, {recursive: true, force: true});
});
const manifest = () => JSON.parse(readFileSync(join(root, CARD_MANIFEST), 'utf8'));

describe('code card: export', () => {
  it('names or --all', () => {
    expect(parseExportArgs(['a', 'b'])).toEqual({all: false, cards: ['a', 'b']});
    expect(parseExportArgs(['--all'])).toEqual({all: true, cards: []});
    expect(() => parseExportArgs([])).toThrow('usage: miondevx card export');
    expect(() => parseExportArgs(['a', '--all'])).toThrow('not both');
  });

  it("a card's sources: the card and its imports, the components, stylesheet, player, fonts and renderer", () => {
    const sources = cardSources(join(CARDS_DIR, 'typed-match.vue'));
    for (const file of ['cards/typed-match.vue', 'cards/typed-match.snippet.ts', 'components/CardCode.vue', 'card.css', 'player.ts', 'src/render.ts', 'fonts/inter.woff2'])
      expect(sources).toContain(`tools/code-card/${file}`);
    expect(sources).toEqual([...sources].sort());
  });

  it('finds every local file a card imports, whatever the quotes', () => {
    const path = join(CARDS_DIR, '__import-test.vue');
    writeFileSync(path, `<script setup lang="ts">\nimport a from "./typed-match.snippet.ts?raw";\nimport '../card.css';\n</script>\n`);
    try {
      expect(cardSources(path)).toEqual(expect.arrayContaining(['tools/code-card/cards/typed-match.snippet.ts', 'tools/code-card/card.css']));
    } finally {
      rmSync(path);
    }
  });

  it('writes the fragment, the shared files and a manifest of what they were built from', async () => {
    const [fragment] = await exportCards([join(CARDS_DIR, 'typed-match.vue')], {root});
    const html = readFileSync(fragment, 'utf8');
    expect(html).toMatch(/^<!-- generated by `pnpm miondevx card export`/);
    expect(html).toContain('<div class="code-card cc-kind-code"');
    expect(html).not.toMatch(/<html|@font-face/);
    for (const file of ['app/assets/css/code-card.css', 'app/utils/codeCardPlayer.ts', 'public/fonts/code-card/inter.woff2', 'public/fonts/code-card/OFL-Inter.txt'])
      expect(existsSync(join(root, 'container/website', file)), file).toBe(true);
    const entry = manifest()['typed-match'];
    expect(entry.hash).toBe(hashSources(REPO_DIR, entry.sources));
    expect(entry.outputs[`${CARDS_EXPORT_DIR}/typed-match.html`]).toBe(hashSources(root, [`${CARDS_EXPORT_DIR}/typed-match.html`]));
  });

  it('--all rebuilds the manifest, dropping a card that is gone', async () => {
    writeFileSync(join(root, CARDS_EXPORT_DIR, 'gone.html'), '');
    await exportCards([join(CARDS_DIR, 'drizzle-type-cost.vue')], {root, all: true});
    expect(Object.keys(manifest())).toEqual(['drizzle-type-cost']);
    expect(existsSync(join(root, CARDS_EXPORT_DIR, 'gone.html'))).toBe(false);
    expect(existsSync(join(root, CARDS_EXPORT_DIR, 'typed-match.html'))).toBe(false);
  });

  it('refuses no cards, and a card outside cards/', async () => {
    await expect(exportCards([], {root})).rejects.toThrow('no cards to export');
    await expect(exportCards([join(TMP_DIR, 'x.vue')], {root})).rejects.toThrow('only cards in tools/code-card/cards/');
  });

  it('the website stylesheet loads the fonts from public/, never inlined', () => {
    expect(websiteCss()).toContain("src:url(/fonts/code-card/inter.woff2) format('woff2')");
    expect(websiteCss()).not.toContain('data:font');
  });
});
