import {join} from 'node:path';
import {describe, expect, it} from 'vitest';
import {hashSources} from '../../../scripts/lib/card-manifest.mjs';
import {CARDS_DIR, REPO_DIR} from '../src/card.ts';
import {cardSources, parseExportArgs, websiteCss, websitePlayer} from '../src/export.ts';

describe('code card: export', () => {
  it('names or --all', () => {
    expect(parseExportArgs(['a', 'b'])).toEqual({all: false, cards: ['a', 'b']});
    expect(parseExportArgs(['--all'])).toEqual({all: true, cards: []});
    expect(() => parseExportArgs([])).toThrow('usage: miondevx card export');
    expect(() => parseExportArgs(['a', '--all'])).toThrow('not both');
  });

  it("a card's sources: the card, its snippet, every component, the stylesheet and the player", () => {
    const sources = cardSources(join(CARDS_DIR, 'typed-match.vue'));
    expect(sources).toContain('tools/code-card/cards/typed-match.vue');
    expect(sources).toContain('tools/code-card/cards/typed-match.snippet.ts');
    expect(sources).toContain('tools/code-card/components/CardCode.vue');
    expect(sources).toContain('tools/code-card/card.css');
    expect(sources).toContain('tools/code-card/player.ts');
    expect(sources).toEqual([...sources].sort());
  });

  it('hashes the sources the same way every time, and differently for another card', () => {
    const typed = cardSources(join(CARDS_DIR, 'typed-match.vue'));
    expect(hashSources(REPO_DIR, typed)).toBe(hashSources(REPO_DIR, [...typed].reverse()));
    expect(hashSources(REPO_DIR, typed)).not.toBe(hashSources(REPO_DIR, cardSources(join(CARDS_DIR, 'drizzle-type-cost.vue'))));
  });

  it('the website stylesheet loads the fonts from public/, never inlined', () => {
    expect(websiteCss()).toContain("src:url(/fonts/code-card/inter.woff2) format('woff2')");
    expect(websiteCss()).not.toContain('data:font');
    expect(websitePlayer()).toMatch(/^\/\/ generated by `pnpm miondevx card export`/);
  });
});
