// gen-format-error-keys prints packages/run-types/src/go-generated/formatErrorKeys.generated.ts: per format,
// the error keys its validation code can emit and the params its samples cover.
//
//	pnpm miondevx core codegen errorkeys [--check]
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/mionkit/mion/ts-go-runtypes/internal/cachegen/typefunctions/formats"
	_ "github.com/mionkit/mion/ts-go-runtypes/internal/cachegen/typefunctions/formats/all"
)

func main() {
	fmt.Fprint(os.Stdout, Generate())
}

// outputPath is the committed generated file.
func outputPath() string {
	_, thisFile, _, _ := runtime.Caller(0)
	root := filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
	return filepath.Clean(filepath.Join(root, "packages", "run-types", "src", "go-generated", "formatErrorKeys.generated.ts"))
}

func formatNames() []string {
	seen := map[string]bool{}
	var names []string
	for _, emitter := range formats.Registered() {
		if !seen[emitter.Name()] {
			seen[emitter.Name()] = true
			names = append(names, emitter.Name())
		}
	}
	sort.Strings(names)
	return names
}

func quoted(keys []string) []string {
	out := make([]string, len(keys))
	for i, key := range keys {
		out[i] = "'" + strings.ReplaceAll(key, "'", "\\'") + "'"
	}
	return out
}

func union(keys []string) string {
	if len(keys) == 0 {
		return "never"
	}
	return strings.Join(quoted(keys), " | ")
}

// Generate renders the module with no imports, so the FriendlyText type harness can inline it.
func Generate() string {
	names := formatNames()
	var out strings.Builder
	out.WriteString("// AUTO-GENERATED by cmd/gen-format-error-keys. DO NOT EDIT.\n")
	out.WriteString("// Regenerate: pnpm miondevx core codegen errorkeys. CI fails on drift (`--check`).\n")
	out.WriteString("// Keys come from each format's own validation-errors code, run over the samples in\n")
	out.WriteString("// ts-go-runtypes/internal/cachegen/typefunctions/formats/errorkeys_samples.go.\n\n")

	out.WriteString("// Every `rt$errors` key a format's validation errors can carry, per format name.\n")
	out.WriteString("export type FormatErrorKeys = {\n")
	for _, name := range names {
		fmt.Fprintf(&out, "  %s: %s;\n", name, union(formats.AllErrorKeys(name)))
	}
	out.WriteString("};\n\n")

	out.WriteString("// The same keys as data.\n")
	out.WriteString("export const FORMAT_ERROR_KEYS = {\n")
	for _, name := range names {
		fmt.Fprintf(&out, "  %s: [%s],\n", name, strings.Join(quoted(formats.AllErrorKeys(name)), ", "))
	}
	out.WriteString("} as const;\n\n")

	out.WriteString("// The params each format's samples set or exclude on purpose; a param outside it fails a type test.\n")
	out.WriteString("export type FormatSampledParams = {\n")
	for _, name := range names {
		fmt.Fprintf(&out, "  %s: %s;\n", name, union(formats.SampledParams(name)))
	}
	out.WriteString("};\n")
	return out.String()
}
