// Code generated by cmd/gen-ts-constants. DO NOT EDIT.
// Source: internal/constants/constants.go.
// Regenerate via `pnpm run gen:ts-constants` after changing the Go source.

export interface CacheModuleSettings {
  readonly name: string;
  readonly varPrefix: string;
  readonly tag: string;
}

export const CACHE_MODULES = {
  classSerializerReg: {name: 'classSerializerRegModule', varPrefix: 'g_csr_', tag: 'csr'},
  cloneExactShape: {name: 'cloneExactShapeModule', varPrefix: 'g_ces_', tag: 'ces'},
  compactForJson: {name: 'compactForJsonModule', varPrefix: 'g_cj_', tag: 'cj'},
  compactFromJson: {name: 'compactFromJsonModule', varPrefix: 'g_cjr_', tag: 'cjr'},
  formatTransform: {name: 'formatTransformModule', varPrefix: 'g_fmt_', tag: 'fmt'},
  fromBinary: {name: 'fromBinaryModule', varPrefix: 'g_fb_', tag: 'fb'},
  hasUnknownKeys: {name: 'hasUnknownKeysModule', varPrefix: 'g_huk_', tag: 'huk'},
  jsonSchema: {name: 'jsonSchemaModule', varPrefix: 'g_jsc_', tag: 'jsc'},
  prepareForJson: {name: 'prepareForJsonModule', varPrefix: 'g_pj_', tag: 'pj'},
  prepareForJsonSafe: {name: 'prepareForJsonSafeModule', varPrefix: 'g_pjs_', tag: 'pjs'},
  pureFns: {name: 'pureFnsModule', varPrefix: '', tag: ''},
  restoreFromJson: {name: 'restoreFromJsonModule', varPrefix: 'g_rj_', tag: 'rj'},
  runTypes: {name: 'runTypesModule', varPrefix: 't_', tag: 't'},
  stringifyJson: {name: 'stringifyJsonModule', varPrefix: 'g_sj_', tag: 'sj'},
  toBinary: {name: 'toBinaryModule', varPrefix: 'g_tb_', tag: 'tb'},
  unknownKeyErrors: {name: 'unknownKeyErrorsModule', varPrefix: 'g_uke_', tag: 'uke'},
  unknownKeysToUndefinedWire: {name: 'unknownKeysToUndefinedWireModule', varPrefix: 'g_ukuw_', tag: 'ukuw'},
  validate: {name: 'validateModule', varPrefix: 'g_val_', tag: 'val'},
  validateStrict: {name: 'validateStrictModule', varPrefix: 'g_vst_', tag: 'vst'},
  validationErrors: {name: 'validationErrorsModule', varPrefix: 'g_verr_', tag: 'verr'},
  validationErrorsStrict: {name: 'validationErrorsStrictModule', varPrefix: 'g_vest_', tag: 'vest'},
} as const satisfies Record<string, CacheModuleSettings>;

export const CLASSSERIALIZERREG_VAR_PREFIX = 'g_csr_';
export const CLASSSERIALIZERREG_MODULE_NAME = 'classSerializerRegModule';
export const CLASSSERIALIZERREG_TAG = 'csr';
export const CLONEEXACTSHAPE_VAR_PREFIX = 'g_ces_';
export const CLONEEXACTSHAPE_MODULE_NAME = 'cloneExactShapeModule';
export const CLONEEXACTSHAPE_TAG = 'ces';
export const COMPACTFORJSON_VAR_PREFIX = 'g_cj_';
export const COMPACTFORJSON_MODULE_NAME = 'compactForJsonModule';
export const COMPACTFORJSON_TAG = 'cj';
export const COMPACTFROMJSON_VAR_PREFIX = 'g_cjr_';
export const COMPACTFROMJSON_MODULE_NAME = 'compactFromJsonModule';
export const COMPACTFROMJSON_TAG = 'cjr';
export const FORMATTRANSFORM_VAR_PREFIX = 'g_fmt_';
export const FORMATTRANSFORM_MODULE_NAME = 'formatTransformModule';
export const FORMATTRANSFORM_TAG = 'fmt';
export const FROMBINARY_VAR_PREFIX = 'g_fb_';
export const FROMBINARY_MODULE_NAME = 'fromBinaryModule';
export const FROMBINARY_TAG = 'fb';
export const HASUNKNOWNKEYS_VAR_PREFIX = 'g_huk_';
export const HASUNKNOWNKEYS_MODULE_NAME = 'hasUnknownKeysModule';
export const HASUNKNOWNKEYS_TAG = 'huk';
export const JSONSCHEMA_VAR_PREFIX = 'g_jsc_';
export const JSONSCHEMA_MODULE_NAME = 'jsonSchemaModule';
export const JSONSCHEMA_TAG = 'jsc';
export const PREPAREFORJSON_VAR_PREFIX = 'g_pj_';
export const PREPAREFORJSON_MODULE_NAME = 'prepareForJsonModule';
export const PREPAREFORJSON_TAG = 'pj';
export const PREPAREFORJSONSAFE_VAR_PREFIX = 'g_pjs_';
export const PREPAREFORJSONSAFE_MODULE_NAME = 'prepareForJsonSafeModule';
export const PREPAREFORJSONSAFE_TAG = 'pjs';
export const PUREFNS_VAR_PREFIX = '';
export const PUREFNS_MODULE_NAME = 'pureFnsModule';
export const PUREFNS_TAG = '';
export const RESTOREFROMJSON_VAR_PREFIX = 'g_rj_';
export const RESTOREFROMJSON_MODULE_NAME = 'restoreFromJsonModule';
export const RESTOREFROMJSON_TAG = 'rj';
export const RUNTYPES_VAR_PREFIX = 't_';
export const RUNTYPES_MODULE_NAME = 'runTypesModule';
export const RUNTYPES_TAG = 't';
export const STRINGIFYJSON_VAR_PREFIX = 'g_sj_';
export const STRINGIFYJSON_MODULE_NAME = 'stringifyJsonModule';
export const STRINGIFYJSON_TAG = 'sj';
export const TOBINARY_VAR_PREFIX = 'g_tb_';
export const TOBINARY_MODULE_NAME = 'toBinaryModule';
export const TOBINARY_TAG = 'tb';
export const UNKNOWNKEYERRORS_VAR_PREFIX = 'g_uke_';
export const UNKNOWNKEYERRORS_MODULE_NAME = 'unknownKeyErrorsModule';
export const UNKNOWNKEYERRORS_TAG = 'uke';
export const UNKNOWNKEYSTOUNDEFINEDWIRE_VAR_PREFIX = 'g_ukuw_';
export const UNKNOWNKEYSTOUNDEFINEDWIRE_MODULE_NAME = 'unknownKeysToUndefinedWireModule';
export const UNKNOWNKEYSTOUNDEFINEDWIRE_TAG = 'ukuw';
export const VALIDATE_VAR_PREFIX = 'g_val_';
export const VALIDATE_MODULE_NAME = 'validateModule';
export const VALIDATE_TAG = 'val';
export const VALIDATESTRICT_VAR_PREFIX = 'g_vst_';
export const VALIDATESTRICT_MODULE_NAME = 'validateStrictModule';
export const VALIDATESTRICT_TAG = 'vst';
export const VALIDATIONERRORS_VAR_PREFIX = 'g_verr_';
export const VALIDATIONERRORS_MODULE_NAME = 'validationErrorsModule';
export const VALIDATIONERRORS_TAG = 'verr';
export const VALIDATIONERRORSSTRICT_VAR_PREFIX = 'g_vest_';
export const VALIDATIONERRORSSTRICT_MODULE_NAME = 'validationErrorsStrictModule';
export const VALIDATIONERRORSSTRICT_TAG = 'vest';

// Internal render-format names (rtmod:/<basename>.js) the resolver
// writes to disk and relativizes to on-disk paths — see internal/compiler/entrymodules.
export const ENTRY_MODULE_PREFIX = 'rtmod:/';
export const ENTRY_MODULE_SUFFIX = '.js';
export const ENTRY_BINDING_PREFIX = '__rt_';
export const PURE_FN_MODULE_DIR = 'pf';
export const RUNTYPES_BUNDLE_BASENAME = 'runtypes';
export const FNS_BUNDLE_DIR = 'fns';
// Module-mode values for the --module-mode flag / plugin moduleMode option.
export const MODULE_MODE_DEFAULT = 'default';
export const MODULE_MODE_ALL_SINGLE = 'allSingle';
export const MODULE_MODE_ALL_MODULES = 'allModules';
export type ModuleMode = typeof MODULE_MODE_DEFAULT | typeof MODULE_MODE_ALL_SINGLE | typeof MODULE_MODE_ALL_MODULES;

// Enrichment mirror tags (internal/enrichment/mirror/tags.go): the reconcile
// markers hygiene must never flag, the dirty-state tags it reports, and
// the flag-free orphan-block regex body (compile with the 's' flag).
export const RT_TYPE_TAG = '@rtType';
export const RT_IDS_TAG = '@rtIds';
export const MARKER_COMMENT_PREFIX = '/** @rtType ';
export const TODO_TAG = '@todo';
export const ORPHAN_TAG = '@rtOrphan';
export const ORPHAN_CHILD_TAG = '@rtOrphanChild';
export const TODO_LINE = '// @todo: generated skeleton — fill in real data, then delete this line';
export const ORPHAN_BLOCK_PATTERN_SOURCE = '/\\* @rtOrphan(?:Child)? .*? \\*/';
// The ts-runtypes DSL type names enrichment consts are annotated with —
// part of the enrichment-file guard alongside the marker tags.
// FRIENDLY_TYPE_NAME is the LEGACY spelling, still accepted by the file guard
// so mirrors authored before the friendly-text rename are recognized.
export const FRIENDLY_TEXT_NAME = 'FriendlyText';
export const FRIENDLY_TYPE_NAME = 'FriendlyType';
export const MOCK_DATA_NAME = 'MockData';
