// Credit-card mock generation. Unlike a pattern-backed format, a card number is
// BUILT rather than drawn from a declared pool, so these tests drive the walker
// over hand-built RunType graphs and check the generated value against the same
// pure fns the emitted validator calls.
//
// Three behaviours: the default generates a fresh valid number, `testCreditCards`
// switches to the well-known sandbox numbers, and `invalid` produces a value the
// validator rejects.

import {describe, it, expect} from 'vitest';
import {mockRunType} from '../../../src/mocking/mockType.ts';
import {mockRunTypeInvalid} from '../../../src/mocking/mockInvalid.ts';
import {defaultMockOptions} from '../../../src/mocking/constants.mock.ts';
import type {RunTypeMockOptions} from '../../../src/mocking/mockTypes.ts';
import type {RunType} from '../../../src/runtypes/types.ts';
import {RunTypeKind} from '../../../src/go-generated/runTypeKind.generated.ts';
import {getRTUtils} from '../../../src/runtypes/rtUtils.ts';
import '../../../src/formats/index.ts';

const ITERATIONS = 300;

interface CardParams {
  networks?: readonly string[];
  separators?: string;
}
// isCreditCard returns the FAILURE MODE ('' when valid); matchesCardNetwork is a
// plain boolean.
type CardModeFn = (value: string, params: CardParams) => string;
type CardFn = (value: string, params: CardParams) => boolean;
const isCreditCard = getRTUtils().getPureFn('rtFormats::isCreditCard') as CardModeFn;
const matchesCardNetwork = getRTUtils().getPureFn('rtFormats::matchesCardNetwork') as CardFn;

// A card-branded string node, the shape the plugin feeds the walker.
function cardNode(params: CardParams = {}): RunType {
  return {
    id: `card-${JSON.stringify(params)}`,
    kind: RunTypeKind.string,
    formatAnnotation: {name: 'creditCard', params},
  } as unknown as RunType;
}

function mockCard(node: RunType, extra?: Partial<typeof defaultMockOptions>): unknown {
  return mockRunType(node, {mock: {...defaultMockOptions, ...extra}} as RunTypeMockOptions, []);
}

describe('credit card mock — generated by default', () => {
  it('every generated number passes the validator', () => {
    const node = cardNode();
    for (let i = 0; i < ITERATIONS; i++) {
      const card = mockCard(node) as string;
      expect(isCreditCard(card, {}), `generated ${card} should be valid`).toBe('');
    }
  });

  it('generates a DIFFERENT number across draws, which a fixed pool could not', () => {
    const node = cardNode();
    const seen = new Set<string>();
    for (let i = 0; i < ITERATIONS; i++) seen.add(mockCard(node) as string);
    expect(seen.size).toBeGreaterThan(ITERATIONS / 2);
  });

  it('honors pinned networks, so the number passes the network check too', () => {
    for (const networks of [['visa'], ['amex'], ['visa', 'mastercard'], ['diners', 'jcb', 'maestro']]) {
      const node = cardNode({networks});
      for (let i = 0; i < ITERATIONS; i++) {
        const card = mockCard(node) as string;
        expect(isCreditCard(card, {}), `${card} should be a valid card`).toBe('');
        expect(matchesCardNetwork(card, {networks}), `${card} should belong to ${networks.join('/')}`).toBe(true);
      }
    }
  });

  it('emits bare digits, which stay valid whether or not separators are declared', () => {
    const node = cardNode({separators: ' -'});
    for (let i = 0; i < ITERATIONS; i++) {
      const card = mockCard(node) as string;
      expect(card).toMatch(/^[0-9]+$/);
      expect(isCreditCard(card, {separators: ' -'})).toBe('');
    }
  });
});

describe('credit card mock — testCreditCards option', () => {
  it('draws the well-known sandbox numbers instead of generating', () => {
    const node = cardNode();
    const known = new Set([
      '4111111111111111',
      '4012888888881881',
      '4222222222222',
      '5555555555554444',
      '5105105105105100',
      '2223003122003222',
      '378282246310005',
      '371449635398431',
      '378734493671000',
      '6011111111111117',
      '6011000990139424',
      '3530111333300000',
      '3566002020360505',
      '30569309025904',
      '38520000023237',
      '6200000000000005',
      '6759649826438453',
      '6304000000000000',
    ]);
    for (let i = 0; i < ITERATIONS; i++) {
      const card = mockCard(node, {testCreditCards: true}) as string;
      expect(known.has(card), `${card} should be one of the published test numbers`).toBe(true);
      expect(isCreditCard(card, {})).toBe('');
    }
  });

  it('still respects pinned networks', () => {
    const node = cardNode({networks: ['amex']});
    for (let i = 0; i < ITERATIONS; i++) {
      const card = mockCard(node, {testCreditCards: true}) as string;
      expect(matchesCardNetwork(card, {networks: ['amex']}), `${card} should be an Amex test number`).toBe(true);
    }
  });
});

describe('credit card mock — invalid option', () => {
  it('always produces a value the validator rejects', () => {
    const node = cardNode();
    for (let i = 0; i < ITERATIONS; i++) {
      const card = mockRunTypeInvalid(node, {mock: {...defaultMockOptions, invalid: true}} as RunTypeMockOptions, []);
      const valid = typeof card === 'string' && isCreditCard(card, {}) === '';
      expect(valid, `${String(card)} should be rejected`).toBe(false);
    }
  });

  it('produces BOTH kinds of wrong value: a non-string, and a card-shaped one with a broken checksum', () => {
    const node = cardNode();
    let nonStrings = 0;
    let brokenCards = 0;
    for (let i = 0; i < ITERATIONS; i++) {
      const card = mockRunTypeInvalid(node, {mock: {...defaultMockOptions, invalid: true}} as RunTypeMockOptions, []);
      if (typeof card !== 'string') nonStrings++;
      else if (/^[0-9]{12,19}$/.test(card)) {
        // Card-shaped, so the mode names the checksum rather than the shape.
        expect(isCreditCard(card, {})).toBe('checksum');
        brokenCards++;
      }
    }
    // The broken-checksum arm is what actually exercises the checksum; the
    // non-string arm only proves the base kind check. Both must show up.
    expect(nonStrings, 'expected some non-string negatives').toBeGreaterThan(0);
    expect(brokenCards, 'expected some card-shaped negatives with a broken checksum').toBeGreaterThan(0);
  });
});
