// ###### DO NOT MODIFY MANUALLY: THIS FILE IS GENERATED AUTOMATICALLY
export const rΦutεs = {
    logs: {
        paramNames: ['ctx'],
        type: 2,
        id: 'logs',
        pointer: ['logs'],
        nestLevel: 0,
        options: {
            runOnError: false,
            hasReturnData: false,
            validateParams: true,
            deserializeParams: false,
            validateReturn: false,
            serializeReturn: false,
            isAsync: false,
        },
        paramsJitFns: {
            isType: {
                isNoop: false,
                fnID: 'is',
                jitFnHash: 'is_tHDvHBNV5l_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function is_tHDvHBNV5l_hrPp(v){return v.length === 0} return is_tHDvHBNV5l_hrPp;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            typeErrors: {
                isNoop: false,
                fnID: 'te',
                jitFnHash: 'te_tHDvHBNV5l_hrPp',
                args: {vλl: 'v', pλth: 'pth', εrr: 'er'},
                defaultParamValues: {vλl: '', pλth: '[]', εrr: '[]'},
                code: ' function te_tHDvHBNV5l_hrPp(v,pth=[],er=[]){if (v.length !== 0) utl.err(pth,er,"params"); return er} return te_tHDvHBNV5l_hrPp;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            toJsonVal: {
                isNoop: true,
                fnID: 'tj',
                jitFnHash: 'tj_tHDvHBNV5l_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function tj_tHDvHBNV5l_hrPp(v){return v} return tj_tHDvHBNV5l_hrPp;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            fromJsonVal: {
                isNoop: true,
                fnID: 'fj',
                jitFnHash: 'fj_tHDvHBNV5l_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function fj_tHDvHBNV5l_hrPp(v){return v} return fj_tHDvHBNV5l_hrPp;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            jsonStringify: {
                isNoop: false,
                fnID: 'js',
                jitFnHash: 'js_tHDvHBNV5l_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: " function js_tHDvHBNV5l_hrPp(v){return '[]'} return js_tHDvHBNV5l_hrPp;",
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
        },
        returnJitFns: {
            isType: {
                isNoop: false,
                fnID: 'is',
                jitFnHash: 'is_phlJ33Trhl',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function is_phlJ33Trhl(v){return v === undefined} return is_phlJ33Trhl;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            typeErrors: {
                isNoop: false,
                fnID: 'te',
                jitFnHash: 'te_phlJ33Trhl',
                args: {vλl: 'v', pλth: 'pth', εrr: 'er'},
                defaultParamValues: {vλl: '', pλth: '[]', εrr: '[]'},
                code: ' function te_phlJ33Trhl(v,pth=[],er=[]){if (v !== undefined) utl.err(pth,er,"void"); return er} return te_phlJ33Trhl;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            toJsonVal: {
                isNoop: false,
                fnID: 'tj',
                jitFnHash: 'tj_phlJ33Trhl',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function tj_phlJ33Trhl(v){return v = undefined} return tj_phlJ33Trhl;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            fromJsonVal: {
                isNoop: false,
                fnID: 'fj',
                jitFnHash: 'fj_phlJ33Trhl',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function fj_phlJ33Trhl(v){return v = undefined} return fj_phlJ33Trhl;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            jsonStringify: {
                isNoop: false,
                fnID: 'js',
                jitFnHash: 'js_phlJ33Trhl',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function js_phlJ33Trhl(v){return undefined} return js_phlJ33Trhl;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
        },
    },
    'users-updateUser': {
        paramNames: ['ctx', 'user'],
        type: 1,
        id: 'users-updateUser',
        pointer: ['users', 'updateUser'],
        nestLevel: 1,
        options: {
            runOnError: false,
            hasReturnData: true,
            validateParams: true,
            deserializeParams: true,
            validateReturn: false,
            serializeReturn: false,
            isAsync: false,
        },
        paramsJitFns: {
            isType: {
                isNoop: false,
                fnID: 'is',
                jitFnHash: 'is_IMa8OOoqEA_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: 'const is_EkSKYaQYMY_hrPp = utl.getJIT("is_EkSKYaQYMY_hrPp"); function is_IMa8OOoqEA_hrPp(v){return (v.length <= 1 && is_EkSKYaQYMY_hrPp.fn(v[0]))} return is_IMa8OOoqEA_hrPp;',
                dependenciesSet: new Set(['is_EkSKYaQYMY_hrPp']),
                pureFnDependencies: new Set([]),
            },
            typeErrors: {
                isNoop: false,
                fnID: 'te',
                jitFnHash: 'te_IMa8OOoqEA_hrPp',
                args: {vλl: 'v', pλth: 'pth', εrr: 'er'},
                defaultParamValues: {vλl: '', pλth: '[]', εrr: '[]'},
                code: 'const te_EkSKYaQYMY_hrPp = utl.getJIT("te_EkSKYaQYMY_hrPp"); function te_IMa8OOoqEA_hrPp(v,pth=[],er=[]){if (v.length > 1) utl.err(pth,er,"params"); else {pth.push(0); te_EkSKYaQYMY_hrPp.fn(v[0],pth,er); pth.splice(-1);}; return er} return te_IMa8OOoqEA_hrPp;',
                dependenciesSet: new Set(['te_EkSKYaQYMY_hrPp']),
                pureFnDependencies: new Set([]),
            },
            toJsonVal: {
                isNoop: false,
                fnID: 'tj',
                jitFnHash: 'tj_IMa8OOoqEA_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: 'const tj_EkSKYaQYMY_hrPp = utl.getJIT("tj_EkSKYaQYMY_hrPp"); function tj_IMa8OOoqEA_hrPp(v){v[0] = tj_EkSKYaQYMY_hrPp.fn(v[0]); return v} return tj_IMa8OOoqEA_hrPp;',
                dependenciesSet: new Set(['tj_EkSKYaQYMY_hrPp']),
                pureFnDependencies: new Set([]),
            },
            fromJsonVal: {
                isNoop: false,
                fnID: 'fj',
                jitFnHash: 'fj_IMa8OOoqEA_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: 'const fj_EkSKYaQYMY_hrPp = utl.getJIT("fj_EkSKYaQYMY_hrPp"); function fj_IMa8OOoqEA_hrPp(v){v[0] = fj_EkSKYaQYMY_hrPp.fn(v[0]); return v} return fj_IMa8OOoqEA_hrPp;',
                dependenciesSet: new Set(['fj_EkSKYaQYMY_hrPp']),
                pureFnDependencies: new Set([]),
            },
            jsonStringify: {
                isNoop: false,
                fnID: 'js',
                jitFnHash: 'js_IMa8OOoqEA_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: "const js_EkSKYaQYMY_hrPp = utl.getJIT(\"js_EkSKYaQYMY_hrPp\"); function js_IMa8OOoqEA_hrPp(v){return '['+js_EkSKYaQYMY_hrPp.fn(v[0])+']'} return js_IMa8OOoqEA_hrPp;",
                dependenciesSet: new Set(['js_EkSKYaQYMY_hrPp']),
                pureFnDependencies: new Set([]),
            },
        },
        returnJitFns: {
            isType: {
                isNoop: false,
                fnID: 'is',
                jitFnHash: 'is_EkSKYaQYMY',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: " function is_EkSKYaQYMY(v){return (typeof v === 'object' && v !== null && typeof v.name === 'string' && Number.isFinite(v.age) && (v.lastActivity instanceof Date && !isNaN(v.lastActivity.getTime())) )} return is_EkSKYaQYMY;",
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            typeErrors: {
                isNoop: false,
                fnID: 'te',
                jitFnHash: 'te_EkSKYaQYMY',
                args: {vλl: 'v', pλth: 'pth', εrr: 'er'},
                defaultParamValues: {vλl: '', pλth: '[]', εrr: '[]'},
                code: ' function te_EkSKYaQYMY(v,pth=[],er=[]){if (typeof v !== \'object\' || v === null ) {\n                utl.err(pth,er,"object");\n            } else {\n                ; ; if (typeof v.name !== \'string\') utl.err(pth,er,"string",["name"]);; ; if(!(Number.isFinite(v.age))) utl.err(pth,er,"number",["age"]);; ; if (!((v.lastActivity instanceof Date && !isNaN(v.lastActivity.getTime())))) utl.err(pth,er,"date",["lastActivity"])\n            }\n        ; return er} return te_EkSKYaQYMY;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            toJsonVal: {
                isNoop: true,
                fnID: 'tj',
                jitFnHash: 'tj_EkSKYaQYMY',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function tj_EkSKYaQYMY(v){return v} return tj_EkSKYaQYMY;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            fromJsonVal: {
                isNoop: false,
                fnID: 'fj',
                jitFnHash: 'fj_EkSKYaQYMY',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function fj_EkSKYaQYMY(v){v.lastActivity = new Date(v.lastActivity); return v} return fj_EkSKYaQYMY;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            jsonStringify: {
                isNoop: false,
                fnID: 'js',
                jitFnHash: 'js_EkSKYaQYMY',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: " function js_EkSKYaQYMY(v){return '{'+'\"name\":'+utl.asJSONString(v.name)+\",\"+'\"age\":'+v.age+\",\"+'\"lastActivity\":'+'\"'+v.lastActivity.toJSON()+'\"'+'}'} return js_EkSKYaQYMY;",
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
        },
    },
    sayHello: {
        paramNames: ['ctx', 'name'],
        type: 1,
        id: 'sayHello',
        pointer: ['sayHello'],
        nestLevel: 0,
        options: {
            runOnError: false,
            hasReturnData: true,
            validateParams: true,
            deserializeParams: false,
            validateReturn: false,
            serializeReturn: false,
            isAsync: false,
        },
        paramsJitFns: {
            isType: {
                isNoop: false,
                fnID: 'is',
                jitFnHash: 'is_RZzHJxzTTX_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: " function is_RZzHJxzTTX_hrPp(v){return (v.length <= 1 && typeof v[0] === 'string')} return is_RZzHJxzTTX_hrPp;",
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            typeErrors: {
                isNoop: false,
                fnID: 'te',
                jitFnHash: 'te_RZzHJxzTTX_hrPp',
                args: {vλl: 'v', pλth: 'pth', εrr: 'er'},
                defaultParamValues: {vλl: '', pλth: '[]', εrr: '[]'},
                code: ' function te_RZzHJxzTTX_hrPp(v,pth=[],er=[]){if (v.length > 1) utl.err(pth,er,"params"); else {; ; if (typeof v[0] !== \'string\') utl.err(pth,er,"string",[0])}; return er} return te_RZzHJxzTTX_hrPp;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            toJsonVal: {
                isNoop: true,
                fnID: 'tj',
                jitFnHash: 'tj_RZzHJxzTTX_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function tj_RZzHJxzTTX_hrPp(v){return v} return tj_RZzHJxzTTX_hrPp;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            fromJsonVal: {
                isNoop: true,
                fnID: 'fj',
                jitFnHash: 'fj_RZzHJxzTTX_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function fj_RZzHJxzTTX_hrPp(v){return v} return fj_RZzHJxzTTX_hrPp;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            jsonStringify: {
                isNoop: false,
                fnID: 'js',
                jitFnHash: 'js_RZzHJxzTTX_hrPp',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: " function js_RZzHJxzTTX_hrPp(v){return '['+utl.asJSONString(v[0])+']'} return js_RZzHJxzTTX_hrPp;",
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
        },
        returnJitFns: {
            isType: {
                isNoop: false,
                fnID: 'is',
                jitFnHash: 'is_LrjxT1f3Nr',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: " function is_LrjxT1f3Nr(v){return typeof v === 'string'} return is_LrjxT1f3Nr;",
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            typeErrors: {
                isNoop: false,
                fnID: 'te',
                jitFnHash: 'te_LrjxT1f3Nr',
                args: {vλl: 'v', pλth: 'pth', εrr: 'er'},
                defaultParamValues: {vλl: '', pλth: '[]', εrr: '[]'},
                code: ' function te_LrjxT1f3Nr(v,pth=[],er=[]){if (typeof v !== \'string\') utl.err(pth,er,"string"); return er} return te_LrjxT1f3Nr;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            toJsonVal: {
                isNoop: true,
                fnID: 'tj',
                jitFnHash: 'tj_LrjxT1f3Nr',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function tj_LrjxT1f3Nr(v){return v} return tj_LrjxT1f3Nr;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            fromJsonVal: {
                isNoop: true,
                fnID: 'fj',
                jitFnHash: 'fj_LrjxT1f3Nr',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function fj_LrjxT1f3Nr(v){return v} return fj_LrjxT1f3Nr;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
            jsonStringify: {
                isNoop: false,
                fnID: 'js',
                jitFnHash: 'js_LrjxT1f3Nr',
                args: {vλl: 'v'},
                defaultParamValues: {vλl: ''},
                code: ' function js_LrjxT1f3Nr(v){return utl.asJSONString(v)} return js_LrjxT1f3Nr;',
                dependenciesSet: new Set([]),
                pureFnDependencies: new Set([]),
            },
        },
    },
};
