import {mkdirSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {measureCase, readRouteFile, type CaseCost, type Lane} from './costHarness.ts';

// The same pg queries, returned by inferred and by hand-typed routes, over builder, type-form and plain drizzle tables.

const LANES: Lane[] = [
  {name: 'builders', rewrites: {}},
  {name: 'types', rewrites: {'../db/pg.db.ts': '../db/pg.types.db.ts', '../db/pg.schema.ts': '../db/pg.types.schema.ts'}},
  {name: 'plain drizzle', rewrites: {'../db/pg.db.ts': '../db/pg.plain.db.ts', '../db/pg.schema.ts': '../db/pg.plain.db.ts'}},
];
const STYLES = [
  {name: 'inferred', file: 'pg.routes.ts'},
  {name: 'typed', file: 'pg.typed.routes.ts'},
];

type Costs = Record<string, Record<string, Record<string, CaseCost>>>;
const costs: Costs = {};

describe('type cost of each pg case', () => {
  beforeAll(() => {
    for (const style of STYLES) {
      const {header, cases} = readRouteFile(style.file);
      for (const routeCase of cases) {
        for (const lane of LANES) {
          costs[routeCase.name] ??= {};
          costs[routeCase.name][style.name] ??= {};
          costs[routeCase.name][style.name][lane.name] = measureCase(header, lane, routeCase);
        }
      }
    }
    writeReport(costs);
  }, 600_000);

  it('every case compiles on every lane, in both styles', () => {
    const errors = Object.entries(costs).flatMap(([name, styles]) =>
      Object.entries(styles).flatMap(([style, lanes]) =>
        Object.entries(lanes).flatMap(([lane, cost]) => cost.errors.map((error) => `${name} ${style} ${lane}: ${error}`))
      )
    );
    expect(errors.join('\n')).toBe('');
  });

  it('both slim table forms cost less than plain drizzle on the server', () => {
    for (const [name, styles] of Object.entries(costs)) {
      for (const [style, lanes] of Object.entries(styles)) {
        for (const lane of ['builders', 'types']) {
          expect(lanes[lane].server, `${name} ${style} ${lane}`).toBeLessThan(lanes['plain drizzle'].server);
        }
      }
    }
  });

  it('an inferred route makes its client pay for the drizzle query, a typed one does not', () => {
    for (const [name, styles] of Object.entries(costs)) {
      for (const lane of ['builders', 'types']) {
        expect(styles.typed[lane].client, `${name} ${lane}`).toBeLessThan(styles.inferred[lane].client / 4);
      }
    }
  });

  it("a client of a typed route pays less for the slim models than for drizzle's $inferSelect types", () => {
    for (const [name, styles] of Object.entries(costs)) {
      for (const lane of ['builders', 'types']) {
        expect(styles.typed[lane].client, `${name} ${lane}`).toBeLessThanOrEqual(styles.typed['plain drizzle'].client);
      }
    }
  });
});

function writeReport(all: Costs): void {
  const dir = fileURLToPath(new URL('../reports/', import.meta.url));
  mkdirSync(dir, {recursive: true});
  writeFileSync(`${dir}drizzle-app.json`, `${JSON.stringify(all, (key, value) => (key === 'errors' ? undefined : value), 2)}\n`);
  const columns = STYLES.flatMap((style) => LANES.map((lane) => [style.name, lane.name] as const));
  const table = (side: 'server' | 'client') => [
    `| case | ${columns.map(([style, lane]) => `${style}, ${lane}`).join(' | ')} |`,
    `| ---- | ${columns.map(() => '----:').join(' | ')} |`,
    ...Object.entries(all).map(
      ([name, styles]) => `| ${name} | ${columns.map(([style, lane]) => styles[style][lane][side]).join(' | ')} |`
    ),
  ];
  const text = [
    '# Drizzle reference app: type cost per case',
    '',
    'GENERATED by packages/private-drizzle-app/test/cost.compile.test.ts. Net type instantiations of one pg route',
    '(inferred: no return type written; typed: the return type written from the slim models), over builder tables,',
    'type-form tables, and the same tables on plain drizzle.',
    '',
    '## Server file (the route alone)',
    '',
    ...table('server'),
    '',
    '## Client file (a call through the api type)',
    '',
    ...table('client'),
    '',
  ].join('\n');
  writeFileSync(`${dir}drizzle-app.md`, text);
}
