// gen-ts-constants regenerates the TS mirror of internal/constants/constants.go.
//
// internal/constants/constants.go is the single source of truth for values
// shared across the Go and JS halves of this repo (cache module settings,
// reserved identifiers, …). This program imports that package and writes a
// TS module mirroring its values, so the JS workspace never duplicates the
// constants by hand.
//
// Output:
//
//   - packages/ts-runtypes-devtools/src/go-generated/runtypes-constants.generated.ts
//     The registry consumed by the Vite plugin (cache modules, reflection
//     sub kinds, non-serializable globals).
//
// Run via the pnpm script:
//
//	pnpm run gen:ts-constants
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mionkit/ts-runtypes/internal/constants"
	"github.com/mionkit/ts-runtypes/internal/enrichment"
	"github.com/mionkit/ts-runtypes/internal/enrichment/mirror"
)

const vitePluginConstantsPath = "packages/ts-runtypes-devtools/src/go-generated/runtypes-constants.generated.ts"

func main() {
	if err := writeFile(filepath.Join(repoRoot(), vitePluginConstantsPath), buildVitePluginConstants()); err != nil {
		fmt.Fprintln(os.Stderr, "gen-ts-constants:", err)
		os.Exit(1)
	}
}

// repoRoot walks up from the working directory to the monorepo root (the
// directory holding package.json), so the output path resolves the same whether
// this tool is invoked from the repo root or from the Go module dir
// (ts-go-runtypes/, e.g. via `go -C ts-go-runtypes run ./cmd/gen-ts-constants`).
func repoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return "."
	}
	for {
		if _, statErr := os.Stat(filepath.Join(dir, "package.json")); statErr == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "."
		}
		dir = parent
	}
}

// writeFile writes content to path, creating or overwriting.
func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

// buildVitePluginConstants returns the full TS module body the Vite plugin
// consumes — cache modules, reflection sub kinds, and the non-serializable
// globals list.
func buildVitePluginConstants() string {
	out := &strings.Builder{}
	out.WriteString("// Code generated by cmd/gen-ts-constants. DO NOT EDIT.\n")
	out.WriteString("// Source: internal/constants/constants.go.\n")
	out.WriteString("// Regenerate via `pnpm run gen:ts-constants` after changing the Go source.\n")
	out.WriteString("\n")

	out.WriteString("export interface CacheModuleSettings {\n")
	out.WriteString("  readonly name: string;\n")
	out.WriteString("  readonly varPrefix: string;\n")
	out.WriteString("  readonly tag: string;\n")
	out.WriteString("}\n")
	out.WriteString("\n")

	keys := make([]string, 0, len(constants.CacheModules))
	for key := range constants.CacheModules {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	out.WriteString("export const CACHE_MODULES = {\n")
	for _, key := range keys {
		setting := constants.CacheModules[key]
		out.WriteString(fmt.Sprintf("  %s: {name: %q, varPrefix: %q, tag: %q},\n", tsKey(key), setting.Name, setting.VarPrefix, setting.Tag))
	}
	out.WriteString("} as const satisfies Record<string, CacheModuleSettings>;\n")
	out.WriteString("\n")

	// Convenience exports per module — `RUNTYPES_VAR_PREFIX` etc. — so
	// callers don't have to dereference CACHE_MODULES at every use site.
	for _, key := range keys {
		setting := constants.CacheModules[key]
		upper := strings.ToUpper(key)
		out.WriteString(fmt.Sprintf("export const %s_VAR_PREFIX = %q;\n", upper, setting.VarPrefix))
		out.WriteString(fmt.Sprintf("export const %s_MODULE_NAME = %q;\n", upper, setting.Name))
		out.WriteString(fmt.Sprintf("export const %s_TAG = %q;\n", upper, setting.Tag))
	}

	out.WriteString("\n")
	writeEntryModuleConstants(out)
	out.WriteString("\n")
	// REFLECTION_SUB_KIND / ReflectionSubKind moved to cmd/gen-run-type-kind's
	// devtools mirror (reflectionKind.generated.ts), generated from the FULL
	// internal/reflection/subkind.go parse so it can't drift (the old hand-list here
	// was a partial subset that silently omitted the Temporal sub-kinds).
	out.WriteString("\n")
	writeEnrichmentTagConstants(out)

	return out.String()
}

// writeEntryModuleConstants emits the internal render-format names. In
// files-mode they key the entry modules the resolver writes to disk and the
// rewrite's import injection consumes; rtmod:/ survives only as the
// render specifier, relativized to on-disk paths at the resolver boundary.
func writeEntryModuleConstants(out *strings.Builder) {
	out.WriteString("// Internal render-format names (rtmod:/<basename>.js) the resolver\n")
	out.WriteString("// writes to disk and relativizes to on-disk paths — see internal/compiler/entrymodules.\n")
	fmt.Fprintf(out, "export const ENTRY_MODULE_PREFIX = %q;\n", constants.EntryModulePrefix)
	fmt.Fprintf(out, "export const ENTRY_MODULE_SUFFIX = %q;\n", constants.EntryModuleSuffix)
	fmt.Fprintf(out, "export const ENTRY_BINDING_PREFIX = %q;\n", constants.EntryBindingPrefix)
	fmt.Fprintf(out, "export const PURE_FN_MODULE_DIR = %q;\n", constants.PureFnModuleDir)
	fmt.Fprintf(out, "export const RUNTYPES_BUNDLE_BASENAME = %q;\n", constants.RunTypesBundleBasename)
	fmt.Fprintf(out, "export const FNS_BUNDLE_DIR = %q;\n", constants.FnsBundleDir)
	out.WriteString("// Module-mode values for the --module-mode flag / plugin moduleMode option.\n")
	fmt.Fprintf(out, "export const MODULE_MODE_DEFAULT = %q;\n", constants.ModuleModeDefault)
	fmt.Fprintf(out, "export const MODULE_MODE_ALL_SINGLE = %q;\n", constants.ModuleModeAllSingle)
	fmt.Fprintf(out, "export const MODULE_MODE_ALL_MODULES = %q;\n", constants.ModuleModeAllModules)
	out.WriteString("export type ModuleMode = typeof MODULE_MODE_DEFAULT | typeof MODULE_MODE_ALL_SINGLE | typeof MODULE_MODE_ALL_MODULES;\n")
}

// writeEnrichmentTagConstants emits the enrichment-mirror tag literals from
// internal/enrichment/mirror/tags.go (single source of truth — the emitters and
// the Go hygiene detector derive from the same constants). The lint entry in
// ts-runtypes-devtools uses them for its cheap pre-filters and its tests; the
// regex body ships WITHOUT the Go `(?s)` prefix — JS compiles it with the
// `s` flag.
func writeEnrichmentTagConstants(out *strings.Builder) {
	out.WriteString("// Enrichment mirror tags (internal/enrichment/mirror/tags.go): the reconcile\n")
	out.WriteString("// markers hygiene must never flag, the dirty-state tags it reports, and\n")
	out.WriteString("// the flag-free orphan-block regex body (compile with the 's' flag).\n")
	fmt.Fprintf(out, "export const RT_TYPE_TAG = %q;\n", mirror.RtTypeTag)
	fmt.Fprintf(out, "export const RT_IDS_TAG = %q;\n", mirror.RtIdsTag)
	fmt.Fprintf(out, "export const MARKER_COMMENT_PREFIX = %q;\n", mirror.MarkerCommentPrefix)
	fmt.Fprintf(out, "export const TODO_TAG = %q;\n", mirror.TodoTag)
	fmt.Fprintf(out, "export const ORPHAN_TAG = %q;\n", mirror.OrphanTag)
	fmt.Fprintf(out, "export const ORPHAN_CHILD_TAG = %q;\n", mirror.OrphanChildTag)
	fmt.Fprintf(out, "export const TODO_LINE = %q;\n", mirror.TodoLine)
	fmt.Fprintf(out, "export const ORPHAN_BLOCK_PATTERN_SOURCE = %q;\n", mirror.OrphanBlockPatternSource)
	out.WriteString("// The ts-runtypes DSL type names enrichment consts are annotated with —\n")
	out.WriteString("// part of the enrichment-file guard alongside the marker tags.\n")
	out.WriteString("// FRIENDLY_TYPE_NAME is the LEGACY spelling, still accepted by the file guard\n")
	out.WriteString("// so mirrors authored before the friendly-text rename are recognized.\n")
	fmt.Fprintf(out, "export const FRIENDLY_TEXT_NAME = %q;\n", enrichment.FriendlyTextName)
	fmt.Fprintf(out, "export const FRIENDLY_TYPE_NAME = %q;\n", enrichment.FriendlyTypeName)
	fmt.Fprintf(out, "export const MOCK_DATA_NAME = %q;\n", enrichment.MockDataName)
}

// tsKey wraps a key in quotes if it isn't a bare JS identifier. Keeps the
// generated object literal small for the common alphanumeric case.
func tsKey(key string) string {
	if isIdent(key) {
		return key
	}
	return fmt.Sprintf("%q", key)
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, char := range s {
		isLetter := char == '_' || (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z')
		isDigit := char >= '0' && char <= '9'
		if i == 0 && !isLetter {
			return false
		}
		if !isLetter && !isDigit {
			return false
		}
	}
	return true
}
