package main

import (
	"fmt"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/mionkit/mion/ts-go-runtypes/internal/cachegen/typefunctions/formats"
	// Blank-import the aggregator so every concrete format emitter registers
	// with formats.Registry via its init() before Generate() enumerates it.
	_ "github.com/mionkit/mion/ts-go-runtypes/internal/cachegen/typefunctions/formats/all"
	"github.com/mionkit/mion/ts-go-runtypes/internal/reflection"
)

// monorepoRoot is the repository root — three dirs up from this file (cmd/
// gen-type-formats → cmd → ts-go-runtypes → repo root). The `packages/`
// workspaces live here, NOT under the Go module (a past migration moved the Go
// tree into ts-go-runtypes/ but left packages/ at the repo root), so the output
// path is one level above the Go module.
func monorepoRoot() string {
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", "..", ".."))
}

// typeFormatsOutputPath is the absolute path of the TS file we emit.
func typeFormatsOutputPath() string {
	return filepath.Join(monorepoRoot(), "packages", "run-types", "src", "go-generated", "typeFormats.generated.ts")
}

// jsStr renders a single-quoted TS string literal, matching oxfmt's quote style
// so the raw output stays close to the committed (oxfmt-formatted) file. Format
// names are plain identifiers, so the escaping only ever matters defensively.
func jsStr(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('\'')
	for _, r := range s {
		if r == '\'' || r == '\\' {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	b.WriteByte('\'')
	return b.String()
}

// kindJsName maps the base ReflectionKind a format refines onto its RunTypeKind
// JS property name, so the emitted metadata references RunTypeKind.<name> instead
// of a bare wire integer. A kind outside this map panics so the generator (and
// TestTypeFormatsFileInSync) fail loudly until it is extended, rather than
// emitting a broken RunTypeKind.undefined reference.
func kindJsName(kind reflection.ReflectionKind) string {
	switch kind {
	case reflection.KindString:
		return "string"
	case reflection.KindNumber:
		return "number"
	case reflection.KindBigInt:
		return "bigint"
	case reflection.KindClass:
		return "class"
	case reflection.KindArray:
		return "array"
	case reflection.KindTuple:
		return "tuple"
	case reflection.KindObject:
		return "object"
	case reflection.KindObjectLiteral:
		return "objectLiteral"
	default:
		panic(fmt.Sprintf("gen-type-formats: format refines unmapped ReflectionKind %d — extend kindJsName", int(kind)))
	}
}

// Generate builds the full body of typeFormats.generated.ts from the live format
// registry. Deterministic: one metadata row per registered format, keyed and
// sorted by canonical name.
func Generate() string {
	entries := formats.Registered()
	// Registered() sorts by (kind, name); re-sort by name alone for a stable,
	// human-scannable alphabetical table (and unique-key detection below).
	// Same-name entries (one family under several base kinds) tie-break by
	// kind so the deduped row below is deterministic — sort.Slice is unstable.
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name() != entries[j].Name() {
			return entries[i].Name() < entries[j].Name()
		}
		return entries[i].Kind() < entries[j].Kind()
	})

	var out strings.Builder
	out.WriteString("// ============================================================================\n")
	out.WriteString("//                            AUTO-GENERATED FILE\n")
	out.WriteString("//                            DO NOT EDIT MANUALLY\n")
	out.WriteString("// ============================================================================\n")
	out.WriteString("//\n")
	out.WriteString("// Generated by cmd/gen-type-formats from the Go format registry\n")
	out.WriteString("// (internal/cachegen/typefunctions/formats — each emitter's Name() + Kind()).\n")
	out.WriteString("//\n")
	out.WriteString("// To update: add / rename a format emitter on the Go side, then run:\n")
	out.WriteString("//\n")
	out.WriteString("//     pnpm miondevx core codegen typeformats\n")
	out.WriteString("//\n")
	out.WriteString("// The TestTypeFormatsFileInSync Go test and\n")
	out.WriteString("// `pnpm miondevx core codegen typeformats --check` (CI) both fail on any drift.\n")
	out.WriteString("//\n")
	out.WriteString("// The canonical format names mion stamps on a reflected prop's\n")
	out.WriteString("// `formatAnnotation.name`, each with the base RunTypeKind it refines. A\n")
	out.WriteString("// consumer that maps a reflected format to something external (a DB column,\n")
	out.WriteString("// a UI label) keys off this table instead of re-declaring the names.\n")
	out.WriteString("//\n")
	out.WriteString("// ============================================================================\n")
	out.WriteString("\n")
	out.WriteString("import {RunTypeKind, type RunTypeKindValue} from './runTypeKind.generated.ts';\n")
	out.WriteString("\n")
	out.WriteString("// Metadata for one built-in type format: the canonical `name` and the base\n")
	out.WriteString("// `RunTypeKind` the format refines.\n")
	out.WriteString("export interface TypeFormatMeta {\n")
	out.WriteString("  readonly name: FormatName;\n")
	out.WriteString("  readonly kind: RunTypeKindValue;\n")
	out.WriteString("}\n")
	out.WriteString("\n")
	out.WriteString("// Every built-in type format, keyed by its canonical name.\n")
	out.WriteString("export const typeFormats = {\n")
	seen := map[string]bool{}
	for _, emitter := range entries {
		name := emitter.Name()
		if seen[name] {
			// One family may register under SEVERAL base kinds (formattedObject
			// covers objectLiteral AND the bare `object` keyword); the table
			// stays name-keyed with the first (kind, name)-sorted entry —
			// the registry itself already panics on an exact (kind, name)
			// duplicate, so this is never a silent clash between emitters.
			continue
		}
		seen[name] = true
		fmt.Fprintf(&out, "  %s: {name: %s, kind: RunTypeKind.%s},\n", name, jsStr(name), kindJsName(emitter.Kind()))
	}
	out.WriteString("} as const;\n")
	out.WriteString("\n")
	out.WriteString("// The canonical format-name string stamped on a reflected prop's\n")
	out.WriteString("// `formatAnnotation.name`, covering every built-in format.\n")
	out.WriteString("export type FormatName = keyof typeof typeFormats;\n")

	return out.String()
}
