import {mkdirSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {measureCase, readRouteFile, type CaseCost} from './costHarness.ts';
import {DIALECTS, VARIANTS, type Dialect, type Variant} from './routeVariants.ts';

// The same routes in three variants per dialect: drizzle types (return inferred), type-form models, builder models.

type Costs = Record<Dialect, Record<string, Record<Variant, CaseCost>>>;
const costs = {} as Costs;

describe('type cost of every route, per dialect and variant', () => {
  beforeAll(() => {
    for (const dialect of DIALECTS) {
      costs[dialect] = {};
      for (const variant of VARIANTS) {
        const {header, cases} = readRouteFile(`${dialect}.${variant}.routes.ts`);
        for (const routeCase of cases) {
          costs[dialect][routeCase.name] ??= {} as Record<Variant, CaseCost>;
          costs[dialect][routeCase.name][variant] = measureCase(header, routeCase);
        }
      }
    }
    writeReport(costs);
  }, 900_000);

  it('every route compiles in every variant, whole and params only', () => {
    const errors = DIALECTS.flatMap((dialect) =>
      Object.entries(costs[dialect]).flatMap(([route, variants]) =>
        VARIANTS.flatMap((variant) => variants[variant].errors.map((error) => `${dialect} ${route} ${variant}: ${error}`))
      )
    );
    expect(errors.join('\n')).toBe('');
  });

  it('a client of a slim-model route pays less than a client of a drizzle-typed one', () => {
    for (const dialect of DIALECTS) {
      for (const [route, variants] of Object.entries(costs[dialect])) {
        for (const variant of ['types', 'builders'] as const) {
          expect(variants[variant].client.total, `${dialect} ${route} ${variant}`).toBeLessThan(variants.drizzle.client.total);
        }
      }
    }
  });
});

const fmt = (value: number) => value.toLocaleString('en-US');

function writeReport(all: Costs): void {
  const dir = fileURLToPath(new URL('../reports/', import.meta.url));
  mkdirSync(dir, {recursive: true});
  writeFileSync(
    `${dir}drizzle-example-app.json`,
    `${JSON.stringify(all, (key, value) => (key === 'errors' || key === 'rawClient' ? undefined : value), 2)}\n`
  );
  const PARTS = ['params', 'return', 'total'] as const;
  const table = (dialect: Dialect, side: 'server' | 'client') => {
    const routes = Object.entries(all[dialect]);
    const sum = (variant: Variant, part: (typeof PARTS)[number]) =>
      routes.reduce((total, [, variants]) => total + variants[variant][side][part], 0);
    const heads = VARIANTS.flatMap((variant) => [`${variant} params`, `${variant} return`, `${variant} both`]);
    return [
      `| route | ${heads.join(' | ')} |`,
      `| ---- | ${heads.map(() => '----:').join(' | ')} |`,
      ...routes.map(
        ([route, variants]) =>
          `| ${route} | ${VARIANTS.flatMap((variant) => PARTS.map((part) => fmt(variants[variant][side][part]))).join(' | ')} |`
      ),
      `| **all routes** | ${VARIANTS.flatMap((variant) => PARTS.map((part) => `**${fmt(sum(variant, part))}**`)).join(' | ')} |`,
    ];
  };
  const text = [
    '# Drizzle reference app: type cost per route',
    '',
    'GENERATED by packages/private-drizzle-example-app/test/cost.compile.test.ts. Net type instantiations of one route.',
    '`params` is the route with only its params; `return` is the rest (the query and the return type); `both` is',
    'the whole route. The server file holds the route alone; the client file calls it through the api type.',
    '',
    '- **drizzle**: plain drizzle tables, params typed with drizzle types, return type inferred by drizzle.',
    '- **types**: slim tables written as types, params and return type written with the slim models.',
    '- **builders**: slim builder tables, params and return type written with the slim models.',
    '',
    ...DIALECTS.flatMap((dialect) => [
      `## ${dialect}`,
      '',
      '### Client file',
      '',
      ...table(dialect, 'client'),
      '',
      '### Server file',
      '',
      ...table(dialect, 'server'),
      '',
    ]),
  ].join('\n');
  writeFileSync(`${dir}drizzle-example-app.md`, text);
}
