package resolver

// The batch transport, generated by the SERVER build. A batch is written in client code, but the server
// must know every batch id, its routes and its mappers before it runs one, so this file reads them from
// the BATCH SOURCE program (the session's own, or the separate one Options.ClientTsconfig names) and
// writes `<outDir>/rpc/batches.generated.js` (the table, registered through replaceBatches) plus one
// module per referenced inline mapper under `rpc/pf/`. Relative imports only, so the server never reads a
// client tree and no path leaks into a generated file; every lane gets the same output because all of
// them funnel through OpGenerate + OpTransform.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mionkit/mion/ts-go-runtypes/internal/cachegen/purefunctions"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/entrymodules"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/requestbatch"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/routerinit"
	"github.com/mionkit/mion/ts-go-runtypes/internal/constants"
	"github.com/mionkit/mion/ts-go-runtypes/internal/diagnostics"
	"github.com/mionkit/mion/ts-go-runtypes/internal/jsquote"
	"github.com/mionkit/mion/ts-go-runtypes/internal/protocol"
	"github.com/mionkit/mion/ts-go-runtypes/internal/textpos"
)

// batchesModuleBasename is the table module's basename under rpc/; the materializer appends the extension.
var batchesModuleBasename = strings.TrimSuffix(constants.BatchesModuleFile, moduleFileExt)

// clientPackages are the modules a client program must resolve for its batches to be readable at all: the
// brands come from the marker package, the calls from the client one. A client whose dependencies are not
// installed resolves neither and would otherwise yield zero batches with no signal.
var clientPackages = []string{requestbatch.ClientModule, "@mionjs/run-types"}

// rpcCollection is what one read of the batch source yields.
type rpcCollection struct {
	// sites are the batch source's `batch([...])` calls.
	sites []requestbatch.Site
	// entries are the inline mappers the batches reference plus the pure fns
	// those mappers call, sorted by key.
	entries []purefunctions.Entry
	// sourceDiags are kept ONLY for a separate batch source: the own program's already ride the generate
	// response. mapperDiags, the BAT007 misses plus the BAT008 warnings for own batches a client pointer
	// leaves out, are kept always.
	sourceDiags []diagnostics.Diagnostic
	mapperDiags []diagnostics.Diagnostic
	// files and roots are what the dev host watches, a NEW file under the root having to regenerate too;
	// empty when the batch source is the own program.
	files []string
	roots []string
}

// batchSourceSession returns the session the batch transport is read from: this one, or the lazily built
// client session, rebuilt when a stamped file changed or the client tsconfig matches a different file
// set. A client tsconfig that fails to load, or one that cannot resolve its packages, is an error.
func (sess *Session) batchSourceSession() (*Session, error) {
	if sess.opts.ClientTsconfig == "" {
		return sess, nil
	}
	tsconfig := sess.absPath(sess.opts.ClientTsconfig)
	if sess.batchPeer.session != nil && sess.batchPeer.tsconfig == tsconfig && !sess.batchPeer.stale() {
		return sess.batchPeer.session, nil
	}
	sess.closeBatchSource()
	client, err := sess.batchPeer.open(sess, tsconfig, "clientTsconfig", checkClientResolution)
	if err != nil {
		return nil, err
	}
	sess.hasBatchesMemo = nil
	return client, nil
}

// checkClientResolution fails when a client file's import of the client or marker package does not
// resolve: such a program's batches are invisible (no brand on `batch`, no `inputFrom` overload), and a
// server shipping without a table because the client's dependencies were missing must not pass silently.
func checkClientResolution(client *Session, tsconfig string) error {
	for _, sourceFile := range client.Program.TS.SourceFiles() {
		if sourceFile == nil || sourceFile.IsDeclarationFile || strings.Contains(sourceFile.FileName(), "/node_modules/") {
			continue
		}
		for _, specifier := range collectUnresolvedImportSpecifiers(client.checker, sourceFile) {
			for _, required := range clientPackages {
				if specifier == required {
					return fmt.Errorf("clientTsconfig %s: %s imports '%s', which does not resolve; install the client project's dependencies so its batches can be read", tsconfig, sourceFile.FileName(), specifier)
				}
			}
		}
	}
	return nil
}

// closeBatchSource releases the client session, if any.
func (sess *Session) closeBatchSource() {
	sess.batchPeer.close()
	sess.hasBatchesMemo = nil
}

func isDeclarationFileName(file string) bool {
	return strings.HasSuffix(file, ".d.ts") || strings.HasSuffix(file, ".d.mts") || strings.HasSuffix(file, ".d.cts")
}

// collectRpc reads the batch source: every batch site, the inline mappers they reference with the pure
// fns those call, and for a separate source its files and root for the dev watcher. With a client pointer
// set the own program's batches never reach the table, so each of their files gets a BAT008 warning.
func (sess *Session) collectRpc() (rpcCollection, error) {
	source, err := sess.batchSourceSession()
	if err != nil {
		return rpcCollection{}, err
	}
	sites, sourceDiags := source.collectProgramBatches()
	sess.setHasBatches(len(sites) > 0)
	out := rpcCollection{sites: sites}
	separate := source != sess
	if separate {
		out.sourceDiags = sourceDiags
		ownSites, _ := sess.collectProgramBatches()
		for _, file := range requestbatch.Files(ownSites) {
			for _, site := range ownSites {
				if site.FilePath == file {
					out.mapperDiags = append(out.mapperDiags, diagnostics.New(diagnostics.CodeBatchOwnBatchIgnored, batchSiteOf(sess, site), sess.opts.ClientTsconfig))
					break
				}
			}
		}
		out.files, out.roots = batchSourceWatchSet(source)
	}
	if len(sites) == 0 {
		return out, nil
	}
	referenced := referencedMapperKeys(sites)
	if len(referenced) > 0 {
		// Only the files holding a batch are walked, and only for their pure-fn registrations: an inline
		// mapper is written inside or beside the batch that names it. No override pass either, that is the
		// type-fn lane's. The keys the mappings name pick the entries, so a mapper reached through a
		// wrapper still counts.
		programEntries, _ := purefunctions.ExtractFromProgramCached(source.checker, source.marker, source.Program, requestbatch.Files(sites), source.pureFnFileCache)
		byKey := make(map[string]purefunctions.Entry, len(programEntries))
		for _, entry := range programEntries {
			byKey[entry.Key()] = entry
		}
		// The referenced mappers plus the closure of the pure fns they call;
		// a dep the program does not define is stubbed at render time.
		queue := append([]string(nil), referenced...)
		seen := map[string]bool{}
		for len(queue) > 0 {
			key := queue[0]
			queue = queue[1:]
			if seen[key] {
				continue
			}
			seen[key] = true
			entry, ok := byKey[key]
			if !ok {
				continue
			}
			out.entries = append(out.entries, entry)
			queue = append(queue, entry.PureFnDependencies...)
		}
		sort.Slice(out.entries, func(i, j int) bool { return out.entries[i].Key() < out.entries[j].Key() })
		for _, key := range referenced {
			if _, ok := byKey[key]; !ok {
				out.mapperDiags = append(out.mapperDiags, missingMapperDiag(source, sites, key))
			}
		}
	}
	return out, nil
}

// batchSourceWatchSet is what a dev host watches for a separate batch source: every non-declaration file
// outside node_modules, a mapper or batch being able to appear in any, plus the program's source root so
// a file created under it is seen too.
func batchSourceWatchSet(source *Session) (files []string, roots []string) {
	for _, sourceFile := range source.Program.TS.SourceFiles() {
		if sourceFile == nil || sourceFile.IsDeclarationFile || strings.Contains(sourceFile.FileName(), "/node_modules/") {
			continue
		}
		files = append(files, sourceFile.FileName())
	}
	return uniqueSortedStrings(files), []string{source.inferSrcDir()}
}

// referencedMapperKeys returns the sorted unique mapper ids the mappings name; every one needs its module.
func referencedMapperKeys(sites []requestbatch.Site) []string {
	seen := map[string]bool{}
	var keys []string
	for _, site := range sites {
		for _, mapping := range site.Mappings {
			if mapping.MapperKey == "" || seen[mapping.MapperKey] {
				continue
			}
			seen[mapping.MapperKey] = true
			keys = append(keys, mapping.MapperKey)
		}
	}
	sort.Strings(keys)
	return keys
}

// batchSiteOf turns a batch site into a diagnostic location on its program.
func batchSiteOf(source *Session, site requestbatch.Site) diagnostics.Site {
	diagSite := diagnostics.Site{FilePath: site.FilePath}
	if sourceFile := source.Program.SourceFile(site.FilePath); sourceFile != nil {
		diagSite.StartLine, diagSite.StartCol = textpos.LineCol(sourceFile, site.Start)
		diagSite.EndLine, diagSite.EndCol = textpos.LineCol(sourceFile, site.End)
	}
	return diagSite
}

// missingMapperDiag reports BAT007 at the first batch call naming key.
func missingMapperDiag(source *Session, sites []requestbatch.Site, key string) diagnostics.Diagnostic {
	for _, site := range sites {
		for _, mapping := range site.Mappings {
			if mapping.MapperKey == key {
				return diagnostics.New(diagnostics.CodeBatchMapperMissing, batchSiteOf(source, site), key)
			}
		}
	}
	return diagnostics.New(diagnostics.CodeBatchMapperMissing, diagnostics.Site{}, key)
}

// generateRpc writes `<outDir>/rpc/` for the collection and returns the table module's absolute path, or
// "" after removing `rpc/` when the batch source holds no batch.
func generateRpc(outDir string, collection rpcCollection, emitMode constants.EmitMode) (string, error) {
	rpcDir := filepath.Join(outDir, constants.RpcModuleDir)
	if len(collection.sites) == 0 {
		if err := os.RemoveAll(rpcDir); err != nil {
			return "", unwritableOutDirError(rpcDir, err)
		}
		return "", nil
	}
	// Always per-entry modules, whatever the project's moduleMode: the table imports each mapper by path.
	graph := purefunctions.CollectEntries(collection.entries, emitMode)
	var missing []string
	for _, entry := range graph {
		for _, dep := range entry.SoftDeps {
			if _, ok := graph[dep]; !ok {
				missing = append(missing, dep)
			}
		}
	}
	graph.AddMissingStubs(missing)
	rendered, err := entrymodules.RenderGrouped(graph, nil)
	if err != nil {
		return "", fmt.Errorf("batch transport: %w", err)
	}
	files := make(map[string]string, len(rendered)+1)
	for basename, source := range rendered {
		files[basename] = relativizeModuleImports(basename, source)
	}
	files[batchesModuleBasename] = renderBatchesModule(collection.sites, collection.entries)
	if err := os.MkdirAll(rpcDir, 0o755); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	if _, err := materializeModules(rpcDir, files); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	if err := pruneStaleModules(rpcDir, files); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	return filepath.Join(rpcDir, constants.BatchesModuleFile), nil
}

// batchTableEntry / batchTableMapping mirror @mionjs/router's BatchDefinition,
// the shape replaceBatches takes.
type batchTableEntry struct {
	Routes   []string            `json:"routes"`
	Mappings []batchTableMapping `json:"mappings,omitempty"`
}

type batchTableMapping struct {
	FromId     string `json:"fromId"`
	ToId       string `json:"toId"`
	ParamIndex int    `json:"paramIndex"`
	MapperKey  string `json:"mapperKey"`
}

// renderBatchesModule renders the table module: the imports of the mappers a mapping names, whose own
// deps sit inside the mapper modules, one registerInputMapperTuple each, then replaceBatches with the
// whole table. Deterministic: mappers by key, batches by id, mappings as extracted.
func renderBatchesModule(sites []requestbatch.Site, entries []purefunctions.Entry) string {
	defined := make(map[string]bool, len(entries))
	for _, entry := range entries {
		defined[entry.Key()] = true
	}
	var out strings.Builder
	out.WriteString("// GENERATED by mion (the batch transport). Do not edit.\n")
	out.WriteString("import {registerInputMapperTuple} from '@mionjs/core';\n")
	out.WriteString("import {replaceBatches} from '@mionjs/router';\n")
	var mapperKeys []string
	for _, key := range referencedMapperKeys(sites) {
		if !defined[key] {
			continue // BAT007 already reported; the server has nothing to register
		}
		mapperKeys = append(mapperKeys, key)
		basename := entrymodules.ModuleName(key, entrymodules.KindPureFn)
		out.WriteString("import {" + entrymodules.BindingName(basename) + "} from '" + ensureDotPrefix(basename) + moduleFileExt + "';\n")
	}
	for _, key := range mapperKeys {
		basename := entrymodules.ModuleName(key, entrymodules.KindPureFn)
		out.WriteString("registerInputMapperTuple(" + jsquote.Single(key) + ", " + entrymodules.BindingName(basename) + ");\n")
	}
	table := make(map[string]batchTableEntry, len(sites))
	for _, site := range sites {
		if _, seen := table[site.BatchId]; seen {
			continue // the same batch at a second call site (BAT003 flags a differing one)
		}
		entry := batchTableEntry{Routes: append([]string(nil), site.RouteIds...)}
		for _, mapping := range site.Mappings {
			entry.Mappings = append(entry.Mappings, batchTableMapping(mapping))
		}
		table[site.BatchId] = entry
	}
	var encoded bytes.Buffer
	encoder := json.NewEncoder(&encoded)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(table); err != nil {
		panic("batch table is not encodable: " + err.Error())
	}
	out.WriteString("replaceBatches(" + strings.TrimSuffix(encoded.String(), "\n") + ");\n")
	return out.String()
}

// setHasBatches records the batch source's batch presence for the transform.
func (sess *Session) setHasBatches(has bool) {
	sess.hasBatchesMemo = &has
}

// noteOwnBatches folds a per-scan extraction into the memo when the batch source is the own program: a
// file that just gained its first batch must flip the transform's switch before the next generate runs.
func (sess *Session) noteOwnBatches(sites []requestbatch.Site) {
	if sess.opts.ClientTsconfig == "" && len(sites) > 0 {
		sess.setHasBatches(true)
	}
}

// hasBatches is memoised and computed on demand, so `mion compile`, which transforms before it generates,
// decides the same way the bundler lane does. A client tsconfig that fails to load reads as "no batches"
// here and fails generate loudly.
func (sess *Session) hasBatches() bool {
	if sess.hasBatchesMemo != nil {
		return *sess.hasBatchesMemo
	}
	source, err := sess.batchSourceSession()
	if err != nil {
		return false
	}
	sites, _ := source.collectProgramBatches()
	sess.setHasBatches(len(sites) > 0)
	return *sess.hasBatchesMemo
}

// importsRouter is the cheap text signal separating a server, which may create its router through a
// wrapper the detector cannot see, from a client, which is never a misconfiguration. Memoised per Program.
func (sess *Session) importsRouter() bool {
	if sess.importsRouterMemo != nil {
		return *sess.importsRouterMemo
	}
	imports := false
	if sess.Program != nil && sess.Program.TS != nil {
		for _, sourceFile := range sess.Program.TS.SourceFiles() {
			if sourceFile == nil || sourceFile.IsDeclarationFile || strings.Contains(sourceFile.FileName(), "/node_modules/") {
				continue
			}
			if strings.Contains(sourceFile.Text(), routerinit.RouterModule) {
				imports = true
				break
			}
		}
	}
	sess.importsRouterMemo = &imports
	return imports
}

// routerInitSites finds the router-init modules among files, memoised per file for the current Program.
func (sess *Session) routerInitSites(files []string) []routerinit.Site {
	if sess.Program == nil || len(files) == 0 {
		return nil
	}
	return routerinit.ExtractFromProgramCached(sess.checker, sess.marker, sess.Program, files, sess.routerInitFileCache)
}

// routerInitFiles rides the generate response so a dev host re-transforms them when the batch module first appears.
func (sess *Session) routerInitFiles() []string {
	return routerinit.Files(sess.routerInitSites(sess.programSourceFiles()))
}

// routerInitReplacements appends the batch import to each router-init module when the batch source holds
// a batch: one point insertion at end of file, so no existing line moves. Under TransformRelative the
// specifier is already relative to the file; otherwise the virtual `rtrpc:/` form goes out for the
// compile lane's emit-time relativizer.
func (sess *Session) routerInitReplacements(files []string) []protocol.Replacement {
	sites := sess.routerInitSites(files)
	if len(sites) == 0 || !sess.hasBatches() {
		return nil
	}
	outDir := ""
	if sess.opts.TransformRelative {
		outDir = sess.resolveOutDir()
	}
	out := make([]protocol.Replacement, 0, len(sites))
	for _, site := range sites {
		specifier := constants.RpcModulePrefix + constants.BatchesModuleFile
		if outDir != "" {
			if rel := relUserToRpc(site.FilePath, outDir, constants.BatchesModuleFile); rel != "" {
				specifier = rel
			}
		}
		out = append(out, protocol.Replacement{File: site.FilePath, Start: site.End, End: site.End, Text: "\nimport '" + specifier + "';\n"})
	}
	return out
}

// uniqueSortedStrings dedupes and sorts.
func uniqueSortedStrings(values []string) []string {
	seen := make(map[string]bool, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}
