package resolver

// The batch transport, generated by the SERVER build: batches live in client code, but the server must know every
// id, route and mapper before it runs one. Relative imports only, so no path leaks into a generated file; every lane
// funnels through OpGenerate + OpTransform, so all get the same output.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mionkit/mion/ts-go-runtypes/internal/cachegen/purefunctions"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/entrymodules"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/marker"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/requestbatch"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/routerinit"
	"github.com/mionkit/mion/ts-go-runtypes/internal/constants"
	"github.com/mionkit/mion/ts-go-runtypes/internal/diagnostics"
	"github.com/mionkit/mion/ts-go-runtypes/internal/jsquote"
	"github.com/mionkit/mion/ts-go-runtypes/internal/protocol"
	"github.com/mionkit/mion/ts-go-runtypes/internal/textpos"
)

// batchesModuleBasename is the table module's basename under rpc/; the materializer appends the extension.
var batchesModuleBasename = strings.TrimSuffix(constants.BatchesModuleFile, moduleFileExt)

// rpcCollection is what one read of the program's batches yields.
type rpcCollection struct {
	// sites are the program's `batch([...])` calls.
	sites []requestbatch.Site
	// entries are the inline mappers the batches reference plus the pure fns
	// those mappers call, sorted by key.
	entries []purefunctions.Entry
	// mapperDiags are the BAT007 misses: a mapping naming a mapper the program does not define.
	mapperDiags []diagnostics.Diagnostic
}

// collectRpc reads the program's batch sites: the inline mappers they reference with the pure fns those call.
func (sess *Session) collectRpc(sites []requestbatch.Site) rpcCollection {
	sess.setHasBatches(len(sites) > 0)
	out := rpcCollection{sites: sites}
	if len(sites) == 0 {
		return out
	}
	referenced := referencedMapperKeys(sites)
	if len(referenced) > 0 {
		// Only the files holding a batch are walked, and only for their pure-fn registrations: an inline
		// mapper is written inside or beside the batch that names it. No override pass either, that is the
		// type-fn lane's. The keys the mappings name pick the entries, so a mapper reached through a
		// wrapper still counts.
		programEntries, _ := purefunctions.ExtractFromProgramCached(sess.checker, sess.marker, sess.Program, requestbatch.Files(sites), sess.pureFnFileCache)
		byKey := make(map[string]purefunctions.Entry, len(programEntries))
		for _, entry := range programEntries {
			byKey[entry.Key()] = entry
		}
		// The referenced mappers plus the closure of the pure fns they call;
		// a dep the program does not define is stubbed at render time.
		queue := append([]string(nil), referenced...)
		seen := map[string]bool{}
		for len(queue) > 0 {
			key := queue[0]
			queue = queue[1:]
			if seen[key] {
				continue
			}
			seen[key] = true
			entry, ok := byKey[key]
			if !ok {
				continue
			}
			out.entries = append(out.entries, entry)
			queue = append(queue, entry.PureFnDependencies...)
		}
		sort.Slice(out.entries, func(i, j int) bool { return out.entries[i].Key() < out.entries[j].Key() })
		for _, key := range referenced {
			if _, ok := byKey[key]; !ok {
				out.mapperDiags = append(out.mapperDiags, sess.missingMapperDiag(sites, key))
			}
		}
	}
	return out
}

// referencedMapperKeys returns the sorted unique mapper ids the mappings name; every one needs its module.
func referencedMapperKeys(sites []requestbatch.Site) []string {
	seen := map[string]bool{}
	var keys []string
	for _, site := range sites {
		for _, mapping := range site.Mappings {
			if mapping.MapperKey == "" || seen[mapping.MapperKey] {
				continue
			}
			seen[mapping.MapperKey] = true
			keys = append(keys, mapping.MapperKey)
		}
	}
	sort.Strings(keys)
	return keys
}

// missingMapperDiag reports BAT007 at the first batch call naming key.
func (sess *Session) missingMapperDiag(sites []requestbatch.Site, key string) diagnostics.Diagnostic {
	for _, site := range sites {
		for _, mapping := range site.Mappings {
			if mapping.MapperKey != key {
				continue
			}
			diagSite := diagnostics.Site{FilePath: site.FilePath}
			if sourceFile := sess.Program.SourceFile(site.FilePath); sourceFile != nil {
				diagSite.StartLine, diagSite.StartCol = textpos.LineCol(sourceFile, site.Start)
				diagSite.EndLine, diagSite.EndCol = textpos.LineCol(sourceFile, site.End)
			}
			return diagnostics.New(diagnostics.CodeBatchMapperMissing, diagSite, key)
		}
	}
	return diagnostics.New(diagnostics.CodeBatchMapperMissing, diagnostics.Site{}, key)
}

// generateRpc writes `<outDir>/rpc/` for the collection and returns the table module's absolute path, or
// "" after removing `rpc/` when the program holds no batch.
func generateRpc(outDir string, collection rpcCollection, emitMode constants.EmitMode) (string, error) {
	rpcDir := filepath.Join(outDir, constants.RpcModuleDir)
	if len(collection.sites) == 0 {
		if err := os.RemoveAll(rpcDir); err != nil {
			return "", unwritableOutDirError(rpcDir, err)
		}
		return "", nil
	}
	// Always per-entry modules, whatever the project's moduleMode: the table imports each mapper by path.
	graph := purefunctions.CollectEntries(collection.entries, emitMode)
	var missing []string
	for _, entry := range graph {
		for _, dep := range entry.SoftDeps {
			if _, ok := graph[dep]; !ok {
				missing = append(missing, dep)
			}
		}
	}
	graph.AddMissingStubs(missing)
	rendered, err := entrymodules.RenderGrouped(graph, nil)
	if err != nil {
		return "", fmt.Errorf("batch transport: %w", err)
	}
	files := make(map[string]string, len(rendered)+1)
	for basename, source := range rendered {
		files[basename] = relativizeModuleImports(basename, source)
	}
	files[batchesModuleBasename] = renderBatchesModule(collection.sites, collection.entries)
	if err := os.MkdirAll(rpcDir, 0o755); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	if _, err := materializeModules(rpcDir, files); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	if err := pruneStaleModules(rpcDir, files); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	return filepath.Join(rpcDir, constants.BatchesModuleFile), nil
}

// batchTableEntry / batchTableMapping mirror @mionjs/router's BatchDefinition,
// the shape replaceBatches takes.
type batchTableEntry struct {
	Routes   []string            `json:"routes"`
	Mappings []batchTableMapping `json:"mappings,omitempty"`
}

type batchTableMapping struct {
	FromId     string `json:"fromId"`
	ToId       string `json:"toId"`
	ParamIndex int    `json:"paramIndex"`
	MapperKey  string `json:"mapperKey"`
}

// renderBatchesModule renders the table module: the imports of the mappers a mapping names, whose own
// deps sit inside the mapper modules, one registerInputMapperTuple each, then replaceBatches with the
// whole table. Deterministic: mappers by key, batches by id, mappings as extracted.
func renderBatchesModule(sites []requestbatch.Site, entries []purefunctions.Entry) string {
	defined := make(map[string]bool, len(entries))
	for _, entry := range entries {
		defined[entry.Key()] = true
	}
	var out strings.Builder
	out.WriteString("// GENERATED by mion (the batch transport). Do not edit.\n")
	out.WriteString("import {registerInputMapperTuple} from '@mionjs/core';\n")
	out.WriteString("import {replaceBatches} from '@mionjs/router';\n")
	var mapperKeys []string
	for _, key := range referencedMapperKeys(sites) {
		if !defined[key] {
			continue // BAT007 already reported; the server has nothing to register
		}
		mapperKeys = append(mapperKeys, key)
		basename := entrymodules.ModuleName(key, entrymodules.KindPureFn)
		out.WriteString("import {" + entrymodules.BindingName(basename) + "} from '" + ensureDotPrefix(basename) + moduleFileExt + "';\n")
	}
	for _, key := range mapperKeys {
		basename := entrymodules.ModuleName(key, entrymodules.KindPureFn)
		out.WriteString("registerInputMapperTuple(" + jsquote.Single(key) + ", " + entrymodules.BindingName(basename) + ");\n")
	}
	table := make(map[string]batchTableEntry, len(sites))
	for _, site := range sites {
		if _, seen := table[site.BatchId]; seen {
			continue // the same batch at a second call site (BAT003 flags a differing one)
		}
		entry := batchTableEntry{Routes: append([]string(nil), site.RouteIds...)}
		for _, mapping := range site.Mappings {
			entry.Mappings = append(entry.Mappings, batchTableMapping(mapping))
		}
		table[site.BatchId] = entry
	}
	var encoded bytes.Buffer
	encoder := json.NewEncoder(&encoded)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(table); err != nil {
		panic("batch table is not encodable: " + err.Error())
	}
	out.WriteString("replaceBatches(" + strings.TrimSuffix(encoded.String(), "\n") + ");\n")
	return out.String()
}

// setHasBatches records the program's batch presence for the transform.
func (sess *Session) setHasBatches(has bool) {
	sess.hasBatchesMemo = &has
}

// noteOwnBatches folds a per-scan extraction into the memo: a file that just gained its first batch must
// flip the transform's switch before the next generate runs.
func (sess *Session) noteOwnBatches(sites []requestbatch.Site) {
	if len(sites) > 0 {
		sess.setHasBatches(true)
	}
}

// hasBatches is memoised and computed on demand, so `mion compile`, which transforms before it generates,
// decides the same way the bundler lane does.
func (sess *Session) hasBatches() bool {
	if sess.hasBatchesMemo != nil {
		return *sess.hasBatchesMemo
	}
	sites, _ := sess.collectProgramBatches()
	sess.setHasBatches(len(sites) > 0)
	return *sess.hasBatchesMemo
}

// importsRouter tells a server, whose router may hide behind a wrapper, from a client (never a misconfiguration).
// The router's own files import it by relative path, so a file the router package owns counts too.
func (sess *Session) importsRouter() bool {
	if sess.importsRouterMemo != nil {
		return *sess.importsRouterMemo
	}
	imports := false
	if sess.Program != nil && sess.Program.TS != nil {
		ownerByDir := map[string]string{}
		for _, sourceFile := range sess.Program.TS.SourceFiles() {
			if sourceFile == nil || sourceFile.IsDeclarationFile || strings.Contains(sourceFile.FileName(), "/node_modules/") {
				continue
			}
			if strings.Contains(sourceFile.Text(), routerinit.RouterModule) {
				imports = true
				break
			}
			dir := filepath.Dir(sourceFile.FileName())
			owner, seen := ownerByDir[dir]
			if !seen {
				owner, _ = marker.PackageOfFile(sourceFile.FileName(), sess.Program.FS)
				ownerByDir[dir] = owner
			}
			if owner == routerinit.RouterModule {
				imports = true
				break
			}
		}
	}
	sess.importsRouterMemo = &imports
	return imports
}

// routerInitSites finds the router-init modules among files, memoised per file for the current Program.
func (sess *Session) routerInitSites(files []string) []routerinit.Site {
	if sess.Program == nil || len(files) == 0 {
		return nil
	}
	return routerinit.ExtractFromProgramCached(sess.checker, sess.marker, sess.Program, files, sess.routerInitFileCache)
}

// routerInitFiles rides the generate response so a dev host re-transforms them when the batch module first appears.
func (sess *Session) routerInitFiles() []string {
	return routerinit.Files(sess.routerInitSites(sess.programSourceFiles()))
}

// routerInitReplacements appends the batch import to each router-init module when the program holds
// a batch: one point insertion at end of file, so no existing line moves. Under TransformRelative the
// specifier is already relative to the file; otherwise the virtual `rtrpc:/` form goes out for the
// compile lane's emit-time relativizer.
func (sess *Session) routerInitReplacements(files []string) []protocol.Replacement {
	sites := sess.routerInitSites(files)
	if len(sites) == 0 || !sess.hasBatches() {
		return nil
	}
	outDir := ""
	if sess.opts.TransformRelative {
		outDir = sess.resolveOutDir()
	}
	out := make([]protocol.Replacement, 0, len(sites))
	for _, site := range sites {
		specifier := constants.RpcModulePrefix + constants.BatchesModuleFile
		if outDir != "" {
			if rel := relUserToRpc(site.FilePath, outDir, constants.BatchesModuleFile); rel != "" {
				specifier = rel
			}
		}
		out = append(out, protocol.Replacement{File: site.FilePath, Start: site.End, End: site.End, Text: "\nimport '" + specifier + "';\n"})
	}
	return out
}
