package resolver

// The batch transport, generated by the SERVER build.
//
// A batch is written in client code (`batch([...])` with inline `inputFrom()`
// mappers), but the server must know every batch id, its routes and its
// mappers before it runs one. This file reads them from the BATCH SOURCE
// program (the session's own program, or the separate one
// Options.ClientTsconfig names) and writes everything the server loads under
// its own output root:
//
//	<outDir>/rpc/batches.generated.js   the table, registered via replaceBatches
//	<outDir>/rpc/pf/<ns>/<fn>.js        one module per referenced inline mapper
//
// Relative imports only: the batch module imports each mapper as
// `./pf/<ns>/<fn>.js`, and OpTransform appends `import 'rtrpc:/batches.generated.js'`
// to every module that calls createMionRouter (relativized against that file).
// The server never reads a client tree, no path leaks into a generated file,
// and every lane (bundler plugin, `mion compile`) gets the same output because
// both funnel through OpGenerate + OpTransform.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/mionkit/mion/ts-go-runtypes/internal/cachegen/purefunctions"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/entrymodules"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/program"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/requestbatch"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/routerinit"
	"github.com/mionkit/mion/ts-go-runtypes/internal/constants"
	"github.com/mionkit/mion/ts-go-runtypes/internal/diagnostics"
	"github.com/mionkit/mion/ts-go-runtypes/internal/jsquote"
	"github.com/mionkit/mion/ts-go-runtypes/internal/protocol"
	"github.com/mionkit/mion/ts-go-runtypes/internal/textpos"
)

// batchesModuleBasename is the table module's basename under rpc/ (the
// materializer appends the module extension).
var batchesModuleBasename = strings.TrimSuffix(constants.BatchesModuleFile, moduleFileExt)

// rpcCollection is what one read of the batch source yields.
type rpcCollection struct {
	// sites are the batch source's `batch([...])` calls.
	sites []requestbatch.Site
	// entries are the inline mappers the batches reference plus the pure fns
	// those mappers call, sorted by key.
	entries []purefunctions.Entry
	// sourceDiags are the batch source program's own batch diagnostics, kept
	// ONLY when it is a separate program (the own program's ride the generate
	// response already); mapperDiags are the BAT007 misses, kept always.
	sourceDiags []diagnostics.Diagnostic
	mapperDiags []diagnostics.Diagnostic
	// files are the batch source's files holding a batch or a mapper, for the
	// dev host to watch; empty when the batch source is the own program.
	files []string
}

// batchSourceSession returns the session the batch transport is read from:
// this one, or the lazily built client session (rebuilt when a stamped file
// changed). A client tsconfig that fails to load is an error naming it.
func (sess *Session) batchSourceSession() (*Session, error) {
	if sess.opts.ClientTsconfig == "" {
		return sess, nil
	}
	if sess.batchSource != nil && !sess.batchSourceStale() {
		return sess.batchSource, nil
	}
	sess.closeBatchSource()
	tsconfig := sess.absPath(sess.opts.ClientTsconfig)
	prog, err := program.New(program.Options{Cwd: filepath.Dir(tsconfig), TsconfigPath: tsconfig, SingleThreaded: sess.opts.SingleThreaded})
	if err != nil {
		return nil, fmt.Errorf("clientTsconfig %s: %w", tsconfig, err)
	}
	// The client session only EXTRACTS (batches, mappers): no output root, no
	// disk cache, no reports of its own.
	opts := sess.opts
	opts.ClientTsconfig = ""
	opts.Cwd = filepath.Dir(tsconfig)
	opts.TsconfigPath = tsconfig
	opts.TsconfigGenDir = ""
	opts.GenDir = ""
	opts.CacheDir = ""
	opts.CacheFollowsIncremental = false
	opts.PureFnReportWire = false
	opts.PureFnReportFile = false
	client, err := New(prog, opts)
	if err != nil {
		return nil, fmt.Errorf("clientTsconfig %s: %w", tsconfig, err)
	}
	sess.batchSource = client
	sess.batchSourceStamps = stampProgramFiles(prog, tsconfig)
	sess.hasBatchesMemo = nil
	return client, nil
}

// closeBatchSource releases the client session, if any.
func (sess *Session) closeBatchSource() {
	if sess.batchSource == nil {
		return
	}
	sess.batchSource.Close()
	sess.batchSource = nil
	sess.batchSourceStamps = nil
	sess.hasBatchesMemo = nil
}

// stampProgramFiles records mtime + size for every non-declaration source
// file of prog plus its tsconfig, the set a later generate compares against.
func stampProgramFiles(prog *program.Program, tsconfig string) map[string]string {
	stamps := map[string]string{tsconfig: fileStamp(tsconfig)}
	for _, sourceFile := range prog.TS.SourceFiles() {
		if sourceFile == nil || sourceFile.IsDeclarationFile {
			continue
		}
		stamps[sourceFile.FileName()] = fileStamp(sourceFile.FileName())
	}
	return stamps
}

// fileStamp is "<mtime>-<size>", or "" for a file that cannot be stat'ed.
func fileStamp(path string) string {
	info, err := os.Stat(path)
	if err != nil {
		return ""
	}
	return strconv.FormatInt(info.ModTime().UnixNano(), 10) + "-" + strconv.FormatInt(info.Size(), 10)
}

// batchSourceStale reports whether any stamped client file changed or went
// away since the client session was built.
func (sess *Session) batchSourceStale() bool {
	for path, stamp := range sess.batchSourceStamps {
		if fileStamp(path) != stamp {
			return true
		}
	}
	return false
}

// collectRpc reads the batch source: every batch site, the inline mappers the
// sites reference (with the pure fns those mappers call), and the files a
// separate batch source must be watched at. Sets the hasBatches memo.
func (sess *Session) collectRpc() (rpcCollection, error) {
	source, err := sess.batchSourceSession()
	if err != nil {
		return rpcCollection{}, err
	}
	sites, sourceDiags := source.collectProgramBatches()
	sess.setHasBatches(len(sites) > 0)
	out := rpcCollection{sites: sites}
	separate := source != sess
	if separate {
		out.sourceDiags = sourceDiags
	}
	if len(sites) == 0 {
		return out, nil
	}
	referenced := referencedMapperKeys(sites)
	var entryFiles []string
	if len(referenced) > 0 {
		programEntries, _, _ := source.extractProgramPureFns(nil)
		byKey := make(map[string]purefunctions.Entry, len(programEntries))
		for _, entry := range programEntries {
			byKey[entry.Key()] = entry
		}
		// The referenced mappers plus the closure of the pure fns they call;
		// a dep the program does not define is stubbed at render time.
		queue := append([]string(nil), referenced...)
		seen := map[string]bool{}
		for len(queue) > 0 {
			key := queue[0]
			queue = queue[1:]
			if seen[key] {
				continue
			}
			seen[key] = true
			entry, ok := byKey[key]
			if !ok {
				continue
			}
			out.entries = append(out.entries, entry)
			entryFiles = append(entryFiles, entry.FilePath)
			queue = append(queue, entry.PureFnDependencies...)
		}
		sort.Slice(out.entries, func(i, j int) bool { return out.entries[i].Key() < out.entries[j].Key() })
		for _, key := range referenced {
			if _, ok := byKey[key]; !ok {
				out.mapperDiags = append(out.mapperDiags, missingMapperDiag(source, sites, key))
			}
		}
	}
	if separate {
		out.files = uniqueSortedStrings(append(requestbatch.Files(sites), entryFiles...))
	}
	return out, nil
}

// referencedMapperKeys returns the sorted unique inline mapper keys
// (`rt::<hash>`) the sites' mappings name. Named mappers (`mionjs::<name>`)
// are registered by the server itself and need no module.
func referencedMapperKeys(sites []requestbatch.Site) []string {
	seen := map[string]bool{}
	var keys []string
	prefix := purefunctions.AnonymousNamespace + "::"
	for _, site := range sites {
		for _, mapping := range site.Mappings {
			if !strings.HasPrefix(mapping.MapperKey, prefix) || seen[mapping.MapperKey] {
				continue
			}
			seen[mapping.MapperKey] = true
			keys = append(keys, mapping.MapperKey)
		}
	}
	sort.Strings(keys)
	return keys
}

// missingMapperDiag reports BAT007 at the first batch call naming key.
func missingMapperDiag(source *Session, sites []requestbatch.Site, key string) diagnostics.Diagnostic {
	for _, site := range sites {
		for _, mapping := range site.Mappings {
			if mapping.MapperKey != key {
				continue
			}
			diagSite := diagnostics.Site{FilePath: site.FilePath}
			if sourceFile := source.Program.SourceFile(site.FilePath); sourceFile != nil {
				diagSite.StartLine, diagSite.StartCol = textpos.LineCol(sourceFile, site.Start)
				diagSite.EndLine, diagSite.EndCol = textpos.LineCol(sourceFile, site.End)
			}
			return diagnostics.New(diagnostics.CodeBatchMapperMissing, diagSite, key)
		}
	}
	return diagnostics.New(diagnostics.CodeBatchMapperMissing, diagnostics.Site{}, key)
}

// generateRpc writes `<outDir>/rpc/` for the collection (write-on-change,
// stale mapper modules pruned) and returns the table module's absolute path,
// or "" after removing `rpc/` when the batch source holds no batch.
func generateRpc(outDir string, collection rpcCollection, emitMode constants.EmitMode) (string, error) {
	rpcDir := filepath.Join(outDir, constants.RpcModuleDir)
	if len(collection.sites) == 0 {
		if err := os.RemoveAll(rpcDir); err != nil {
			return "", unwritableOutDirError(rpcDir, err)
		}
		return "", nil
	}
	// Always per-entry modules, whatever the project's moduleMode: the table
	// imports each mapper by its own path, so the layout is one.
	graph := purefunctions.CollectEntries(collection.entries, emitMode)
	var missing []string
	for _, entry := range graph {
		for _, dep := range entry.SoftDeps {
			if _, ok := graph[dep]; !ok {
				missing = append(missing, dep)
			}
		}
	}
	graph.AddMissingStubs(missing)
	rendered, err := entrymodules.RenderGrouped(graph, nil)
	if err != nil {
		return "", fmt.Errorf("batch transport: %w", err)
	}
	files := make(map[string]string, len(rendered)+1)
	for basename, source := range rendered {
		files[basename] = relativizeModuleImports(basename, source)
	}
	files[batchesModuleBasename] = renderBatchesModule(collection.sites, collection.entries)
	if err := os.MkdirAll(rpcDir, 0o755); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	if _, err := materializeModules(rpcDir, files); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	if err := pruneStaleModules(rpcDir, files); err != nil {
		return "", unwritableOutDirError(rpcDir, err)
	}
	return filepath.Join(rpcDir, constants.BatchesModuleFile), nil
}

// batchTableEntry / batchTableMapping mirror @mionjs/router's BatchDefinition,
// the shape replaceBatches takes.
type batchTableEntry struct {
	Routes   []string            `json:"routes"`
	Mappings []batchTableMapping `json:"mappings,omitempty"`
}

type batchTableMapping struct {
	FromId     string `json:"fromId"`
	ToId       string `json:"toId"`
	ParamIndex int    `json:"paramIndex"`
	MapperKey  string `json:"mapperKey"`
}

// renderBatchesModule renders the table module: the mapper imports (only the
// mappers a mapping names; their own deps ride inside the mapper modules), one
// registerInputMapperTuple per mapper, then replaceBatches with the whole
// table. Deterministic: mappers by key, batches by id, mappings as extracted
// (sorted by target and argument index).
func renderBatchesModule(sites []requestbatch.Site, entries []purefunctions.Entry) string {
	defined := make(map[string]bool, len(entries))
	for _, entry := range entries {
		defined[entry.Key()] = true
	}
	var out strings.Builder
	out.WriteString("// GENERATED by mion (the batch transport). Do not edit.\n")
	out.WriteString("import {registerInputMapperTuple} from '@mionjs/core';\n")
	out.WriteString("import {replaceBatches} from '@mionjs/router';\n")
	var mapperKeys []string
	for _, key := range referencedMapperKeys(sites) {
		if !defined[key] {
			continue // BAT007 already reported; the server has nothing to register
		}
		mapperKeys = append(mapperKeys, key)
		basename := entrymodules.ModuleName(key, entrymodules.KindPureFn)
		out.WriteString("import {" + entrymodules.BindingName(basename) + "} from '" + ensureDotPrefix(basename) + moduleFileExt + "';\n")
	}
	for _, key := range mapperKeys {
		basename := entrymodules.ModuleName(key, entrymodules.KindPureFn)
		out.WriteString("registerInputMapperTuple(" + jsquote.Single(key) + ", " + entrymodules.BindingName(basename) + ");\n")
	}
	table := make(map[string]batchTableEntry, len(sites))
	for _, site := range sites {
		if _, seen := table[site.BatchId]; seen {
			continue // the same batch at a second call site (BAT003 flags a differing one)
		}
		entry := batchTableEntry{Routes: append([]string(nil), site.RouteIds...)}
		for _, mapping := range site.Mappings {
			entry.Mappings = append(entry.Mappings, batchTableMapping(mapping))
		}
		table[site.BatchId] = entry
	}
	var encoded bytes.Buffer
	encoder := json.NewEncoder(&encoded)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(table); err != nil {
		panic("batch table is not encodable: " + err.Error())
	}
	out.WriteString("replaceBatches(" + strings.TrimSuffix(encoded.String(), "\n") + ");\n")
	return out.String()
}

// setHasBatches records the batch source's batch presence for the transform.
func (sess *Session) setHasBatches(has bool) {
	sess.hasBatchesMemo = &has
}

// noteOwnBatches folds a per-scan batch extraction into the memo when the
// batch source is the own program: a file that just gained its first batch
// must flip the transform's switch before the next generate runs.
func (sess *Session) noteOwnBatches(sites []requestbatch.Site) {
	if sess.opts.ClientTsconfig == "" && len(sites) > 0 {
		sess.setHasBatches(true)
	}
}

// hasBatches reports whether the batch source holds at least one batch call.
// Memoised; computed on demand so `mion compile` (which transforms before it
// generates) decides the same way the bundler lane does. A client tsconfig
// that fails to load reads as "no batches" here and fails generate loudly.
func (sess *Session) hasBatches() bool {
	if sess.hasBatchesMemo != nil {
		return *sess.hasBatchesMemo
	}
	source, err := sess.batchSourceSession()
	if err != nil {
		return false
	}
	sites, _ := source.collectProgramBatches()
	sess.setHasBatches(len(sites) > 0)
	return *sess.hasBatchesMemo
}

// routerInitSites finds the router-init modules among files (memoised per
// file for the current Program).
func (sess *Session) routerInitSites(files []string) []routerinit.Site {
	if sess.Program == nil || len(files) == 0 {
		return nil
	}
	return routerinit.ExtractFromProgramCached(sess.checker, sess.marker, sess.Program, files, sess.routerInitFileCache)
}

// routerInitFiles is the whole program's sorted router-init file list, the
// generate echo a dev host re-transforms when the batch module first appears.
func (sess *Session) routerInitFiles() []string {
	if sess.Program == nil || sess.Program.TS == nil {
		return nil
	}
	sourceFiles := sess.Program.TS.SourceFiles()
	files := make([]string, 0, len(sourceFiles))
	for _, sourceFile := range sourceFiles {
		if sourceFile == nil || sourceFile.IsDeclarationFile {
			continue
		}
		files = append(files, sourceFile.FileName())
	}
	return routerinit.Files(sess.routerInitSites(files))
}

// routerInitReplacements builds the batch import appended to each router-init
// module among files, when the batch source holds a batch: one point
// insertion at end of file, so no existing line moves. In files mode
// (TransformRelative) the specifier is already relative to the file; otherwise
// the virtual `rtrpc:/` form rides through for the compile lane's emit-time
// relativizer.
func (sess *Session) routerInitReplacements(files []string) []protocol.Replacement {
	sites := sess.routerInitSites(files)
	if len(sites) == 0 || !sess.hasBatches() {
		return nil
	}
	outDir := ""
	if sess.opts.TransformRelative {
		outDir = sess.resolveOutDir()
	}
	out := make([]protocol.Replacement, 0, len(sites))
	for _, site := range sites {
		specifier := constants.RpcModulePrefix + constants.BatchesModuleFile
		if outDir != "" {
			if rel := relUserToRpc(site.FilePath, outDir, constants.BatchesModuleFile); rel != "" {
				specifier = rel
			}
		}
		out = append(out, protocol.Replacement{File: site.FilePath, Start: site.End, End: site.End, Text: "\nimport '" + specifier + "';\n"})
	}
	return out
}

// uniqueSortedStrings dedupes and sorts.
func uniqueSortedStrings(values []string) []string {
	seen := make(map[string]bool, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}
