package resolver_test

// The batch transport the SERVER build generates: `<outDir>/rpc/` holds the
// batch table module and one module per inline mapper, relative imports only,
// and the transform appends the table's import to every module that creates
// the router. Fixtures reuse the batches lane's client stand-ins
// (batch_test.go) plus an ambient `@mionjs/router` for the server half.

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/microsoft/typescript-go/shim/tspath"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/program"
	"github.com/mionkit/mion/ts-go-runtypes/internal/compiler/resolver"
	"github.com/mionkit/mion/ts-go-runtypes/internal/protocol"
)

// routerDTS is the ambient stand-in for the `@mionjs/router` surface the
// router-init detector reads: the factory's declaring module is what matters.
const routerDTS = `declare module '@mionjs/router' {
  export function createMionRouter(opts?: unknown): {initRoutes: (routes: unknown) => unknown};
}
`

// serverTS is the module that creates the router, the batch import target.
const serverTS = `import {createMionRouter} from '@mionjs/router';
export const mion = createMionRouter();
export const api = mion.initRoutes({});
`

// rpcSources is a shared-root program: the client half (a.ts with an inline
// mapper, b.ts with a plain batch) and the server half in one tsconfig.
func rpcSources() map[string]string {
	sources := map[string]string{"router.d.ts": routerDTS, "server.ts": serverTS}
	for name, content := range batchSources {
		sources[name] = content
	}
	return sources
}

// serverOnlySources is the same server with no batch anywhere.
func serverOnlySources() map[string]string {
	return map[string]string{
		"router.d.ts": routerDTS,
		"server.ts":   serverTS,
		"client.d.ts": batchClientDTS,
		"routes.ts":   batchRoutesTS,
	}
}

var (
	mapperImportRE = regexp.MustCompile(`import \{(__rt_pf\$2Frt\$2F[A-Za-z0-9_$]+)\} from '(\./pf/rt/[^']+\.js)';`)
	specifierRE    = regexp.MustCompile(`from '([^']+)'`)
	batchIdRE      = regexp.MustCompile(`"(b_[A-Za-z0-9_-]+)"`)
	mapperKeyRE    = regexp.MustCompile(`'(rt::[A-Za-z0-9_-]+)'`)
)

func readRpcModule(t *testing.T, outDir string) string {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(outDir, "rpc", "batches.generated.js"))
	if err != nil {
		t.Fatalf("read batch module: %v", err)
	}
	return string(content)
}

// readTree returns every file under dir keyed by its slash-relative path.
func readTree(t *testing.T, dir string) map[string]string {
	t.Helper()
	tree := map[string]string{}
	err := filepath.WalkDir(dir, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil || entry.IsDir() {
			return walkErr
		}
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		rel, _ := filepath.Rel(dir, path)
		tree[filepath.ToSlash(rel)] = string(content)
		return nil
	})
	if err != nil && !os.IsNotExist(err) {
		t.Fatalf("walk %s: %v", dir, err)
	}
	return tree
}

func generate(t *testing.T, r *resolver.Session) protocol.Response {
	t.Helper()
	gen := r.Dispatch(protocol.Request{Op: protocol.OpGenerate})
	if gen.Error != "" {
		t.Fatalf("generate: %s", gen.Error)
	}
	return gen
}

func transform(t *testing.T, r *resolver.Session, file string) string {
	t.Helper()
	tr := r.Dispatch(protocol.Request{Op: protocol.OpTransform, Files: []string{file}})
	if tr.Error != "" {
		t.Fatalf("transform %s: %s", file, tr.Error)
	}
	return tr.Transformed[file].Code
}

// TestRpc_GenerateWritesTableAndMappers: one generate writes the table module
// and the referenced mapper module under rpc/, every import relative, and the
// echo names the module, the router-init file and nothing to watch (the batch
// source is the own program).
func TestRpc_GenerateWritesTableAndMappers(t *testing.T) {
	outDir := t.TempDir()
	r := setupGen(t, rpcSources(), outDir)
	gen := generate(t, r)

	want := filepath.Join(outDir, "rpc", "batches.generated.js")
	if gen.BatchesModule != want {
		t.Fatalf("BatchesModule = %q, want %q", gen.BatchesModule, want)
	}
	module := readRpcModule(t, outDir)
	if !strings.HasPrefix(module, "// GENERATED by mion") {
		t.Errorf("module lacks the generated header:\n%s", module)
	}
	for _, line := range []string{
		"import {registerInputMapperTuple} from '@mionjs/core';",
		"import {replaceBatches} from '@mionjs/router';",
		"replaceBatches({",
	} {
		if !strings.Contains(module, line) {
			t.Errorf("module lacks %q:\n%s", line, module)
		}
	}
	imports := mapperImportRE.FindAllStringSubmatch(module, -1)
	if len(imports) != 1 {
		t.Fatalf("expected exactly one mapper import, got %d:\n%s", len(imports), module)
	}
	binding, specifier := imports[0][1], imports[0][2]
	keys := mapperKeyRE.FindAllStringSubmatch(module, -1)
	if len(keys) == 0 {
		t.Fatalf("module registers no mapper key:\n%s", module)
	}
	mapperKey := keys[0][1]
	if !strings.Contains(module, "registerInputMapperTuple('"+mapperKey+"', "+binding+");") {
		t.Errorf("module does not register %s through %s:\n%s", mapperKey, binding, module)
	}
	// every specifier is relative or a package: never a path into a project
	for _, match := range specifierRE.FindAllStringSubmatch(module, -1) {
		if !strings.HasPrefix(match[1], "./") && !strings.HasPrefix(match[1], "@mionjs/") {
			t.Errorf("non-relative specifier %q in the batch module", match[1])
		}
	}
	if ids := batchIdRE.FindAllString(module, -1); len(ids) != 2 {
		t.Errorf("expected the two fixture batches in the table, got %v", ids)
	}
	if !strings.Contains(module, `"mapperKey":"`+mapperKey+`"`) {
		t.Errorf("the table does not name the mapper %s:\n%s", mapperKey, module)
	}
	// the mapper module itself: the body, the key, under rpc/pf/rt/
	mapperPath := filepath.Join(outDir, "rpc", filepath.FromSlash(strings.TrimPrefix(specifier, "./")))
	mapperSource, err := os.ReadFile(mapperPath)
	if err != nil {
		t.Fatalf("mapper module %s: %v", mapperPath, err)
	}
	if !strings.Contains(string(mapperSource), "u.id") || !strings.Contains(string(mapperSource), "'"+mapperKey+"'") {
		t.Errorf("mapper module does not carry the body and key:\n%s", mapperSource)
	}
	// the client transform injects the same key the server registers
	if code := transform(t, r, "a.ts"); !strings.Contains(code, "'"+mapperKey+"'") {
		t.Errorf("client transform of a.ts does not carry %s:\n%s", mapperKey, code)
	}
	// echoes: the router-init module is named, joins SiteFiles, nothing to watch
	serverAbs := tspath.ResolvePath(r.Program.TS.GetCurrentDirectory(), "server.ts")
	if len(gen.RouterInitFiles) != 1 || gen.RouterInitFiles[0] != serverAbs {
		t.Errorf("RouterInitFiles = %v, want [%s]", gen.RouterInitFiles, serverAbs)
	}
	if !containsString(gen.SiteFiles, serverAbs) {
		t.Errorf("SiteFiles %v must include the router-init module %s", gen.SiteFiles, serverAbs)
	}
	if len(gen.BatchSourceFiles) != 0 {
		t.Errorf("own-program batch source must echo no watch files, got %v", gen.BatchSourceFiles)
	}
}

// TestRpc_TransformAppendsImportToRouterInit: the router-init module gets the
// table import appended, relativized in files mode and virtual otherwise, in
// both wire modes; a program without batches gets nothing.
func TestRpc_TransformAppendsImportToRouterInit(t *testing.T) {
	outDir := t.TempDir()
	r := setupGen(t, rpcSources(), outDir)
	generate(t, r)
	serverAbs := tspath.ResolvePath(r.Program.TS.GetCurrentDirectory(), "server.ts")
	rel, err := filepath.Rel(filepath.Dir(serverAbs), filepath.Join(outDir, "rpc", "batches.generated.js"))
	if err != nil {
		t.Fatal(err)
	}
	rel = filepath.ToSlash(rel)
	if !strings.HasPrefix(rel, "./") && !strings.HasPrefix(rel, "../") {
		rel = "./" + rel
	}
	wantImport := "\nimport '" + rel + "';\n"

	code := transform(t, r, "server.ts")
	if !strings.HasSuffix(code, wantImport) {
		t.Errorf("go-mode transform does not end with %q:\n%s", wantImport, code)
	}
	if strings.Contains(code, "rtrpc:") {
		t.Errorf("files-mode transform leaked the virtual specifier:\n%s", code)
	}
	// the body is untouched: the import is appended, nothing prepended or moved
	if !strings.HasPrefix(code, serverTS) {
		t.Errorf("transform changed the module body:\n%s", code)
	}

	edits := r.Dispatch(protocol.Request{Op: protocol.OpTransform, Files: []string{"server.ts"}, EmitEdits: true})
	if edits.Error != "" {
		t.Fatalf("edits transform: %s", edits.Error)
	}
	result := edits.Transformed["server.ts"]
	found := false
	for _, edit := range result.Edits {
		if edit.Text == wantImport && edit.Start == len(serverTS) && edit.End == len(serverTS) {
			found = true
		}
	}
	if !found {
		t.Errorf("edits mode lacks the end-of-file import edit %q: %+v", wantImport, result.Edits)
	}

	// virtual form when the session does not relativize (the compile lane)
	virtual := setupInlineWith(t, rpcSources(), func(programOpts *program.Options, resolverOpts *resolver.Options) {
		programOpts.SingleThreaded = true
		resolverOpts.SingleThreaded = true
		resolverOpts.GenDir = t.TempDir()
	})
	if code := transform(t, virtual, "server.ts"); !strings.HasSuffix(code, "\nimport 'rtrpc:/batches.generated.js';\n") {
		t.Errorf("virtual transform does not end with the rtrpc import:\n%s", code)
	}

	// no batch anywhere: nothing appended, no rpc/ written
	quiet := setupGen(t, serverOnlySources(), t.TempDir())
	gen := generate(t, quiet)
	if gen.BatchesModule != "" {
		t.Errorf("a program without batches must echo no module, got %q", gen.BatchesModule)
	}
	if code := transform(t, quiet, "server.ts"); strings.Contains(code, "batches.generated") {
		t.Errorf("a program without batches must not import the table:\n%s", code)
	}
}

// TestRpc_RouterInitDetectionShapes: the detector follows the checker, so an
// alias, a namespace import and a local barrel match, while a type-only import
// and a same-named local function do not.
func TestRpc_RouterInitDetectionShapes(t *testing.T) {
	sources := rpcSources()
	delete(sources, "server.ts")
	sources["alias.ts"] = "import {createMionRouter as create} from '@mionjs/router';\nexport const m = create();\n"
	sources["ns.ts"] = "import * as router from '@mionjs/router';\nexport const m = router.createMionRouter();\n"
	sources["barrel.ts"] = "export {createMionRouter} from '@mionjs/router';\n"
	sources["viaBarrel.ts"] = "import {createMionRouter} from './barrel.ts';\nexport const m = createMionRouter();\n"
	sources["typeOnly.ts"] = "import type {createMionRouter} from '@mionjs/router';\nexport type Factory = typeof createMionRouter;\n"
	sources["local.ts"] = "function createMionRouter() { return 1; }\nexport const m = createMionRouter();\n"
	r := setupGen(t, sources, t.TempDir())
	gen := generate(t, r)

	want := map[string]bool{"alias.ts": true, "ns.ts": true, "viaBarrel.ts": true, "typeOnly.ts": false, "local.ts": false, "barrel.ts": false}
	for file, expect := range want {
		code := transform(t, r, file)
		if got := strings.Contains(code, "batches.generated"); got != expect {
			t.Errorf("%s: import appended = %v, want %v:\n%s", file, got, expect, code)
		}
	}
	cwd := r.Program.TS.GetCurrentDirectory()
	var wantFiles []string
	for file, expect := range want {
		if expect {
			wantFiles = append(wantFiles, tspath.ResolvePath(cwd, file))
		}
	}
	sort.Strings(wantFiles)
	if strings.Join(gen.RouterInitFiles, ",") != strings.Join(wantFiles, ",") {
		t.Errorf("RouterInitFiles = %v, want %v", gen.RouterInitFiles, wantFiles)
	}
}

// TestRpc_ByNameMapperNeedsNoModule: a `mionjs::<name>` mapper is registered by
// the server itself, so the table names it and no module is written.
func TestRpc_ByNameMapperNeedsNoModule(t *testing.T) {
	sources := rpcSources()
	sources["a.ts"] = `import {batch, inputFrom} from '@mionjs/client';
import {routes} from './routes.ts';
const user = routes.users.getById(1);
export const b = batch([user, routes.orders.getById(inputFrom(user, 'toUserId'))]);
`
	outDir := t.TempDir()
	r := setupGen(t, sources, outDir)
	generate(t, r)
	module := readRpcModule(t, outDir)
	if !strings.Contains(module, `"mapperKey":"mionjs::toUserId"`) {
		t.Errorf("table does not name the server mapper:\n%s", module)
	}
	if strings.Contains(module, "registerInputMapperTuple('") || mapperImportRE.MatchString(module) {
		t.Errorf("a by-name mapper must import and register nothing:\n%s", module)
	}
	if _, err := os.Stat(filepath.Join(outDir, "rpc", "pf")); !os.IsNotExist(err) {
		t.Errorf("rpc/pf must not exist for by-name mappers only (stat err = %v)", err)
	}
}

// TestRpc_NoBatchesRemovesRpc: a later generate from a program that lost its
// batches removes the whole rpc/ folder.
func TestRpc_NoBatchesRemovesRpc(t *testing.T) {
	outDir := t.TempDir()
	generate(t, setupGen(t, rpcSources(), outDir))
	if _, err := os.Stat(filepath.Join(outDir, "rpc")); err != nil {
		t.Fatalf("rpc/ expected after the first generate: %v", err)
	}
	gen := generate(t, setupGen(t, serverOnlySources(), outDir))
	if gen.BatchesModule != "" {
		t.Errorf("BatchesModule = %q, want empty", gen.BatchesModule)
	}
	if _, err := os.Stat(filepath.Join(outDir, "rpc")); !os.IsNotExist(err) {
		t.Errorf("rpc/ must be removed when no batch remains (stat err = %v)", err)
	}
}

// TestRpc_NoRouterInitWritesNoRpc: a program with batches but no router (a
// client project) has nothing to serve the table to, so no rpc/ is written
// and one left behind by an earlier server build is removed.
func TestRpc_NoRouterInitWritesNoRpc(t *testing.T) {
	outDir := t.TempDir()
	generate(t, setupGen(t, rpcSources(), outDir))
	if _, err := os.Stat(filepath.Join(outDir, "rpc")); err != nil {
		t.Fatalf("rpc/ expected after the server generate: %v", err)
	}
	clientOnly := rpcSources()
	delete(clientOnly, "server.ts")
	gen := generate(t, setupGen(t, clientOnly, outDir))
	if gen.BatchesModule != "" || len(gen.RouterInitFiles) != 0 {
		t.Errorf("a client-only program must echo no module and no router-init files, got %q / %v", gen.BatchesModule, gen.RouterInitFiles)
	}
	if _, err := os.Stat(filepath.Join(outDir, "rpc")); !os.IsNotExist(err) {
		t.Errorf("rpc/ must not exist for a program that creates no router (stat err = %v)", err)
	}
	// the client half still gets its ids and hashes: that is the transform's job, not the table's
	if code := transform(t, setupGen(t, clientOnly, t.TempDir()), "a.ts"); !strings.Contains(code, "'b_") || !strings.Contains(code, "'rt::") {
		t.Errorf("client transform lost the batch id or the mapper hash:\n%s", code)
	}
}

// TestRpc_StaleMapperPruned: a mapper that is no longer referenced is deleted
// on the next generate; the table imports only the current one.
func TestRpc_StaleMapperPruned(t *testing.T) {
	outDir := t.TempDir()
	generate(t, setupGen(t, rpcSources(), outDir))
	before := readTree(t, filepath.Join(outDir, "rpc"))
	var oldMapper string
	for path := range before {
		if strings.HasPrefix(path, "pf/rt/") {
			oldMapper = path
		}
	}
	if oldMapper == "" {
		t.Fatalf("no mapper module written: %v", before)
	}

	changed := rpcSources()
	changed["a.ts"] = strings.Replace(batchSources["a.ts"], "(u: {id: number}) => u.id", "(u: {name: string}) => u.name.length", 1)
	generate(t, setupGen(t, changed, outDir))
	after := readTree(t, filepath.Join(outDir, "rpc"))
	if _, stale := after[oldMapper]; stale {
		t.Errorf("stale mapper %s survived the regenerate", oldMapper)
	}
	var mappers []string
	for path := range after {
		if strings.HasPrefix(path, "pf/rt/") {
			mappers = append(mappers, path)
		}
	}
	if len(mappers) != 1 || !strings.Contains(after[mappers[0]], "u.name.length") {
		t.Errorf("expected exactly the new mapper, got %v", mappers)
	}
	if imports := mapperImportRE.FindAllStringSubmatch(after["batches.generated.js"], -1); len(imports) != 1 || "./"+mappers[0] != imports[0][2] {
		t.Errorf("table imports %v, want ./%s", imports, mappers[0])
	}
}

// TestRpc_DeterministicAndWriteOnChange: the same programs yield a
// byte-identical rpc/ tree across sessions, and an unchanged tree is never
// rewritten (mtimes stay put).
func TestRpc_DeterministicAndWriteOnChange(t *testing.T) {
	outDir := t.TempDir()
	r := setupGen(t, rpcSources(), outDir)
	generate(t, r)
	rpcDir := filepath.Join(outDir, "rpc")
	first := readTree(t, rpcDir)
	if len(first) < 2 {
		t.Fatalf("expected the table and a mapper, got %v", first)
	}
	mtimes := map[string]time.Time{}
	for path := range first {
		info, err := os.Stat(filepath.Join(rpcDir, filepath.FromSlash(path)))
		if err != nil {
			t.Fatal(err)
		}
		mtimes[path] = info.ModTime()
	}
	// a rewrite would need a later mtime, so make the clock observable
	time.Sleep(20 * time.Millisecond)
	generate(t, r)
	for path, stamp := range mtimes {
		info, err := os.Stat(filepath.Join(rpcDir, filepath.FromSlash(path)))
		if err != nil {
			t.Fatal(err)
		}
		if !info.ModTime().Equal(stamp) {
			t.Errorf("%s was rewritten although nothing changed", path)
		}
	}

	otherDir := t.TempDir()
	generate(t, setupGen(t, rpcSources(), otherDir))
	second := readTree(t, filepath.Join(otherDir, "rpc"))
	if len(second) != len(first) {
		t.Fatalf("tree sizes differ: %d vs %d", len(first), len(second))
	}
	for path, content := range first {
		if second[path] != content {
			t.Errorf("%s differs between two sessions over the same program", path)
		}
	}
}

// TestRpc_ClientTsconfigSeparateProject: the server session reads the batch
// source from a SEPARATE client project on disk, echoes that project's files
// for the dev watcher, rebuilds it when one of them changes, and names a bad
// tsconfig in its error.
func TestRpc_ClientTsconfigSeparateProject(t *testing.T) {
	clientDir := writeClientProject(t)
	outDir := t.TempDir()
	server := setupInlineWith(t, map[string]string{"router.d.ts": routerDTS, "server.ts": serverTS}, func(programOpts *program.Options, resolverOpts *resolver.Options) {
		programOpts.SingleThreaded = true
		resolverOpts.SingleThreaded = true
		resolverOpts.GenDir = outDir
		resolverOpts.TransformRelative = true
		resolverOpts.ClientTsconfig = filepath.Join(clientDir, "tsconfig.json")
	})
	gen := generate(t, server)
	if gen.BatchesModule == "" {
		t.Fatalf("no batch module generated from the client project; diagnostics: %+v", gen.Diagnostics)
	}
	module := readRpcModule(t, outDir)
	if ids := batchIdRE.FindAllString(module, -1); len(ids) != 1 {
		t.Errorf("expected the client's one batch, got %v:\n%s", ids, module)
	}
	if !mapperImportRE.MatchString(module) {
		t.Errorf("the client's inline mapper must be imported:\n%s", module)
	}
	if strings.Contains(module, clientDir) {
		t.Errorf("the module leaks the client project path:\n%s", module)
	}
	clientA := filepath.Join(clientDir, "src", "a.ts")
	if len(gen.BatchSourceFiles) != 1 || gen.BatchSourceFiles[0] != clientA {
		t.Errorf("BatchSourceFiles = %v, want [%s]", gen.BatchSourceFiles, clientA)
	}
	if code := transform(t, server, "server.ts"); !strings.Contains(code, "rpc/batches.generated.js';") {
		t.Errorf("server transform lacks the table import:\n%s", code)
	}

	// a client edit is picked up by the next generate (the stamps changed)
	time.Sleep(20 * time.Millisecond)
	writeTestFile(t, clientA, batchSources["a.ts"]+"export const c = batch([routes.orders.list(1)]);\n")
	gen = generate(t, server)
	if ids := batchIdRE.FindAllString(readRpcModule(t, outDir), -1); len(ids) != 2 {
		t.Errorf("expected two batches after the client edit, got %v", ids)
	}

	// a tsconfig that does not exist fails generate and names itself
	broken := setupInlineWith(t, map[string]string{"router.d.ts": routerDTS, "server.ts": serverTS}, func(programOpts *program.Options, resolverOpts *resolver.Options) {
		programOpts.SingleThreaded = true
		resolverOpts.SingleThreaded = true
		resolverOpts.GenDir = t.TempDir()
		resolverOpts.ClientTsconfig = filepath.Join(clientDir, "missing.json")
	})
	if resp := broken.Dispatch(protocol.Request{Op: protocol.OpGenerate}); resp.Error == "" || !strings.Contains(resp.Error, "missing.json") {
		t.Errorf("expected a generate error naming missing.json, got %q", resp.Error)
	}
}

// writeClientProject writes a real client project to disk: a tsconfig over
// src/, the batches fixtures, and the real marker package under node_modules
// so the brands resolve exactly as they do in a consumer.
func writeClientProject(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "tsconfig.json"), `{
  "compilerOptions": {
    "target": "ES2022", "module": "ESNext", "moduleResolution": "Bundler",
    "rootDir": "src", "noEmit": true, "strict": true, "allowImportingTsExtensions": true
  },
  "include": ["src"]
}
`)
	for rel, content := range realMarkerOverlay(t) {
		writeTestFile(t, filepath.Join(dir, filepath.FromSlash(rel)), content)
	}
	writeTestFile(t, filepath.Join(dir, "src", "client.d.ts"), batchClientDTS)
	writeTestFile(t, filepath.Join(dir, "src", "routes.ts"), batchRoutesTS)
	writeTestFile(t, filepath.Join(dir, "src", "a.ts"), batchSources["a.ts"])
	return dir
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func containsString(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
