package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

// moduleRoot is the Go module root (ts-go-runtypes/), derived from this source
// file's location so it resolves regardless of the caller's working directory.
func moduleRoot() string {
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))
}

// monorepoRoot is the repository root — the parent of the Go module — where the
// packages/ workspaces live. The emitted TS lands there, not under the Go module
// (a past migration moved the Go tree into ts-go-runtypes/ but left packages/ at
// the repo root, so the output path needs one more level up).
func monorepoRoot() string {
	return filepath.Dir(moduleRoot())
}

// configSourcePath is the Go file declaring the tsRuntypesPlugin struct whose
// json tags are the tsconfig plugin entry's recognised keys.
func configSourcePath() string {
	return filepath.Join(moduleRoot(), "cmd", "ts-runtypes", "config.go")
}

// outputPath is the committed TS mirror the plugin-option parity test reads.
func outputPath() string {
	return filepath.Join(monorepoRoot(), "packages", "ts-runtypes-devtools", "src", "go-generated", "tsconfig-plugin-keys.generated.ts")
}

// parsePluginKeys walks config.go and returns the json tag names of every field
// on the tsRuntypesPlugin struct, sorted, skipping "" and "-". This mirrors the
// runtime knownPluginKeys reflection in config.go — same struct, same rule — but
// via the AST, so this generator (package main of cmd/gen-plugin-keys) needs no
// import of cmd/ts-runtypes (also package main, hence unimportable).
func parsePluginKeys() ([]string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, configSourcePath(), nil, 0)
	if err != nil {
		return nil, err
	}
	var keys []string
	found := false
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || typeSpec.Name.Name != "tsRuntypesPlugin" {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			found = true
			for _, field := range structType.Fields.List {
				if field.Tag == nil {
					continue
				}
				tagValue, unquoteErr := strconv.Unquote(field.Tag.Value)
				if unquoteErr != nil {
					return nil, fmt.Errorf("unquote tag %s: %w", field.Tag.Value, unquoteErr)
				}
				name, _, _ := strings.Cut(reflect.StructTag(tagValue).Get("json"), ",")
				if name == "" || name == "-" {
					continue
				}
				keys = append(keys, name)
			}
		}
	}
	if !found {
		return nil, fmt.Errorf("tsRuntypesPlugin struct not found in %s", configSourcePath())
	}
	sort.Strings(keys)
	return keys, nil
}

// Generate builds the body of tsconfig-plugin-keys.generated.ts from the live
// tsRuntypesPlugin struct. Deterministic; depends only on config.go's json tags.
func Generate() (string, error) {
	keys, err := parsePluginKeys()
	if err != nil {
		return "", err
	}
	var out strings.Builder
	out.WriteString("// Code generated by cmd/gen-plugin-keys. DO NOT EDIT.\n")
	out.WriteString("// Source: cmd/ts-runtypes/config.go (tsRuntypesPlugin json tags).\n")
	out.WriteString("// Regenerate via `pnpm rtx core codegen pluginkeys` after changing the struct.\n")
	out.WriteString("//\n")
	out.WriteString("// The recognised keys of the tsconfig `plugins` entry. The plugin-option\n")
	out.WriteString("// parity test (test/plugin-option-parity.test.ts) checks these against the\n")
	out.WriteString("// bundler PluginOptions so a project option added to only one side fails CI.\n")
	out.WriteString("\n")
	out.WriteString("export const TSCONFIG_PLUGIN_KEYS = [\n")
	for _, key := range keys {
		fmt.Fprintf(&out, "  '%s',\n", key)
	}
	out.WriteString("] as const;\n")
	out.WriteString("\n")
	out.WriteString("export type TsconfigPluginKey = (typeof TSCONFIG_PLUGIN_KEYS)[number];\n")
	return out.String(), nil
}
