// Code generated by cmd/gen-fn-hashes. DO NOT EDIT.
// Source: internal/cachegen/operations (the registry + fnhash.go salt).
// Regenerate via `pnpm miondevx core codegen fnhashes` after adding or renaming a family.

/** The `<fnHash>` half of the runtime cache key `<fnHash>_<typeId>`, one per family, keyed by the
 *  run-types FAMILY name so a parsing row's value indexes this table directly.
 *
 *  Every hash is TYPE-INDEPENDENT and release-stable. This narrow table exists rather than a
 *  getFnHash call because that call pulls FN_HASHES, the whole variant table, into every browser
 *  bundle. Only the plain variant is here: a route never asks for an option-forked one. */
export const JIT_FUNCTION_IDS = {
  compactForJson: 'rpEK',
  compactFromJson: 'FFsn',
  formatTransform: 'mzca',
  fromBinary: 'rR8x',
  jsonSchema: 'VwiH',
  prepareForJsonClone: 'A0Qb',
  prepareForJsonMutate: 'AwYs',
  removeUnknownKeys: 'C85b',
  restoreFromJsonClone: 'Ky89',
  restoreFromJsonMutate: 'w8ie',
  stringifyJson: 'i4VX',
  toBinary: 'jDpZ',
  validate: 'Eq2V',
  validateStrict: 'fZHy',
  validateUnionKeys: 'Xhuv',
  validationErrors: 'swxg',
  validationErrorsStrict: 'OB5g',
  validationErrorsUnionKeys: 'OBOg',
} as const satisfies Readonly<Record<string, string>>;
