// Code generated by cmd/gen-builtin-purefns; DO NOT EDIT.
// Regenerate with `pnpm miondevx core codegen builtinpurefns` after editing the
// built-in pure-fn sources in packages/run-types/src.

// Package purefnids holds the ids of the pure functions @mionjs/run-types
// registers itself. An emitter that writes `utl.usePureFn(<id>)` into a
// generated body names it through a constant here, so moving or renaming a
// built-in fails this codegen instead of splitting one function across two ids.
// The package imports nothing, which is what lets both the extractor and the
// emitters depend on it.
package purefnids

import "sort"

// IDPrefix is what every id below starts with: the package that owns these
// pure fns. A build tells a reference to one of them apart from a reference to
// a consumer's own pure fn by this prefix, which is also how it knows a
// reference the table does not carry means a STALE table rather than a user
// pure fn it should leave alone.
const IDPrefix = "@mionjs/run-types#pf_"

const (
	IsDateStringMDY         = "@mionjs/run-types#pf_-y__pOnrgnvRMz"
	RelativeNowKey          = "@mionjs/run-types#pf_0DI2YbUTsfcoey"
	DateStrToMs             = "@mionjs/run-types#pf_0lOuvJ-q2MW6gT"
	IsTimeStringMmss        = "@mionjs/run-types#pf_2xtQHAMu-yOBo6"
	UniqueMapEntries        = "@mionjs/run-types#pf_3ALPSmgX80ATiY"
	PunycodeEncode          = "@mionjs/run-types#pf_5oCqd7YyfA9rEw"
	IsSecondsWithMs         = "@mionjs/run-types#pf_6E7qWsIwaFRGn6"
	IsIdnaLabel             = "@mionjs/run-types#pf_7SetHd9N2sVGrV"
	MatchesCardNetwork      = "@mionjs/run-types#pf_A3KjzpjelkcBST"
	IsTimeZone              = "@mionjs/run-types#pf_EYsxRHRDgAykA_"
	IsDateStringDM          = "@mionjs/run-types#pf_Eube1z0GFHuqlM"
	CountEnumKeys           = "@mionjs/run-types#pf_G5-z72czuSL8sC"
	PunycodeDecode          = "@mionjs/run-types#pf_GA20s6bj41GC1A"
	IsDateStringYM          = "@mionjs/run-types#pf_GfQK19ktpvibuZ"
	IsTimeStringHHmmss      = "@mionjs/run-types#pf_IyjvBbz0zSlgCJ"
	IsDateString            = "@mionjs/run-types#pf_MnJ72PqkyXHiSP"
	IsDateStringMD          = "@mionjs/run-types#pf_NJ9TCGDnkv_9Mn"
	CanonicalJson           = "@mionjs/run-types#pf_NsFHAjPcl6zHKH"
	IsTimeStringISO         = "@mionjs/run-types#pf_OCJ1B0-ZCAwagS"
	IsDateStringDMY         = "@mionjs/run-types#pf_PQVLEBllZckw8I"
	IsEcmaRegex             = "@mionjs/run-types#pf_Qd_9GJQlOCVqDe"
	TimeStrToMs             = "@mionjs/run-types#pf_RUAE44N0eAppE7"
	LuhnSum                 = "@mionjs/run-types#pf_VJiknJ2exR2oMF"
	IsIPV6                  = "@mionjs/run-types#pf_WMqh9KCFUZK-QD"
	IsIPV4                  = "@mionjs/run-types#pf_Yxs_8lqAG5ppIo"
	CodePointLength         = "@mionjs/run-types#pf_Z2sc5xQPKB0oav"
	UniqueArrayItems        = "@mionjs/run-types#pf_auGH9B61BMDll3"
	IsMinutes               = "@mionjs/run-types#pf_cgwpjq6rGsI8jb"
	IsHours                 = "@mionjs/run-types#pf_d8U9HjmMsNFd6Z"
	GetUnknownKeysFromArray = "@mionjs/run-types#pf_fL3v1v6aVZwJ7-"
	IsDateStringYMD         = "@mionjs/run-types#pf_gFl-yXbCxJqWgQ"
	IsTimeStringHHmm        = "@mionjs/run-types#pf_hiotRbfSKFAuK4"
	IsUUID                  = "@mionjs/run-types#pf_jzwmCOXKrhbowQ"
	IsSecondsWithLeap       = "@mionjs/run-types#pf_lFYcgG5ZSI-8em"
	FindCycle               = "@mionjs/run-types#pf_lQvUeXx-d_WXSw"
	IsSeconds               = "@mionjs/run-types#pf_n_ZOWff4X3qBMQ"
	CardNetworkRules        = "@mionjs/run-types#pf_nsU8QeJCuCF8Kr"
	IsIdnHostname           = "@mionjs/run-types#pf_oSEQKIPgV2b85k"
	IsTimeStringISOTZ       = "@mionjs/run-types#pf_qMsNYN8hy_sC8i"
	IsEmailAddress          = "@mionjs/run-types#pf_qotJfcleAqnWOD"
	NewRunTypeErr           = "@mionjs/run-types#pf_rXVwGkGDX08BsQ"
	HasUnknownKeysFromArray = "@mionjs/run-types#pf_tfRjnFZVF8lqI_"
	SatisfiesBidi           = "@mionjs/run-types#pf_vLId7t0J8HNWlN"
	UniqueSetMembers        = "@mionjs/run-types#pf_wxoIgaBn9QgDNN"
	IsCreditCard            = "@mionjs/run-types#pf_xkXrw7yD4dileP"
	IsLocalHost             = "@mionjs/run-types#pf_xlhuhlEYNnc0zQ"
)

// ids is every constant above, as a set, for Has.
var ids = map[string]bool{
	CanonicalJson:           true,
	CardNetworkRules:        true,
	CodePointLength:         true,
	CountEnumKeys:           true,
	DateStrToMs:             true,
	FindCycle:               true,
	GetUnknownKeysFromArray: true,
	HasUnknownKeysFromArray: true,
	IsCreditCard:            true,
	IsDateString:            true,
	IsDateStringDM:          true,
	IsDateStringDMY:         true,
	IsDateStringMD:          true,
	IsDateStringMDY:         true,
	IsDateStringYM:          true,
	IsDateStringYMD:         true,
	IsEcmaRegex:             true,
	IsEmailAddress:          true,
	IsHours:                 true,
	IsIPV4:                  true,
	IsIPV6:                  true,
	IsIdnHostname:           true,
	IsIdnaLabel:             true,
	IsLocalHost:             true,
	IsMinutes:               true,
	IsSeconds:               true,
	IsSecondsWithLeap:       true,
	IsSecondsWithMs:         true,
	IsTimeStringHHmm:        true,
	IsTimeStringHHmmss:      true,
	IsTimeStringISO:         true,
	IsTimeStringISOTZ:       true,
	IsTimeStringMmss:        true,
	IsTimeZone:              true,
	IsUUID:                  true,
	LuhnSum:                 true,
	MatchesCardNetwork:      true,
	NewRunTypeErr:           true,
	PunycodeDecode:          true,
	PunycodeEncode:          true,
	RelativeNowKey:          true,
	SatisfiesBidi:           true,
	TimeStrToMs:             true,
	UniqueArrayItems:        true,
	UniqueMapEntries:        true,
	UniqueSetMembers:        true,
}

// names is the identifier each built-in is bound to in source. An id is a
// hash, which names nothing a reader can search for, so a diagnostic or a
// report that has to SAY which pure function it means looks it up here.
var names = map[string]string{
	CanonicalJson:           "canonicalJson",
	CardNetworkRules:        "cardNetworkRules",
	CodePointLength:         "codePointLength",
	CountEnumKeys:           "countEnumKeys",
	DateStrToMs:             "dateStrToMs",
	FindCycle:               "findCycle",
	GetUnknownKeysFromArray: "getUnknownKeysFromArray",
	HasUnknownKeysFromArray: "hasUnknownKeysFromArray",
	IsCreditCard:            "isCreditCard",
	IsDateString:            "isDateString",
	IsDateStringDM:          "isDateString_DM",
	IsDateStringDMY:         "isDateString_DMY",
	IsDateStringMD:          "isDateString_MD",
	IsDateStringMDY:         "isDateString_MDY",
	IsDateStringYM:          "isDateString_YM",
	IsDateStringYMD:         "isDateString_YMD",
	IsEcmaRegex:             "isEcmaRegex",
	IsEmailAddress:          "isEmailAddress",
	IsHours:                 "isHours",
	IsIPV4:                  "isIPV4",
	IsIPV6:                  "isIPV6",
	IsIdnHostname:           "isIdnHostname",
	IsIdnaLabel:             "isIdnaLabel",
	IsLocalHost:             "isLocalHost",
	IsMinutes:               "isMinutes",
	IsSeconds:               "isSeconds",
	IsSecondsWithLeap:       "isSecondsWithLeap",
	IsSecondsWithMs:         "isSecondsWithMs",
	IsTimeStringHHmm:        "isTimeString_HHmm",
	IsTimeStringHHmmss:      "isTimeString_HHmmss",
	IsTimeStringISO:         "isTimeString_ISO",
	IsTimeStringISOTZ:       "isTimeString_ISO_TZ",
	IsTimeStringMmss:        "isTimeString_mmss",
	IsTimeZone:              "isTimeZone",
	IsUUID:                  "isUUID",
	LuhnSum:                 "luhnSum",
	MatchesCardNetwork:      "matchesCardNetwork",
	NewRunTypeErr:           "newRunTypeErr",
	PunycodeDecode:          "punycodeDecode",
	PunycodeEncode:          "punycodeEncode",
	RelativeNowKey:          "relativeNowKey",
	SatisfiesBidi:           "satisfiesBidi",
	TimeStrToMs:             "timeStrToMs",
	UniqueArrayItems:        "uniqueArrayItems",
	UniqueMapEntries:        "uniqueMapEntries",
	UniqueSetMembers:        "uniqueSetMembers",
}

// NameOf returns the identifier a built-in is bound to in source, or empty
// when id names no built-in.
func NameOf(id string) string {
	return names[id]
}

// Has reports whether id names one of the package's own pure functions.
// Their bodies never come from a consumer's program — the compiler extracts
// them from the package's own sources — so a build checks a reference to one
// against this set instead of against the registrations it extracted.
func Has(id string) bool {
	return ids[id]
}

// SourceFiles are this package's files that register a pure function, relative
// to its root. Scanned for a registrar call when this file was generated and
// narrowed to the files that produced an entry, so there is nothing to keep in
// sync and nothing to scan at build time: the resolver resolves these against
// whatever root it finds the installed package at, and a path the install does
// not have is CFG004.
var SourceFiles = []string{
	"src/formats/datetime/dateTime-pure-fns.ts",
	"src/formats/string/credit-card-pure-fns.ts",
	"src/formats/string/string-formats-pure-fns.ts",
	"src/runtypes/circular-pure-fns.ts",
	"src/runtypes/pure-fns-utils.ts",
}

// All returns every built-in id, sorted. An id is a hash of the body that
// ships, so a test can assert that each one still resolves from the sources and
// catch a body edited without regenerating this file.
func All() []string {
	out := make([]string, 0, len(ids))
	for id := range ids {
		out = append(out, id)
	}
	sort.Strings(out)
	return out
}
