// Code generated by cmd/gen-builtin-purefns; DO NOT EDIT.
// Regenerate with `pnpm miondevx core codegen builtinpurefns` after editing the
// built-in pure-fn sources in packages/run-types/src.

// Package purefnids holds the ids of the pure functions @mionjs/run-types
// registers itself. An emitter that writes `utl.usePureFn(<id>)` into a
// generated body names it through a constant here, so moving or renaming a
// built-in fails this codegen instead of splitting one function across two ids.
// The package imports nothing, which is what lets both the extractor and the
// emitters depend on it.
package purefnids

// IDPrefix is what every id below starts with: the package that owns these
// pure fns. A build tells a reference to one of them apart from a reference to
// a consumer's own pure fn by this prefix, which is also how it knows a
// reference the table does not carry means a STALE table rather than a user
// pure fn it should leave alone.
const IDPrefix = "@mionjs/run-types/"

const (
	DateStrToMs             = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#dateStrToMs"
	IsDateString            = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isDateString"
	IsDateStringDM          = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isDateString_DM"
	IsDateStringDMY         = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isDateString_DMY"
	IsDateStringMD          = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isDateString_MD"
	IsDateStringMDY         = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isDateString_MDY"
	IsDateStringYM          = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isDateString_YM"
	IsDateStringYMD         = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isDateString_YMD"
	IsHours                 = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isHours"
	IsMinutes               = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isMinutes"
	IsSeconds               = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isSeconds"
	IsSecondsWithLeap       = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isSecondsWithLeap"
	IsSecondsWithMs         = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isSecondsWithMs"
	IsTimeStringHHmm        = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isTimeString_HHmm"
	IsTimeStringHHmmss      = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isTimeString_HHmmss"
	IsTimeStringISO         = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isTimeString_ISO"
	IsTimeStringISOTZ       = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isTimeString_ISO_TZ"
	IsTimeStringMmss        = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isTimeString_mmss"
	IsTimeZone              = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#isTimeZone"
	RelativeNowKey          = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#relativeNowKey"
	TimeStrToMs             = "@mionjs/run-types/src/formats/datetime/dateTime-pure-fns#timeStrToMs"
	CardNetworkRules        = "@mionjs/run-types/src/formats/string/credit-card-pure-fns#cardNetworkRules"
	IsCreditCard            = "@mionjs/run-types/src/formats/string/credit-card-pure-fns#isCreditCard"
	LuhnSum                 = "@mionjs/run-types/src/formats/string/credit-card-pure-fns#luhnSum"
	MatchesCardNetwork      = "@mionjs/run-types/src/formats/string/credit-card-pure-fns#matchesCardNetwork"
	CodePointLength         = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#codePointLength"
	IsEcmaRegex             = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isEcmaRegex"
	IsEmailAddress          = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isEmailAddress"
	IsIPV4                  = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isIPV4"
	IsIPV6                  = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isIPV6"
	IsIdnHostname           = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isIdnHostname"
	IsIdnaLabel             = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isIdnaLabel"
	IsLocalHost             = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isLocalHost"
	IsUUID                  = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#isUUID"
	PunycodeDecode          = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#punycodeDecode"
	PunycodeEncode          = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#punycodeEncode"
	SatisfiesBidi           = "@mionjs/run-types/src/formats/string/string-formats-pure-fns#satisfiesBidi"
	FindCycle               = "@mionjs/run-types/src/runtypes/circular-pure-fns#findCycle"
	CanonicalJson           = "@mionjs/run-types/src/runtypes/pure-fns-utils#canonicalJson"
	CountEnumKeys           = "@mionjs/run-types/src/runtypes/pure-fns-utils#countEnumKeys"
	GetUnknownKeysFromArray = "@mionjs/run-types/src/runtypes/pure-fns-utils#getUnknownKeysFromArray"
	HasUnknownKeysFromArray = "@mionjs/run-types/src/runtypes/pure-fns-utils#hasUnknownKeysFromArray"
	NewRunTypeErr           = "@mionjs/run-types/src/runtypes/pure-fns-utils#newRunTypeErr"
	UniqueArrayItems        = "@mionjs/run-types/src/runtypes/pure-fns-utils#uniqueArrayItems"
	UniqueMapEntries        = "@mionjs/run-types/src/runtypes/pure-fns-utils#uniqueMapEntries"
	UniqueSetMembers        = "@mionjs/run-types/src/runtypes/pure-fns-utils#uniqueSetMembers"
)

// ids is every constant above, as a set, for Has.
var ids = map[string]bool{
	CanonicalJson:           true,
	CardNetworkRules:        true,
	CodePointLength:         true,
	CountEnumKeys:           true,
	DateStrToMs:             true,
	FindCycle:               true,
	GetUnknownKeysFromArray: true,
	HasUnknownKeysFromArray: true,
	IsCreditCard:            true,
	IsDateString:            true,
	IsDateStringDM:          true,
	IsDateStringDMY:         true,
	IsDateStringMD:          true,
	IsDateStringMDY:         true,
	IsDateStringYM:          true,
	IsDateStringYMD:         true,
	IsEcmaRegex:             true,
	IsEmailAddress:          true,
	IsHours:                 true,
	IsIPV4:                  true,
	IsIPV6:                  true,
	IsIdnHostname:           true,
	IsIdnaLabel:             true,
	IsLocalHost:             true,
	IsMinutes:               true,
	IsSeconds:               true,
	IsSecondsWithLeap:       true,
	IsSecondsWithMs:         true,
	IsTimeStringHHmm:        true,
	IsTimeStringHHmmss:      true,
	IsTimeStringISO:         true,
	IsTimeStringISOTZ:       true,
	IsTimeStringMmss:        true,
	IsTimeZone:              true,
	IsUUID:                  true,
	LuhnSum:                 true,
	MatchesCardNetwork:      true,
	NewRunTypeErr:           true,
	PunycodeDecode:          true,
	PunycodeEncode:          true,
	RelativeNowKey:          true,
	SatisfiesBidi:           true,
	TimeStrToMs:             true,
	UniqueArrayItems:        true,
	UniqueMapEntries:        true,
	UniqueSetMembers:        true,
}

// Has reports whether id names one of the package's own pure functions.
// Their bodies never come from a consumer's program — the compiler serves them
// from its own table — so a build checks a reference to one against this set
// instead of against the registrations it extracted.
func Has(id string) bool {
	return ids[id]
}
